### ISSUE TITLE
Feat : Add description and Categorize tool & Sorting option addition

### ISSUE THREAD

**Issue by itsarraj** [JasonDsouza212/free-hit#101]
Problem : if people don't know what tool they need ,
solution : need to add some tags with each tools , 

p: if we sort in alphabetical order that wont solve the problem 
s: we should make a sort option to
 - sort in accending 
 - sort in decending 
 - sort by popularity ( default )
 - sort by date released 
 - sort by added (in website)
 
 and many more options for people to find tools
 
 note - search option will do no good because they can seach on goole than prefer this site , we have to solve problem by categorize the toold based on thier use and we should give brief description that where we can use this tool .

**Comment by JasonDsouza212** [comment]
That's a good suggestion, but as far as I know, to sort it according to popularity, we need to store it in some kind of database. Giving static data for popularity is not a good idea. Sorting in ascending and descending order can be a good idea. To sort by date, we can add a new field in the Products.json file, but I don't think sorting it according to date is of much use.

**Comment by itsarraj** [comment]
Then Let's Finalize it to sort by popularity , accending decending , that's all
and for sorting have a discussion on what we will use. a .json file for db or simple static js sorting and rendering at time user choose short

**Comment by JasonDsouza212** [comment]
can do only ascending and descending sort

**Comment by itsarraj** [comment]
okay

**Comment by itsarraj** [comment]
in js or make db

**Comment by JasonDsouza212** [comment]
I didn't get you @itsarraj

**Comment by itsarraj** [comment]
are we making database or sore these data in json as we are using it.
