### ISSUE TITLE
[Feat]:  Adding a chat BOT in website

### ISSUE THREAD

**Issue by marshadkhn** [JasonDsouza212/free-hit#1017]
### What feature?

I have an idea of adding a chat bot in website like most of the website
That AI chat bot will do following things
- Tell the user what this website is all about and chat with the user
- Tell the user where to find what he/she asking for
- Tell the weather if needed
and many more things that can an AI do

### Add screenshots

![image](https://github.com/JasonDsouza212/free-hit/assets/80325579/5d2faa21-e0e4-4fd3-86af-a5c5f99b0c4f)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by marshadkhn** [comment]
@JasonDsouza212

**Comment by JasonDsouza212** [comment]
@marshadkhn sounds amazing

**Comment by marshadkhn** [comment]
@JasonDsouza212 
Thankyou for this
Soon I'll send PR

**Comment by akanksha984** [comment]
Please assign this issue to me

**Comment by marshadkhn** [comment]
Please assign this issue to @akanksha984
