### ISSUE TITLE
BUG: fix the card hight

### ISSUE THREAD

**Issue by priyankarpal** [JasonDsouza212/free-hit#102]
## Need to fix the card height

![image](https://user-images.githubusercontent.com/88102392/229397067-57b74a89-db28-4f99-a512-26c6a9f6bbe9.png)

**Comment by itsarraj** [comment]
We can't always change height , Based on description or information . We should make a readmore and provide another descriptive page or popup

**Comment by priyankarpal** [comment]
> We can't always change height , Based on description or information . We should make a readmore and provide another descriptive page or popup

I think we need to change the whole card design. what do you think?  🤔

**Comment by JasonDsouza212** [comment]
- Until we change the card design, let's limit the description to a maximum of 12 words. Also, @priyankarpal  could you let me know the dimensions at which you are encountering this bug?
- As for @itsarraj's suggestion, it sounds good. However, I have a question: there is a small description and a 'Visit Website' button, when users click on the button, they be able to view more information so why to create another page for that?

**Comment by priyankarpal** [comment]
> * Until we change the card design, let's limit the description to a maximum of 12 words. Also, @priyankarpal  could you let me know the dimensions at which you are encountering this bug?
> * As for @itsarraj's suggestion, it sounds good. However, I have a question: there is a small description and a 'Visit Website' button, when users click on the button, they be able to view more information so why to create another page for that?

yeah we can limit the description length.

**Comment by itsarraj** [comment]
Okay Limit the description

**Comment by priyankarpal** [comment]
hi, @JasonDsouza212 I solved the problem & created a PR please check.

**Comment by JasonDsouza212** [comment]
can you add some screen shots @priyankarpal

**Comment by priyankarpal** [comment]
> can you add some screen shots @priyankarpal

yeah wait

**Comment by priyankarpal** [comment]
> can you add some screen shots @priyankarpal

check the PR https://github.com/JasonDsouza212/free-hit/pull/105
