### ISSUE TITLE
Add AI section

### ISSUE THREAD

**Issue by JasonDsouza212** [JasonDsouza212/free-hit#103]
There are many free AI tools available, and AI is becoming increasingly popular and useful. 
Therefore, it would be beneficial to create a separate section dedicated to AI, and list some of the most useful tools under it.

**Comment by JasonDsouza212** [comment]
https://www.useblackbox.io/

**Comment by priyankarpal** [comment]
> There are many free AI tools available, and AI is becoming increasingly popular and useful. Therefore, it would be beneficial to create a separate section dedicated to AI and list some of the most useful tools under it.

I want to work on it. could you assign me?

**Comment by JasonDsouza212** [comment]
@priyankarpal  remove the code to image section and merge it with useful tool after that create a section for AI
