### ISSUE TITLE
[Docs]: improve docs

### ISSUE THREAD

**Issue by priyankarpal** [JasonDsouza212/free-hit#1032]
### what's wrong in the documentation?

in contributing guide & readme file there are lots of unnecessary lines we need to remove those & highlight valid lines

### Add screenshots

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by navvvgupta** [comment]
Heyy I am new to Open Source community and would like to sovle this issue,can you assign me this issue?

**Comment by priyankarpal** [comment]
> Heyy I am new to Open Source community and would like to solve this issue, can you assign me this issue?

currently I'm working on this issue
