### ISSUE TITLE
[Feat]: Adding HDHub4u 

### ISSUE THREAD

**Issue by Vaibhav9027** [JasonDsouza212/free-hit#1040]
### What feature?

I have an idea to add HDHub4u
This website allows you to download various movies and web series for free.
Please assign me this under GSSOC'23.

### Add screenshots

![Screenshot (112)](https://github.com/JasonDsouza212/free-hit/assets/115151167/a011eea0-27bc-4590-aac9-cdfabe673df7)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JasonDsouza212** [comment]
The template you used is incorrect. Please use the correct template and create a new issue.
