### ISSUE TITLE
[Feat]:  Add LearnVern website

### ISSUE THREAD

**Issue by Parul1606** [JasonDsouza212/free-hit#1066]
### What feature?

I would like to add LearnVern website. 
This website provides free courses to the students.
You can checkout: https://www.learnvern.com/

### Add screenshots

![image](https://github.com/JasonDsouza212/free-hit/assets/80768852/02f8aafb-19b7-4b6b-91aa-1a8c6fbc97a9)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JasonDsouza212** [comment]
The template you used is incorrect. Please use the correct template and create a new issue.
