### ISSUE TITLE
[Feat]: Add Good First Issue

### ISSUE THREAD

**Issue by Parul1606** [JasonDsouza212/free-hit#1068]
### What feature?

I would like to add Good First Issue website.
This website provides begineer programmer to work on simple and easy web development projects. 
You can checkout: https://goodfirstissue.dev/

### Add screenshots

![image](https://github.com/JasonDsouza212/free-hit/assets/80768852/5439c936-349b-489d-b541-191ae5ca8d98)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JasonDsouza212** [comment]
The template you used is incorrect. Please use the correct template and create a new issue.
