### ISSUE TITLE
[Feat]: Add Campusgate

### ISSUE THREAD

**Issue by Parul1606** [JasonDsouza212/free-hit#1069]
### What feature?

I would like to add Campusgate - Platform to prepare for interview.

### Add screenshots

![image](https://github.com/JasonDsouza212/free-hit/assets/80768852/98f3943e-d527-47db-b7d5-be3b8d36b6ef)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JasonDsouza212** [comment]
The template you used is incorrect. Please use the correct template and create a new issue.
