### ISSUE TITLE
[Feat]: Add Indiabix

### ISSUE THREAD

**Issue by Parul1606** [JasonDsouza212/free-hit#1070]
### What feature?

I would like to add IndiaBix - Platform to prepare for aptitude

### Add screenshots

![image](https://github.com/JasonDsouza212/free-hit/assets/80768852/8bacd29c-c5cb-471f-b018-563d73f5c400)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JasonDsouza212** [comment]
The template you used is incorrect. Please use the correct template and create a new issue.
