### ISSUE TITLE
[Feat]: Add PrepInsta

### ISSUE THREAD

**Issue by Parul1606** [JasonDsouza212/free-hit#1072]
### What feature?

I would like to add PrepInsta - platform to prepare for aptitude

### Add screenshots

![image](https://github.com/JasonDsouza212/free-hit/assets/80768852/bd936fb6-6739-4196-b4bf-83308bbedb0c)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JasonDsouza212** [comment]
The template you used is incorrect. Please use the correct template and create a new issue.
