### ISSUE TITLE
[Feat]: Add Flexbox Froggy

### ISSUE THREAD

**Issue by Parul1606** [JasonDsouza212/free-hit#1074]
### What feature?

I would like to add Flexbox Froggy - website where a learner can learn CSS playing game

### Add screenshots

![image](https://github.com/JasonDsouza212/free-hit/assets/80768852/0e1a9669-c63e-407b-ab06-4627fbbac1b6)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JasonDsouza212** [comment]
The template you used is incorrect. Please use the correct template and create a new issue.
