### ISSUE TITLE
[Feat]: Add Jenkins

### ISSUE THREAD

**Issue by Karmpatel960** [JasonDsouza212/free-hit#1077]
### What feature?

The leading open source automation server, Jenkins provides hundreds of plugins to support building, deploying and automating any project.

### Add screenshots

<img width="952" alt="image" src="https://github.com/JasonDsouza212/free-hit/assets/96860884/591d7dfd-f6ec-4261-b3b1-7494346434ca">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JasonDsouza212** [comment]
The template you used is incorrect. Please use the correct template and create a new issue.
