### ISSUE TITLE
[Feat]: Add Selenium

### ISSUE THREAD

**Issue by Karmpatel960** [JasonDsouza212/free-hit#1080]
### What feature?

Primarily it is for automating web applications for testing purposes, but is certainly not limited to just that.

Boring web-based administration tasks can also be automated as well.

### Add screenshots

<img width="925" alt="image" src="https://github.com/JasonDsouza212/free-hit/assets/96860884/606d5629-ce2b-44e6-bd39-c90bd39eabd5">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JasonDsouza212** [comment]
The template you used is incorrect. Please use the correct template and create a new issue.
