### ISSUE TITLE
[Feat]: Add Docker

### ISSUE THREAD

**Issue by Karmpatel960** [JasonDsouza212/free-hit#1082]
### What feature?

Docker takes away repetitive, mundane configuration tasks and is used throughout the development lifecycle for fast, easy and portable application development – desktop and cloud. Docker’s comprehensive end to end platform includes UIs, CLIs, APIs and security that are engineered to work together across the entire application delivery lifecycle.

### Add screenshots

<img width="907" alt="image" src="https://github.com/JasonDsouza212/free-hit/assets/96860884/a54d691c-64ad-4467-9d28-7f3f4bf116e7">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by navvvgupta** [comment]
Heyy I am new to Open Source Community, can you assign me this task?

**Comment by JasonDsouza212** [comment]
The template you used is incorrect. Please use the correct template and create a new issue.
