### ISSUE TITLE
[Adding Tool]: Add Kubernetes

### ISSUE THREAD

**Issue by Karmpatel960** [JasonDsouza212/free-hit#1084]
### What tool are you adding and to what category?

We need to add Production-Grade Container Orchestration

### Add Tool Link

https://kubernetes.io/

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] The tool is free for use

**Comment by JasonDsouza212** [comment]
We need Free-hit to include unique and lesser-known tools that people can use. Since the tool you mentioned is already well-known, I will be closing this issue for that reason.
