### ISSUE TITLE
Restructuring the Navbar

### ISSUE THREAD

**Issue by the-amazing-atharva** [JasonDsouza212/free-hit#109]
Hey!

I think having the Free-Hit to the left will look better.
I would like to be assigned and work on it if approved!

![image](https://user-images.githubusercontent.com/121221252/230013264-4170213f-08fb-42be-a7dc-89606621ce25.png)

**Comment by JasonDsouza212** [comment]
We are currently thinking of adding a logo to the website. So, after that change, if you feel like it's not good, you can raise an issue then

**Comment by the-amazing-atharva** [comment]
Oh ok!
