### ISSUE TITLE
[Adding Tool]: Add Illustroke

### ISSUE THREAD

**Issue by Parul1606** [JasonDsouza212/free-hit#1090]
### What tool are you adding and to what category?

We need to add Illustroke | Vector illustrations from text prompts AI. would like to add this in useful tools(tools) category.

### Add Tool Link

tool link: https://illustroke.com/

![image](https://github.com/JasonDsouza212/free-hit/assets/80768852/16fa0889-d7b2-4c83-9864-4da5a474eeb1)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] The tool is free for use

**Comment by itsajay1029** [comment]
Can you assign this to me @Parul1606 ?

**Comment by Parul1606** [comment]
I have raised this issue, once I'm done with it then if there's any problem in it then you may raise another issue and can work on it.

**Comment by itsajay1029** [comment]
> I have raised this issue, once I'm done with it then if there's any problem in it then you may raise another issue and can work on it.

Sure, no problem. Best of luck.

**Comment by itsajay1029** [comment]
Can you explain the issue @JasonDsouza212 ?

**Comment by Parul1606** [comment]
@itsajay1029   You have to add the illustroke tool as I have mentioned above with its link. Tool has to be added in src/db/product.json. It should have its name, category, link, image & desc. Make sure image link is shortened and description of the website is within 9 to 10 words. Follow contributing.md for more clearity. And if there's any other help you need, feel free to ask.
