### ISSUE TITLE
[Feat]: Browser extension of the website

### ISSUE THREAD

**Issue by VivekYadav105** [JasonDsouza212/free-hit#1094]
### What feature?

This website can be extended to an browser extension and  there user can list the website he wants through a search bar

### Add screenshots

this is a sample view of the feature
![image](https://github.com/JasonDsouza212/free-hit/assets/82657104/c3e56e41-0e20-47b0-901e-b73d3e096192)
user can select the desired type of the website he wants in the search section
![image](https://github.com/JasonDsouza212/free-hit/assets/82657104/01e466ab-c257-4cb2-9511-adb423c7b0e4)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JasonDsouza212** [comment]
Looks amazing. create a PR tomorrow
