### ISSUE TITLE
[Feat]: Add CSS Challenges to "Frontend Tools"

### ISSUE THREAD

**Issue by BALASARVAN12** [JasonDsouza212/free-hit#1096]
### What feature?

- CSS Challenges is a resource that offers fun and playful ways to practice your CSS skills. You can do that by playing CSS challenges/riddles or by taking quizzes. 
- For challenges, you’ll find five different difficulty levels starting from easy, ranging all the way up to insane. 
- For each challenge, you have a preview image and a set of rules to match it, the main rule for all challenges is to use CSS code only.
- Here is the link:https://css-challenges.com/

### Add screenshots

Add screenshots
![image](https://github.com/JasonDsouza212/free-hit/assets/91976828/21ce0406-5141-4f8c-bbf4-a04472ae9c2f) 
<br><br> ![image](https://github.com/JasonDsouza212/free-hit/assets/91976828/c4b72a04-017c-4aaf-a883-0c30012ac688)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by JasonDsouza212** [comment]
The template you used is incorrect. Please use the correct template and create a new issue.
