### ISSUE TITLE
[Adding Tool]: Flexbox froggy

### ISSUE THREAD

**Issue by Parul1606** [JasonDsouza212/free-hit#1106]
### What tool are you adding and to what category?

We need to add Flexbox Froggy - website where a learner can learn CSS playing game. We should add this in coding category.

### Add Tool Link

tool link: https://flexboxfroggy.com

![image](https://github.com/JasonDsouza212/free-hit/assets/80768852/8bc36079-8792-48cb-a81e-73e6a2240249)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] The tool is free for use

**Comment by VenomFate-619** [comment]
add this into a new category name coding games

**Comment by Parul1606** [comment]
there's nothing like coding games category, I can just see coding platforms category.
