### ISSUE TITLE
[FEAT] Updates to Issue templates 🛠

### ISSUE THREAD

**Issue by tamalCodes** [JasonDsouza212/free-hit#111]
### Reason/Context

I  am suggesting to update the Issue templates , currently we are using `.md` files instead of the brand new issue forms with `.yml` files.

### Why to update it ? 

- The `.yml` based issue templates makes it more easier to organize, ask your questions, add screenshots and choose other options as necessary
- Plus, we can add "custom" labels to the issue template which makes it more organized than having a bot/user do it.

### Relevant screenshots

![image](https://user-images.githubusercontent.com/72851613/192107388-3b5564d1-4efc-4e05-8fd8-ecb271136a77.png)

![image](https://user-images.githubusercontent.com/72851613/193424759-6ff15f6b-c43a-4de2-bcab-931bc9e06ec3.png)

### Am i willing to work on it ? 

Yes, i will be glad to help an Opensource project grow more !

### Detailed description

I am talking about the **issue templates** which can be wrote using `.yml` , inside the `.github > ISSUE_TEMPLATES` . 
Yes the bot is cool TBH, but the `.yml` based issue template is cooler. 

Currently we are throwing in a markdown based Issue template. The problem is the user may/maynot fill in some fields. Then the maintainers again would have to ask them to fill those. Additionally, It's also not much of a beginner friendly thing, because all someone would see is questions and might be confused on how to structure their issue.

So adding proper, structured issue templates would be helpful for both the contributors as well as the maintainers to manage their repository.

### Features of adding these issue templates
- Required fields
- Less dependant on bots
- Proper options for mentioning their `browsers` , `operating systems` and more.
- Interactive Check boxes to confirm if they have read the `guidelines` and more.
- Better Developer experience. 

#### What currently it is :
![image](https://user-images.githubusercontent.com/72851613/229232690-fa5757d4-2a58-4670-ad4d-a31efe0d4caf.png)

#### What i am suggesting it to be :
![image](https://user-images.githubusercontent.com/72851613/223151657-bf387224-d8cd-47f3-b78a-0549ecb2286b.png)

**Comment by JasonDsouza212** [comment]
Hey @IAmTamal  you mentioned that you would be working on this. Are you going to complete this issue?

**Comment by IAmTamal** [comment]
Hi @JasonDsouza212 , i cannot continue it as of now because of overwhelming exams. Either I can do it later; else you can assign someone else and remove me. Hope you understand, thanks !

**Comment by JasonDsouza212** [comment]
Ok no problem @IAmTamal
