### ISSUE TITLE
Some links are not working

### ISSUE THREAD

**Issue by suzy-g38** [JasonDsouza212/free-hit#112]
Some links especially in the 'movies and series' tab, some links like Pogo, and Soap2Day are not working.

**Comment by JasonDsouza212** [comment]
Do you want to work on it??

**Comment by suzy-g38** [comment]
> Do you want to work on it??

Yeah sure.

**Comment by raunakgurud09** [comment]
Hey, @suzy-g38  are you still working on it?

**Comment by suzy-g38** [comment]
> Hey, @suzy-g38 are you still working on it?

Oh yess, sorry I was out of station for some days that's why it's getting delayed. Really sorry for that. I will create a pr by eod.

**Comment by Vaishu03** [comment]
hey @JasonDsouza212 can you assign this task to me?

**Comment by Gautam-10137** [comment]
@JasonDsouza212 Please assign me this issue under GSSOC'23

**Comment by JasonDsouza212** [comment]
Ok I can do that
