### ISSUE TITLE
[style]:  Changing the style at the bottom of projects buttons

### ISSUE THREAD

**Issue by marshadkhn** [JasonDsouza212/free-hit#1153]
### What's the style idea?

**We need to improve the style of next page as there are many page of projects and on the screen it's visible only three so as my approach first 3 and last 3 pages number should be able to visible for user. Guess the user wants to go to last and first page**

**What we can do**
### Make visible like -   < 1 2 3 ... 4 5 6 >

**Reason for requesting this change**
As I am visiting the page and wants to get on last page but I have to click alot times to `next` button

### Add screenshots

**Place where the change will happen**
![image](https://github.com/JasonDsouza212/free-hit/assets/80325579/9a498969-269e-4aab-a914-9e8bd1bd3a70)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JasonDsouza212** [comment]
The user also needs to know the current page and what are your plans for the mobile view.

**Comment by marshadkhn** [comment]
Same for the website just will make the box size small

**Comment by marshadkhn** [comment]
.

**Comment by biplavmz** [comment]
Hii @JasonDsouza212  I would like to work on this if @marshadkhn  is not working on this issue.

**Comment by marshadkhn** [comment]
Working just one module is left will complete tomorrow

**Comment by marshadkhn** [comment]
Please assign it to @biplavmz

**Comment by biplavmz** [comment]
Hii @JasonDsouza212 can you pls look into this I would like to work pls assign me this task.
