### ISSUE TITLE
suggest: migrate to tailwind css

### ISSUE THREAD

**Issue by priyankarpal** [JasonDsouza212/free-hit#116]
Currently, we are using CSS for this project. We can use Tailwind CSS too. I know it's complicated to migrate but if we do it it would be great.

**Comment by JasonDsouza212** [comment]
Ya, I was thinking the same. Do you want to work on this @priyankarpal

**Comment by priyankarpal** [comment]
> Ya, I was thinking the same. Do you want to work on this @priyankarpal

yes.

**Comment by priyankarpal** [comment]
@JasonDsouza212 I need some time to do that

**Comment by JasonDsouza212** [comment]
Ok take your time no hurry

**Comment by nilayjain0611** [comment]
If not done yet, I can step into this...

**Comment by priyankarpal** [comment]
@JasonDsouza212 check the color code. is it ok? check the image as a demo

 Neon blue `#2272FF`, black `#1D1D11`

![image](https://user-images.githubusercontent.com/88102392/230842304-00c9239b-65d5-45c0-a7bb-ba0f504fd19d.png)

**Comment by priyankarpal** [comment]
ig we need to close this issue
