### ISSUE TITLE
GSSoC'23: Home Page Redesign 

### ISSUE THREAD

**Issue by ShreyaDhiman24** [JasonDsouza212/free-hit#1163]
### What feature?

[Screencast from 04-07-23 02:41:15 PM IST.webm](https://github.com/JasonDsouza212/free-hit/assets/98320971/fabadcdb-1f1d-4f4f-886d-68691ad5e224)

### Add screenshots

level 3 issue which was closed due to some workflow issues #653 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JasonDsouza212** [comment]
@ShreyaDhiman24 create a PR , Ill let you know what all changes we need
