### ISSUE TITLE
[Adding Tool]: Adding Jenkins

### ISSUE THREAD

**Issue by deepshikha2708** [JasonDsouza212/free-hit#1165]
### What tool are you adding and to what category?

We need to add

Jenkins is an open source automation server. It helps automate the parts of software development related to building, testing, and deploying, facilitating continuous integration and continuous delivery

### Add Tool Link

https://www.jenkins.io/

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] The tool is free for use

**Comment by JasonDsouza212** [comment]
We need Free-hit to include unique and lesser-known tools that people can use. Since the tool you mentioned is already well-known, I will be closing this issue for that reason.
