### ISSUE TITLE
[Adding Tool]: adding Ansible

### ISSUE THREAD

**Issue by deepshikha2708** [JasonDsouza212/free-hit#1166]
### What tool are you adding and to what category?

We need to add
Ansible is an IT automation tool. It can configure systems, deploy software, and orchestrate more advanced IT tasks such as continuous deployments or zero downtime rolling updates.

Ansible’s main goals are simplicity and ease-of-use. It also has a strong focus on security and reliability, featuring a minimum of moving parts, usage of OpenSSH for transport (with other transports and pull modes as alternatives), and a language that is designed around auditability by humans–even those not familiar with the program.

### Add Tool Link

Add tool link
https://www.ansible.com/

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] The tool is free for use

**Comment by JasonDsouza212** [comment]
We need Free-hit to include unique and lesser-known tools that people can use. Since the tool you mentioned is already well-known, I will be closing this issue for that reason.
