### ISSUE TITLE
adding new tools to different category

### ISSUE THREAD

**Issue by Komal73** [JasonDsouza212/free-hit#1169]
### What tool are you adding and to what category?

I need to add some tools to coding platforms, and other tools

### Add Tool Link

Add tool link:
coding- ninjas : https://www.codingninjas.com/studio/home
background- remover : https://www.remove.bg/
slazzer : https://www.slazzer.com/
ppt maker: https://slidesgo.com/ai-presentations
uBlock Origin(content blocker) : https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] The tool is free for use

**Comment by Komal73** [comment]
@JasonDsouza212 kindly assign me this issue under GSSOC 23

**Comment by JasonDsouza212** [comment]
@Komal73 coding Ninja is already in the DB

**Comment by Komal73** [comment]
Thanks @JasonDsouza212, will add some other tools

**Comment by Komal73** [comment]
thank you so much @VenomFate-619
