### ISSUE TITLE
Help needed with creating an about page

### ISSUE THREAD

**Issue by JasonDsouza212** [JasonDsouza212/free-hit#118]
I would appreciate some help in creating an **About** page for the project. The **About** page should contain information about Free-Hit, including the project's history, goals, and features. It should also showcase the Free-Hit details about the contributors who have worked on the project.

I'm looking for contributors who are interested in helping with this task. If you have any experience with creating **About** pages and would like to contribute, Do let me know.

**Comment by itsarraj** [comment]
Okay , Will DO

**Comment by JasonDsouza212** [comment]
Shall I assign it to you

**Comment by itsarraj** [comment]
@JasonDsouza212 Yes , Details bhi dedo kya kya dala jai , koi rough details , baki ham kar lenge

**Comment by itsarraj** [comment]
@JasonDsouza212 Give me rough details exactly what are important that has to be shown & rest I will make .

**Comment by JasonDsouza212** [comment]
The About page should include information on the usage of Free-hit, its goals, and the features it provides to the user. Additionally, it should have a link to the repository and a section highlighting all its contributors.
I suggest making the About page more futuristic with appealing designs. You could use routing, such as React Router DOM, to navigate between the About and Tools pages

**Comment by JasonDsouza212** [comment]
It would be great to have a share button that allows users to share the project on social media platforms such as LinkedIn or Twitter.

**Comment by itsarraj** [comment]
Okay , need a little time give me 10-15 days , i will get ideas and will implement some on figma 
, after testing then i will final the UI/UX ok ?

**Comment by itsarraj** [comment]
> @JasonDsouza212 I have experience of making pages like about, contact and more... Can i work on this issue 

I was working on design , Do you have premade figma designs , post screensorts here , let's final a design

**Comment by Bharadwajshivam28** [comment]
currently i dont have design but i can share by tommorow

**Comment by Bharadwajshivam28** [comment]
okay

**Comment by JasonDsouza212** [comment]
Any of you familiar with Next.js and also good at web designing

**Comment by Bharadwajshivam28** [comment]
yes i am familiar with next js

**Comment by JasonDsouza212** [comment]
If your interested I can walk you through the changes we are planning to do

**Comment by Bharadwajshivam28** [comment]
ya sure

**Comment by itsarraj** [comment]
its been 34 days and still no progress on this 
@JasonDsouza212 I am working on it Give me Design Idea or Description of About page i will complete it

**Comment by JasonDsouza212** [comment]
We have a new UI, @itsarraj  If you have any enhancement plans, please let me know so that we can discuss them.

**Comment by itsarraj** [comment]
Share UI , Let me have a look ,
