### ISSUE TITLE
[Adding Tool]: pdf filler

### ISSUE THREAD

**Issue by deepshikha2708** [JasonDsouza212/free-hit#1184]
### What tool are you adding and to what category?

We need to add
Adding pdfFiller which is a free pdf editing website.

### Add Tool Link

Add tool link
https://www.pdffiller.com

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] The tool is free for use

**Comment by Stanzin7** [comment]
Hey I can work on this issue, thanks )
