### ISSUE TITLE
[Adding Tool]: Clothes shopping websites

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [JasonDsouza212/free-hit#1191]
### What tool are you adding and to what category?

We need to add

- Flipkart
- Meesho
- Bebkoof
- Myntra, etc.

I would like to add these websites please assign it to me

### Add Tool Link

Add tool link

![image](https://github.com/JasonDsouza212/free-hit/assets/114330097/40fc0337-7f8c-4bc1-b466-801dbd1b48ef)

[Bebkoof](https://www.bewakoof.com/)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] The tool is free for use

**Comment by Avdhesh-Varshney** [comment]
@JasonDsouza212 @VenomFate-619 Sirs, please assign this task to me

**Comment by JasonDsouza212** [comment]
@Avdhesh-Varshney, no, we need unique websites that are free and these don't match our genre.
