### ISSUE TITLE
[Adding Tool]: Adding Google Websites links

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [JasonDsouza212/free-hit#1192]
### What tool are you adding and to what category?

We need to add

- Drive
- Google sheets
- Google Keep
- Google Classroom
- Google photos
- Google Calendar

### Add Tool Link

Add tool link

<img src="https://cdn.thewirecutter.com/wp-content/uploads/2020/04/googleclassroom-studentview-lowres.jpg?auto=webp&quality=75&width=1024" />

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
- [x] The tool is free for use

**Comment by Avdhesh-Varshney** [comment]
@JasonDsouza212 @VenomFate-619 Sirs, please assign this task to me

**Comment by JasonDsouza212** [comment]
@VenomFate-619, we want our app to include unique tools that are lesser known to people.
