### ISSUE TITLE
[Feat]:  make social anchors accessible for about contributors section 💡

### ISSUE THREAD

**Issue by 0xabdulkhalid** [JasonDsouza212/free-hit#1197]
### What feature?

- I have an idea about making the social anchor of footer accessible for screen readers.

- Currently the issue is about adding `aria-label` for social anchors (links like Github) which are placed inside the `footer` element

- it is important to note that we want to add the `title` attribute also. This is because the `title` attribute is intended to provide additional information to screen reader users.

- The `aria-label` attribute is a way more important for providing accessibility information to screen reader users. The `aria-label` attribute is an Accessible Rich Internet Applications (ARIA) attribute that can be used to provide a label for an element. This label is then read aloud by screen readers, providing additional information about the element to the user.

- In general, the `aria-label` & `title` attributes are preferred for providing accessibility information to screen reader users.

- You can consider to assign this issue to me to make the site accessible for screen readers

### Add screenshots

![Screenshot 2023-07-04 at 19-23-23 Free-Hit](https://github.com/JasonDsouza212/free-hit/assets/92252895/f9571886-974d-4aee-a223-b83feec051b8)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 0xabdulkhalid** [comment]
Hey there @JasonDsouza212 👋🏻 , please make sure to assign this issue to me asap to make the work done!

Thank you.

**Comment by Stanzin7** [comment]
Hey is this issue still open. I would love to work on it. Thanks

**Comment by 0xabdulkhalid** [comment]
@Stanzin7, you can create your own for contributing.

This is issue is open but it's already assigned to me.
