### ISSUE TITLE
Add splash screen for filters

### ISSUE THREAD

**Issue by thevinitgupta** [JasonDsouza212/free-hit#12]
On small screens the options are covering the whole screen : 
![Screen Shot 2023-02-22 at 11 37 27](https://user-images.githubusercontent.com/65801700/220537377-f51303ff-0c0c-4955-992d-636ba1d558ac.png)

A better UI would be to have a modal that opens up to select filters.

I would love to work on this.

**Comment by JasonDsouza212** [comment]
Good catch. Yes @thevinitgupta you can work on that

**Comment by thevinitgupta** [comment]
Thanks, I will start working on this.
