### ISSUE TITLE
[Feat]: improve visibility of copyright text to boost accessibility score 💡

### ISSUE THREAD

**Issue by 0xabdulkhalid** [JasonDsouza212/free-hit#1201]
### What feature?

- The feature is about improving the current copyright text color into the color which can be visible for low visioned people.
- It also boosts the accessibility score from Google Pagespeed Insights.
- Providing texts with good contrast color is essential for every website, if we lack to provide the one then it will be severly affects the low visioned people
- I'm here to come up with a solution for this problem, you can consider to assign this issue to me to boost this site's accessibility score.

### Add screenshots

|||
| :---: | :---: |
| Copyright Section | ![Screenshot 2023-07-04 at 19-33-37 Free-Hit](https://github.com/JasonDsouza212/free-hit/assets/92252895/29c0eb43-2f49-4834-a137-16f7aca15a51) |
| Report | ![Screenshot 2023-07-04 at 19-32-30 PageSpeed Insights](https://github.com/JasonDsouza212/free-hit/assets/92252895/5665062a-29ce-4282-af81-a6aae42f05cc) |

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 0xabdulkhalid** [comment]
Hey there @JasonDsouza212 👋🏻 , please make sure to assign this issue to me asap to make the work done!

Thank you.

**Comment by Stanzin7** [comment]
Is this thread still open. I would be happy to contribute.
