### ISSUE TITLE
[Adding Tool]: Sheet+

### ISSUE THREAD

**Issue by Parul1606** [JasonDsouza212/free-hit#1209]
### What tool are you adding and to what category?

We need to add Sheet+ - An AI powered tool for excel and google sheet.
Sheet+ is an AI-powered tool designed to enhance Excel and Google Sheets functionality. It leverages advanced algorithms to automate tasks, provide intelligent suggestions, and analyze data. With features like data cleansing, formula suggestions, and automated insights, Sheet+ streamlines spreadsheet workflows and empowers users to work more efficiently and effectively with their data. We should add this in ai category.

### Add Tool Link

tool link: https://sheetplus.ai/

![image](https://github.com/JasonDsouza212/free-hit/assets/80768852/0e1907e8-4959-4b36-993e-1a3100d4bcfc)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] The tool is free for use

**Comment by JasonDsouza212** [comment]
@Parul1606, you should add all the tools in one PR. Don't create individual PRs for each tool. Instead, create a single PR that adds all the tools and attach all the issues it closes.
