### ISSUE TITLE
[Bug]: About page alignment problem in mobile device

### ISSUE THREAD

**Issue by Nehagaddam2909** [JasonDsouza212/free-hit#1219]
### What happened?

The about components are not properly visible on the mobile device

### Add screenshots

Add screenshots
![free-hit](https://github.com/JasonDsouza212/free-hit/assets/47719476/5039d887-b191-4ca3-8617-5c6ff82f2916)

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JasonDsouza212** [comment]
@Nehagaddam2909 it has been resolved
