### ISSUE TITLE
[style]: Chaning UI of cards 

### ISSUE THREAD

**Issue by M-A-N-I-K** [JasonDsouza212/free-hit#1222]
### What's the style idea?

We need to improve  the ui of cards as it should be more eye pleasing and should give better user experience

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by karantec** [comment]
please assign me this issue i will solve under GSSOC'23

**Comment by M-A-N-I-K** [comment]
@karantec i am already working on it!
