### ISSUE TITLE
[Adding Tool]: 8 tools under 'chatbots' filter

### ISSUE THREAD

**Issue by inkerton** [JasonDsouza212/free-hit#1228]
### What tool are you adding and to what category?

We need to add 8 tools under 'chabots' filter.
<b>Related issue: #947
Related PR: #1204  </b>
List of tools:
<ol>
<li>Odin</li>(free plan)
<li>Freshworks</li>
<li>Cody</li>
<li>MagicForm</li>(free plan)
<li>Ora</li>
<li>Appyie</li>
<li>Mottle</li>(free plan)
<li>Pi</li>
</ol>

### Add Tool Link

Add tool links:
[Cody](https://meetcody.ai/)
[Freshworks](https://www.freshworks.com/)
[Odin](https://getodin.ai/)
[MagicForm](https://www.magicform.ai/)
[Ora](https://ora.ai/)
[Appypie](https://www.appypie.com/)
[Mottle](https://mottle.com/)
[Pi](https://heypi.com/talk)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] The tool is free for use

**Comment by JasonDsouza212** [comment]
@inkerton you can only add only if the tools are free

**Comment by inkerton** [comment]
> @inkerton you can only add only if the tools are free

I will check and update.

**Comment by inkerton** [comment]
> @inkerton you can only add only if the tools are free

Updated the list .

**Comment by inkerton** [comment]
the tools image generation has been added. Please merge pull request #1349 .

**Comment by inkerton** [comment]
I will be adding these tools and filter for these tools also.
