### ISSUE TITLE
[Adding Tool]: CoinGecko API

### ISSUE THREAD

**Issue by SurajPratap10** [JasonDsouza212/free-hit#1229]
### What tool are you adding and to what category?

We need to add `CoinGecko API` by using this users can receive crypto prices, market data, categories, NFT floor prices, exchanges trading volume and trading pairs, metadata, historical data, and other cryptocurrency data in real-time.

### Add Tool Link

**Add tool link**

https://www.coingecko.com/en/api

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] The tool is free for use

**Comment by JasonDsouza212** [comment]
As of now, we are not planning on adding APIs. However, if you decide to add them, they should be placed in a category and should include 8+ tools. Additionally, all the API endpoints should be free of charge.
