### ISSUE TITLE
[Feat]: Create a contributors page

### ISSUE THREAD

**Issue by karthiknadar1204** [JasonDsouza212/free-hit#1235]
### What feature?

I have an idea to create a separate contributors page routed from the navbar using the github API that would map the data of the individual contributors like their image,commits and a button to access the profile of the contributor.

Tha cards would be made to look attractive with alluring hover effects and transition effects.

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by karthiknadar1204** [comment]
I would like to woek on this issue under gssoc'23

**Comment by karthiknadar1204** [comment]
The current page has the images, i propose to add some more additional content to the cards like the name, number of commits and instead of clicking on the image, we can add a view button that will redirect them to the profile.

We could add pagination as well

**Comment by JasonDsouza212** [comment]
@karthiknadar1204, it's already in process, and this is a duplicate issue. For that reason, I'll be closing this issue.
