### ISSUE TITLE
[Feat]: Add Login with Email-Password, Google, and GitHub using Auth0 to Free-Hit Website

### ISSUE THREAD

**Issue by Nishitbaria** [JasonDsouza212/free-hit#1239]
### What feature?

The proposed enhancement involves implementing login functionality with three different options:

1. Email and Password: Users will be able to create an account on Free-Hit using their email address and password combination. This will allow them to securely access their accounts and access personalized features.

2. Google Sign-In: By integrating Google Sign-In through Auth0, users will have the convenience of using their existing Google accounts to log in to Free-Hit. This will streamline the login process and eliminate the need for users to create new credentials.

3. GitHub Sign-In: Adding GitHub Sign-In through Auth0 will provide users with an additional login option. Users who already have GitHub accounts can log in seamlessly, leveraging their existing credentials and GitHub profile.

Benefits and Considerations:
**-Users can see their bookmarked tools and track their progress.**
- Improved User Experience: Offering multiple login options caters to users' preferences and enables them to choose the method that is most convenient for them.
- Streamlined Onboarding: By allowing users to sign in with their Google or GitHub accounts, the onboarding process becomes quicker and more efficient.
- Authentication Security: Auth0 handles authentication securely, reducing the risks associated with managing user credentials and ensuring best practices for account protection.

### Add screenshots

![image](https://github.com/JasonDsouza212/free-hit/assets/85815172/2798ac67-deb7-4ccc-b1c2-0e19d18c7e36)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Nishitbaria** [comment]
@JasonDsouza212 ,Please assign me this issue,I will create pull request asap

**Comment by Nishitbaria** [comment]
i can implement Auth0 which has its own database of users and i can also maintain users in my custom mongo db database ,i will implement it in express.js and mongodb  ,which will help us to also save boookmarked tools for user,you can assign me this issue ,i will implement it accurately.

**Comment by JasonDsouza212** [comment]
@Nishitbaria as of now we are not planning for that, for that reason Ill be closing this issue
