### ISSUE TITLE
Alter the hover colors

### ISSUE THREAD

**Issue by Deva-1903** [JasonDsouza212/free-hit#125]
**The hover color for the terms "GitHub" and "Twitter" needs to be altered.**

![Screenshot (305)](https://user-images.githubusercontent.com/97371915/230815459-f9466c3d-f13b-4125-949b-0f36ed8a273d.png)

**Comment by JasonDsouza212** [comment]
You can start working on it

**Comment by Deva-1903** [comment]
Done, and now it looks prettier because I included the GitHub and twitter icons. Verify the PR @JasonDsouza212
