### ISSUE TITLE
[style]: Improve hover effects on the cards in the about us page

### ISSUE THREAD

**Issue by karthiknadar1204** [JasonDsouza212/free-hit#1250]
### What's the style idea?

Currently on hovering the cards, the cards move up vertically, what do you think of scaling it, it would look much more visually appealing

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by karthiknadar1204** [comment]
I would like to work on this issue under gssoc'23

**Comment by JasonDsouza212** [comment]
@karthiknadar1204, you have already been assigned 1 issue. Therefore, this issue will be assigned to @karantec

**Comment by karthiknadar1204** [comment]
@JasonDsouza212 I am done with the assigned issue including the asked changes,please review that and then assign it to me.

I opened it because I was done with the assigned task
