### ISSUE TITLE
[Adding Tool]: Simplilearn

### ISSUE THREAD

**Issue by soubhik-111** [JasonDsouza212/free-hit#1267]
### What tool are you adding and to what category?

We need to add Simplilearn

### Add Tool Link

[Simplilearn](https://www.simplilearn.com/)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] The tool is free for use

**Comment by 07-Atharv** [comment]
I will take up these

**Comment by soubhik-111** [comment]
Hello @VenomFate-619 ,
I have raised the issue and I want to work on it therefore I have raised it and raised PR too so, kindly merge it.
