### ISSUE TITLE
Suggest: Migrate to NextJs.

### ISSUE THREAD

**Issue by dhawal-793** [JasonDsouza212/free-hit#128]
As the project is getting bigger I think now we should move the codebase to Next Js.

Benefits of using Next Js :

-  Better SEO.
-  Static-Site-Generation.
- Server-Side-Rendering
-  Also suggested by React Dev team.

**Comment by JasonDsouza212** [comment]
Currently, there isn't much need to migrate it to Next.js. We are thinking of changing the UI first, and after that, we can discuss the possibility of migration.

**Comment by JasonDsouza212** [comment]
We are thinking of changing the Free-Hit Design, and during that time, we can migrate to Next.js

**Comment by JasonDsouza212** [comment]
@dhawal-793 Do you want to work on it

**Comment by dhawal-793** [comment]
Yeah sure,

**Comment by dhawal-793** [comment]
Before starting on nextjs If possible we should move to Tailwind CSS, cause it will be more simpler file structure for nextjs.

**Comment by dhawal-793** [comment]
I can transfer all the code to Tailwind with the current UI If you want.

**Comment by JasonDsouza212** [comment]
@dhawal-793 go ahead . You and @priyankarpal  can do it. But he is kind of stuck in his exams

**Comment by dhawal-793** [comment]
Ok I will do it, will take some time, is it ok

**Comment by adarsh-k27** [comment]
how can i solve issues im new to Open source project ?

**Comment by JasonDsouza212** [comment]
@adarsh-k27 you can contact me through Discord
