### ISSUE TITLE
[Adding Tool]: Machine learning and AI related courses

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [JasonDsouza212/free-hit#1282]
### What tool are you adding and to what category?

We need to add courses related to Machine learning, artificial intelligence, deep learning, stastical learning, etc.

### Add Tool Link

Add tool link

- https://www.coursera.org/learn/unsupervised-learning-recommenders-reinforcement-learning/home/week/1
- https://www.coursera.org/learn/foundations-of-data-science/home/week/2

and so many which are premium but are available free in case, one will the financial aid application and recommended by many experts.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] The tool is free for use

**Comment by Avdhesh-Varshney** [comment]
@JasonDsouza212 @VenomFate-619 please assign this task

**Comment by JasonDsouza212** [comment]
@Avdhesh-Varshney, I believe we should create a separate page for this type of content. I mean, these items aren't tools; they can be considered learning materials. So, let's create a dedicated page for them and categorize them according to the courses.

**Comment by Avdhesh-Varshney** [comment]
> @Avdhesh-Varshney, I believe we should create a separate page for this type of content. I mean, these items aren't tools; they can be considered learning materials. So, let's create a dedicated page for them and categorize them according to the courses.

@JasonDsouza212 @VenomFate-619  Sir, Just like Bookmarks and about pages like that ?
We can create another page for these courses with the title courses or can be categorised as the courses like that ?

**Comment by Avdhesh-Varshney** [comment]
@JasonDsouza212 @VenomFate-619 sir, please tell me about it. So that I can raise the pr
