### ISSUE TITLE
[style]: Redesign the text presentation style in about us page 

### ISSUE THREAD

**Issue by Srishtikumari2002** [JasonDsouza212/free-hit#1286]
### What's the style idea?

We need to improve  the style of text presented in about us page. I mean the text size is too big almost similar to size of logo, that is not good in the sense  of user experience. Hence I want to add some proper style so the size of text automatically gets adjust itself according to screen size. Also to make it more responsive I want to add hovering effect on text as well as on images. The hovering effect is there but only in dark mode.

Because of same sizes in every size of screen it is taking a lot of space, and it is not for user experience as for reading this short content also they need to scroll up, so it will be tiring work.

### Add screenshots

![image](https://github.com/JasonDsouza212/free-hit/assets/77767357/bf84b971-94a2-4dd2-bb12-5dcabcc15e4e)
![image](https://github.com/JasonDsouza212/free-hit/assets/77767357/a9cc45bb-71f5-4eca-902f-16f7b6ac4da4)
![image](https://github.com/JasonDsouza212/free-hit/assets/77767357/aca61c20-1c94-4f9f-b1a3-18b99cad0454)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bhanu17crypto** [comment]
hello
could you assign it to me

**Comment by JasonDsouza212** [comment]
@Srishtikumari2002 as you have been assigned with other issue, this issue will be assigned to @bhanu17crypto

**Comment by Srishtikumari2002** [comment]
Hey, if this issue is still not completed, so would you allow me to work on it?
