### ISSUE TITLE
Refactor BackToTopButton component for improved readability and maintainability⚡

### ISSUE THREAD

**Issue by Nishitbaria** [JasonDsouza212/free-hit#1290]
### **Description:**

The BackToTopButton component in the codebase requires refactoring to enhance its readability and maintainability. The following improvements are suggested:

1. Combine import statements: The import statements for `useContext` and `useState` can be combined on a single line for better readability.

2. Variable name consistency: The variable `btnVisiblity` should be renamed to `btnVisibility` for consistency and clarity.

3. Event handler name clarification: Rename the event handler `toggleVisiblity` to `toggleVisibility` to improve naming consistency and clarity.

4. Define CSS classes outside JSX: Move the calculation of CSS classes (`buttonClass`, `transitionClass`, and `topClass`) outside the JSX to improve readability and maintainability.

5. Indentation and formatting: Apply consistent indentation and spacing throughout the code to enhance readability.

<hr>

**Comment by Nishitbaria** [comment]
Hey @JasonDsouza212  Please Assign me to this issue ⚡

**Comment by JasonDsouza212** [comment]
@Nishitbaria are you working under Gssoc23

**Comment by Nishitbaria** [comment]
> @Nishitbaria are you working under Gssoc23

Yes I am a  Contributor Under Gssoc23
