### ISSUE TITLE
[Feat]: ADD WORKFLOW SCRIPT TO PREVENT MULTIPLE ISSUES 🔐

### ISSUE THREAD

**Issue by 0xabdulkhalid** [JasonDsouza212/free-hit#1293]
### What feature?

- We want to add a workflow script regarding closing the issues.
-  This script will look into the contributor created issue and checks if he already created an issue, If an issue exists the new issue will be closed.
-  According the GSSoC Contributing guidelines, A contributor must want to finish one issue before creating another issue.
- But in this repository the contributors are spamming multiple issues, This is strictly against the contributing guidelines.

### Advantages
- Improved Organization: The script helps maintain a more organized issue tracking system. It prevents contributors from opening multiple issues simultaneously, ensuring that each issue is focused on and resolved before moving on to the next one. This promotes better visibility and prioritization of issues.

- Reduced Noise: By preventing multiple issues from the same contributor, the script reduces the noise and clutter in the issue tracker. It encourages contributors to consolidate their feedback, bug reports, or feature requests into a single, well-defined issue, making it easier for maintainers to track and address them.

- Enhanced Collaboration: With a more streamlined issue tracker, it becomes easier for maintainers and contributors to collaborate effectively. They can concentrate their efforts on resolving one issue at a time, leading to more efficient communication and problem-solving.

- Time and Resource Optimization: The script helps optimize the allocation of time and resources by discouraging contributors from spreading their efforts too thin across multiple issues. Instead, they can focus on one issue, invest their energy in understanding and resolving it, and ensure quality contributions.

- Reduced Duplication: By checking for open issues by the same contributor before opening a new one, the script reduces the likelihood of duplicating issues. This saves time for both contributors and maintainers, as they don't have to address duplicate or overlapping issues separately.

- Accountability: By enforcing a rule against multiple open issues, the script promotes accountability among contributors. It encourages them to take ownership of their previously opened issues, follow up on them, and complete the necessary steps for resolution before opening new ones.

- Efficient Issue Resolution: By addressing one issue at a time, the script promotes a more systematic and focused approach to issue resolution. This can lead to faster turnaround times and higher-quality solutions, benefiting both the contributors and the project as a whole.

- Overall, the script helps create a more organized, efficient, and collaborative environment within the open-source repository. It encourages contributors to be more thoughtful in their issue tracking and promotes a smoother workflow for issue resolution.

### Add screenshots

![image](https://github.com/JasonDsouza212/free-hit/assets/92252895/e60095be-1f97-4b16-8069-ec0e7195a015)

<div align=center>

**You can able to see contributor who spammed multiple issues, this is simply because of not following guidelines**
**We can automate the process to give chance to all contributors, will make the game fair to all the ones**

</div>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 0xabdulkhalid** [comment]
Hey there @JasonDsouza212, @VenomFate-619 👋🏻

Please make sure to assign this issue to me as soon possible so that i can make the work done!

Thank you.

**Comment by JasonDsouza212** [comment]
@VenomFate-619, the duplicate assignments are related to adding tools and do not receive points, so I don't think that's a problem.

**Comment by 0xabdulkhalid** [comment]
You're right @JasonDsouza212, but you can see that some of the contributors are just opening more than 5 at a time for adding new tools eventhough they don't get level labels for that.

The points are no matter here, a contributor must want to work on only one issue at a time. Here they are all creating many number of issues.

We must need to add this workflow to prevent unwanted noise of creating multiple issues.

**Comment by soubhik-111** [comment]
@JasonDsouza212 
@VenomFate-619 
@0xabdulkhalid 

Hello Everyone,
I have one question is it bad to add more tools?
Is it bad to add more tools so users will get more options?

What's the context of using the word "Unfair"?
If one adds duplicate tools, then no doubt it is wrong but for different tools how is it wrong?
Kindly respect everyone's issue

**Comment by 0xabdulkhalid** [comment]
Hey there @soubhik-111,

Adding tools is not bad, but creating multiple issues at a time is bad.
It's strictly against open source guidelines, a contributor must want to work on a single issue if he's assigned to it.
If the issue is fixed/closed then he/she can open a new issue to contribute.

Hope you understood!

**Comment by 0xabdulkhalid** [comment]
For example take a look at your own issues, @soubhik-111.

![image](https://github.com/JasonDsouza212/free-hit/assets/92252895/76a36e13-b74e-4040-9fc5-2ba4bf2dd9fe)

Currently 12 them are open, you got assigned for 10 of them.

Remember **"Every contributor must want to work on one issue at a time"**.
