### ISSUE TITLE
Tool tip

### ISSUE THREAD

**Issue by JasonDsouza212** [JasonDsouza212/free-hit#13]
## Implement a tooltip 
- When we hover over a card, it should display the usage of the corresponding tool.
 - To achieve this, we can provide a tooltip
 - Because in the tools section, it is difficult to know the functionality of each tool
 - Users may find it challenging to locate the tools they need since the tool descriptions do not provide sufficient information about their functionality.

**Comment by scorcism** [comment]
For this, i guess we have to add one more field in our db to store a short into about the website.

**Comment by JasonDsouza212** [comment]
Yes, I just added that. We need the description to be entered. If you want, you can contribute to it.

**Comment by scorcism** [comment]
okay sure, but in this month i m having my exams so may be i wont able to complete in this month.
