### ISSUE TITLE
Feature request: Add a search bar for both categories and tools

### ISSUE THREAD

**Issue by suzy-g38** [JasonDsouza212/free-hit#130]
**Is your feature request related to a problem? Please describe.**

Finding a particular tool from the "all" tools category is a bit tedious as there are quite a number of tools there. Plus, maybe it's early because there not be many tools in some categories but soon there will be more tools and categories. Then searching can save the additional time to manually find it out. 

**Describe the solution you'd like**

So my suggestion is to add a search bar where we can search for both the tools and category.
Thank you.

**Comment by JasonDsouza212** [comment]
@suzy-g38   we already have a search bar, but we need to implement the functionality to search by category

**Comment by Deva-1903** [comment]
I have worked on this issue @JasonDsouza212. In filteredProducts function added a new line  "**product.category.match(regex)**" and Changed the placeholder in the header as  **placeholder=" Search for a tool or category..."**. Can I open a PR?
