### ISSUE TITLE
[Adding Tool]:  sflix

### ISSUE THREAD

**Issue by Parul1606** [JasonDsouza212/free-hit#1310]
### What tool are you adding and to what category?

We need to add sflix movie streaming website. It has almost old Bollywood and Hollywood movies too which we can watch for free. We should add this movies category.

### Add Tool Link

Add tool link: - https://sflix.to/home

![image](https://github.com/JasonDsouza212/free-hit/assets/80768852/f66a5864-5ba7-48e5-bf62-1f90404a6066)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] The tool is free for use

**Comment by vats147** [comment]
Can you recheck url becuase it is not woeking on my device.

**Comment by Parul1606** [comment]
Yeah its working @vats147

**Comment by vats147** [comment]
It will not work on my computer but i can paste your url in code
