### ISSUE TITLE
search icon is not align properly

### ISSUE THREAD

**Issue by biplavmz** [JasonDsouza212/free-hit#1319]
### What happened?

I found a BUG 🐞
search icon is not align properly
Can you please assign it to me under GSSOC'23?

### Add screenshots

<img width="264" alt="image" src="https://github.com/JasonDsouza212/free-hit/assets/68702055/5cc78386-cea5-45f9-baa1-78fe3f2a0720">

### What browsers are you seeing the problem on?

Microsoft Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JasonDsouza212** [comment]
@biplavmz someone is already working on it
