### ISSUE TITLE
[style]: want to change the card Design 

### ISSUE THREAD

**Issue by biplavmz** [JasonDsouza212/free-hit#1321]
### What's the style idea?

We need to improve  
The card Design 

### Add screenshots

Add screenshots
<img width="574" alt="image" src="https://github.com/JasonDsouza212/free-hit/assets/68702055/bbf1ecd6-f4c3-40bb-b04d-d0c56d8f3830">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JasonDsouza212** [comment]
@biplavmz it should align with the apps theme

**Comment by biplavmz** [comment]
ok @JasonDsouza212  can you please assign it to me
