### ISSUE TITLE
[style]: Add hover effect

### ISSUE THREAD

**Issue by dheeraj1129** [JasonDsouza212/free-hit#1325]
### What's the style idea?

Add some hover effects on the [learn more and star the repo] buttons.

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Sayak-Bhunia** [comment]
Hey, I can add some hoover effects to the star the repo button. Please assign me this issue.

**Comment by Amanraj0149** [comment]
I would be delighted to take on this task and contribute to the project by implementing the hover effects for these buttons. Please let me know if this aligns with your vision for the project, and if so, I would appreciate your guidance on how to proceed , pls assign me this issue.

**Comment by riteshkv57** [comment]
I have some latest tools to add the hover feature for star the repo buttons, and i would be highly delighted if you assign me this issue.

**Comment by JasonDsouza212** [comment]
@dheeraj1129 as you have been assigned to another issue this issue will be assigned to @Sayak-Bhunia

**Comment by dheeraj1129** [comment]
@JasonDsouza212 you can assign this to me I guess!!! 
If there are other issues you can assign that task to me also
