### ISSUE TITLE
[Adding Tool]: Soundraw.io

### ISSUE THREAD

**Issue by Parul1606** [JasonDsouza212/free-hit#1328]
### What tool are you adding and to what category?

We need to add Soundraw.io to the free-hit. This ai website generates musics for free. We should add this in ai category.

### Add Tool Link

Add tool link: https://soundraw.io/

![image](https://github.com/JasonDsouza212/free-hit/assets/80768852/c093f4e2-a4d8-4646-bfd1-eab536e45b7f)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] The tool is free for use

**Comment by soubhik-111** [comment]
I want to take up this
