### ISSUE TITLE
[Docs]: changes to docs

### ISSUE THREAD

**Issue by PurviSaini** [JasonDsouza212/free-hit#1339]
### Add screenshots

Add screenshots
# 1. CONTRIBUTING.md
![Screenshot (113)](https://github.com/JasonDsouza212/free-hit/assets/101940722/6fe52485-6237-4156-8005-0e585a43e297)
# 2. README.md
![Screenshot (112)](https://github.com/JasonDsouza212/free-hit/assets/101940722/a391fe21-9661-4e3f-9238-1c84eba14e3f)
# 3. CODE_OF_CONDUCT.md
![Screenshot (111)](https://github.com/JasonDsouza212/free-hit/assets/101940722/058ecf5f-7716-4da6-8b23-874b623147d7)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Sayak-Bhunia** [comment]
I can do this documentation according to your needs. Please assign me this issue.

**Comment by PurviSaini** [comment]
In CODE_OF_CONDUCT.md( Screenshot 3 )
What will be the missing word/sentence to be inserted?

**Comment by PurviSaini** [comment]
If I could know what information to fill in there then I would go for making a PR

**Comment by PurviSaini** [comment]
I guess [jasondsouza212@gmail.com](mailto:jasondsouza212@gmail.com) this is missing in screenshot3, This email id I gathered from your github readme, so should I add it?
