### ISSUE TITLE
Suggest : Use react-icons or Custom Icons

### ISSUE THREAD

**Issue by dhawal-793** [JasonDsouza212/free-hit#134]
Use react-icons npm package or use custom icon components instead of fortasesome.

**Comment by JasonDsouza212** [comment]
Is there any particular reason or benefit for using it?

**Comment by priyankarpal** [comment]
> Is there any particular reason or benefit for using it?

React-icons is a popular npm package that provides a large collection of icons that can be easily imported and used in React projects.

**Comment by dhawal-793** [comment]
React Icons is best for projects where different icons are required and react-icons is a package containing icons of different types, designs, etc.

But as this project doesn't require a lot of icons, it is better to use custom Icon Components to reduce the load of dependencies.
As for only 10 to 12 icons complete dependency is required.

If you agree I can make a custom icon Component for the required Icons.

**Comment by JasonDsouza212** [comment]
Do you want to work on this @dhawal-793

**Comment by dhawal-793** [comment]
Created a pull request regarding this #148 .
