### ISSUE TITLE
[Adding Tool]: Fullstack.cafe for preparing for tech interviews :)

### ISSUE THREAD

**Issue by Ujjwal-soni98** [JasonDsouza212/free-hit#1346]
### What tool are you adding and to what category?

We need to add Fullstack.cafe for preparation for tech interviews.
i want to add this resource assign it to me under GSSoC 2023!!! 

### Add Tool Link

Add tool link [fullstack.cafe](https://www.fullstack.cafe/). Most of the questions are provided free and can be downloaded via pdf.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] The tool is free for use

**Comment by JasonDsouza212** [comment]
@Ujjwal-soni98 , is this free

**Comment by Ujjwal-soni98** [comment]
many questions are free to view over many tech stacks and save them as pdf. but some of the questions are paid also. so can't say that it is completely free.

**Comment by Ujjwal-soni98** [comment]
@JasonDsouza212  please add GSSoC23 tag in this.

**Comment by Ujjwal-soni98** [comment]
GSSoC program is going to end so please add it sooner, i am having my exams right now so cannot look to contribute to any new issue  :)
