### ISSUE TITLE
[Adding Tool]: Appwrite Backend server for Web,Mobile and Flutter Applications

### ISSUE THREAD

**Issue by HarshSharma0801** [JasonDsouza212/free-hit#1347]
### What tool are you adding and to what category?

We need to add Appwrite Backend server tool used for Database , Authentication , Storage and many more 

### Add Tool Link

https://appwrite.io/

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] The tool is free for use

**Comment by JasonDsouza212** [comment]
@HarshSharma0801 but I dont think its free

**Comment by HarshSharma0801** [comment]
@JasonDsouza212
