### ISSUE TITLE
[style]: Enhancement in Hover effect for the buttons.

### ISSUE THREAD

**Issue by Keyuri-19** [JasonDsouza212/free-hit#1356]
### What's the style idea?

We need to improve  the styling effect for the buttons( Bookmark button and visit button ). So want to improve 
the hovering effect for the bookmark and visit buttons to enhance the look of the website.

### Add screenshots

![image](https://github.com/JasonDsouza212/free-hit/assets/115471178/8a7d6381-b89f-424e-8097-150db343aa97)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Keyuri-19** [comment]
@JasonDsouza212 Please assign these issue to me

**Comment by Keyuri-19** [comment]
@VenomFate-619 @JasonDsouza212 Please assign these issue to me

**Comment by VenomFate-619** [comment]
@Keyuri-19 propose your change.
post some example work

**Comment by VenomFate-619** [comment]
@Keyuri-19 give updates.
