### ISSUE TITLE
[Feat]: Migrate to Next.js

### ISSUE THREAD

**Issue by s2sharpit** [JasonDsouza212/free-hit#1360]
### What feature?

Currently, the codebase is in react...I would like to migrate it to the next.js

I would like to work on it under gssoc23

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JasonDsouza212** [comment]
@s2sharpit, the project has been selected for GSSoC23, and there are frequent changes happening in the projects. We can consider migrating to Next.js once GSSoC23 is over.

**Comment by s2sharpit** [comment]
> @s2sharpit, the project has been selected for GSSoC23, and there are frequent changes happening in the projects. We can consider migrating to Next.js once GSSoC23 is over.

Hey @JasonDsouza212,
Actually, I was thinking to work on it under GSSoC23.
