### ISSUE TITLE
[Feat]: Improve bookmark button's behaviour 

### ISSUE THREAD

**Issue by kirtiraj22** [JasonDsouza212/free-hit#1364]
### Description : 
Currently, the website features a bookmark button that allows users to save links. However, upon clicking the bookmark button, there is **no visual indication or feedback** to confirm that the link has been successfully bookmarked. 
So I want to add a toast notification to provide users with immediate feedback when they click the bookmark button.

### Current Behavior:
- There is no notification or any form of feedback/acknowledgment to inform the user that the link has been bookmarked.

### Desired Behavior:
- Upon clicking the bookmark button, trigger a toast notification to provide visual feedback to the user.
- The toast notification will convey a clear message indicating that the link has been bookmarked successfully.
- The toast notification will appear briefly and fade out naturally, ensuring a smooth and non-intrusive user experience.

This feature will enhance the user experience.
 

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by VenomFate-619** [comment]
great find.

**Comment by VenomFate-619** [comment]
on clicking the bookmark the button on a tool card changes to Delete 
![image](https://github.com/JasonDsouza212/free-hit/assets/67755128/8c527799-c6af-4a9d-827d-a8b5c6dd1d1f)

**Comment by kirtiraj22** [comment]
> on clicking the bookmark the button on a tool card changes to Delete ![image](https://user-images.githubusercontent.com/67755128/253476129-8c527799-c6af-4a9d-827d-a8b5c6dd1d1f.png)

true! 
but I thought that if we acknowledge the users with a toast notification, then it will surely improve the user experience!

**Comment by PratikMbade** [comment]
i am working on it.

**Comment by JasonDsouza212** [comment]
@PratikMbade  I don't think it's assigned to you

**Comment by PratikMbade** [comment]
@JasonDsouza212  yes it doesn't assign me , but i am tryping to add this feature. i know i can add this feature.

**Comment by PratikMbade** [comment]
@JasonDsouza212  I have add this feature. here some i have some screenshots

Screenshots:
![image](https://github.com/JasonDsouza212/free-hit/assets/110896142/0157c08e-fb6c-4b67-a6c4-0545b2c15a52)

![image](https://github.com/JasonDsouza212/free-hit/assets/110896142/82a69dd8-389f-41af-9fdf-f425cb6ac804)

**Comment by kirtiraj22** [comment]
Hey @JasonDsouza212, 
I appreciate that @PratikMbade is willing to work on the issue. However, since I was the one who initially raised the issue and I'm interested in contributing to this feature, I would like to work on it if you'd like this enhancement for your website. Let me know if I can proceed with addressing this issue.

Thank you!

**Comment by JasonDsouza212** [comment]
@PratikMbade sorry as @kirtiraj22 raised the issue , he will be assigned with the issue, if he fails you will be assigned next

**Comment by JasonDsouza212** [comment]
@PratikMbade are you up for working on this
