### ISSUE TITLE
[Adding Tool]: Dribble

### ISSUE THREAD

**Issue by blindaks** [JasonDsouza212/free-hit#1370]
### What tool are you adding and to what category?

We need to add Dribble to UI Design tools.

### Add Tool Link

[Add tool link](https://dribbble.com/following)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] The tool is free for use

![Screenshot (55)](https://github.com/JasonDsouza212/free-hit/assets/128223364/acc6db39-acb3-455f-a754-5039a1f84654)

**Comment by blindaks** [comment]
@JasonDsouza212 Please assign this issue to me under GSSOC'23.

**Comment by JasonDsouza212** [comment]
@blindaks is it free
