### ISSUE TITLE
[Adding Tool]: MasterClass

### ISSUE THREAD

**Issue by blindaks** [JasonDsouza212/free-hit#1371]
### What tool are you adding and to what category?

We need to add MasterClass to Course Platforms.

### Add Tool Link

https://www.masterclass.com/?irclickid=XBs0Kj2UZxyPUd8XKpRHgWgzUkFzAb18Z2jiQs0&utm_source=impact&utm_medium=affiliate&utm_campaign=&utm_content=1317543&utm_term=1359419&irgwc=1
![Screenshot (56)](https://github.com/JasonDsouza212/free-hit/assets/128223364/26529718-efed-4c34-85b7-eee5f5bc20c1)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] The tool is free for use

**Comment by blindaks** [comment]
@JasonDsouza212 Please assign this issue to me under GSSOC'23.

**Comment by JasonDsouza212** [comment]
@blindaks is it free
