### ISSUE TITLE
[Docs]: UPDATE README

### ISSUE THREAD

**Issue by Shikhar9425** [JasonDsouza212/free-hit#1374]
### what's wrong in the documentation?

want to add more features .
wants to add some more content to the description so that it will be more easily understandable.
align/modify some of the headings .
wants to make an impressive readme

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Shikhar9425** [comment]
@JasonDsouza212 please assign me this issue

**Comment by Glorycs29** [comment]
@JasonDsouza212 Could you please assign it to me?
