### ISSUE TITLE
Navbar 

### ISSUE THREAD

**Issue by yuvraj6446** [JasonDsouza212/free-hit#1383]
### What's the style idea?

Hey, For desktop devices we can keep navbar at top between search and logo and same as now for android devices or small screen.
I want to work on this

### Add screenshots

Add screenshots

### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

**Comment by yuvraj6446** [comment]
please assign me this task i want to contribute

**Comment by JasonDsouza212** [comment]
@yuvraj6446 I didnt get your idea

**Comment by yuvraj6446** [comment]
I have attached the image of nav bar idea i was talking about
