### ISSUE TITLE
[style]: Position of light/dark mode button

### ISSUE THREAD

**Issue by PratikMbade** [JasonDsouza212/free-hit#1384]
### What's the style idea?

We need to change light/dark mode  button position , it is not noticeable for the users . user thought there no light/dark mode option. light/dark mode should be located in the navbar so user can easily notice it. i want to work on this issue. 

### Add screenshots

Screenshot
![image](https://github.com/JasonDsouza212/free-hit/assets/110896142/aed218d4-f2b3-4ef2-bf5c-b7b8acfe6f43)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JasonDsouza212** [comment]
@PratikMbade where are you planning to place it

**Comment by PratikMbade** [comment]
@JasonDsouza212 In the Navbar section , so it can be noticeable

**Comment by PratikMbade** [comment]
@JasonDsouza212 can start work on it.

**Comment by PratikMbade** [comment]
@JasonDsouza212  assign me this issue , i want to work on it.

**Comment by vatsalsinghkv** [comment]
@PratikMbade Hey, are you still working on this issue?
