### ISSUE TITLE
[Bug]: Category not opening when on bookmark page

### ISSUE THREAD

**Issue by anshumanjaiswal** [JasonDsouza212/free-hit#1390]
### What happened?

When the user is on bookmark page and try to select any category then it's not opening.

### Add screenshots

Add screenshots

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by anshumanjaiswal** [comment]
Hi @JasonDsouza212 , please assign this task to me! Thanks!

**Comment by JasonDsouza212** [comment]
@anshumanjaiswal its filtering based on the bookmarks
