### ISSUE TITLE
Add more websites

### ISSUE THREAD

**Issue by scorcism** [JasonDsouza212/free-hit#14]
Hey @JasonDsouza212,
There are other various other websites list with me related to tech stuffs,
I was thinking to combine all that with this one

- ML related
- Hacking related
- Competitive related
- Freelancing
- many general stuffs

**Comment by scorcism** [comment]
I'm willing to contribute on this.

**Comment by JasonDsouza212** [comment]
Ya go ahead and do it

**Comment by scorcism** [comment]
Thank you, I will start working on it.

**Comment by scorcism** [comment]
some of the websites have text insted of logo, so what should add on that place ?

**Comment by JasonDsouza212** [comment]
You can add logos to your website that are somewhat similar in design .

**Comment by scorcism** [comment]
okay thanks

**Comment by priyankarpal** [comment]
is it still open?
