### ISSUE TITLE
[Feat]: Enhancing Lighthouse Score for Improved Website Performance

### ISSUE THREAD

**Issue by Avinash905** [JasonDsouza212/free-hit#1405]
### What feature?

Currently, our website's Lighthouse score falls short of the desired standards, which can affect its accessibility, speed, and overall usability. 
This issue aims to address the existing performance gaps and enhance the website's Lighthouse score to provide a smoother and more engaging experience for our visitors.

### Add screenshots

![Screenshot (619)](https://github.com/JasonDsouza212/free-hit/assets/56786344/f80ed8ae-006d-41e3-933a-54f494b28d30)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Avinash905** [comment]
Please assign me this issue so that I can work on this issue under **GSSOC'23**.

**Comment by VenomFate-619** [comment]
did you run this test on an incognito window or not?

**Comment by Avinash905** [comment]
> did you run this test on an incognito window or not?

No I did not run it on incognito

**Comment by VenomFate-619** [comment]
did you run this test on an incognito window or not?

**Comment by VenomFate-619** [comment]
did you run this test on an incognito window or not?
