### ISSUE TITLE
[Adding Tool]: Deploying websites

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [JasonDsouza212/free-hit#1409]
### What tool are you adding and to what category?

We need to add deploying websites which can deploy the projects of the web developer.

### Add Tool Link

Add tool link

Heroku
Vercel
BlueHost
DreamHost, etc.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] The tool is free for use

**Comment by Avdhesh-Varshney** [comment]
@JasonDsouza212 @VenomFate-619 sir, please assign this task to me

**Comment by VenomFate-619** [comment]
do wait a little
