### ISSUE TITLE
[Adding Tool]: wordpress website

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [JasonDsouza212/free-hit#1410]
### What tool are you adding and to what category?

We need to add WordPress Website where user can make website without coding just do editing and host that website

### Add Tool Link

Add tool link

[WordPress](https://wordpress.com/)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] The tool is free for use

**Comment by Avdhesh-Varshney** [comment]
@JasonDsouza212 @VenomFate-619 sir, please assign this task to me

**Comment by Piyush-Gambhir** [comment]
I would like to work on this issue. Kindly assign it to me under GSSOC'23.
