### ISSUE TITLE
[Adding Tool]: Add broken-link-checker

### ISSUE THREAD

**Issue by lakshmishreea122003** [JasonDsouza212/free-hit#1415]
### What tool are you adding and to what category?

We need to add
Add broken-link-checker
It helps check your site for broken inbound and outbound links in seconds.

### Add Tool Link

Add tool link
https://ahrefs.com/broken-link-checker

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] The tool is free for use

**Comment by lakshmishreea122003** [comment]
Do assign it to me

**Comment by Piyush-Gambhir** [comment]
I would like to work on this issue. Kindly assign it to me under GSSOC'23.

**Comment by lakshmishreea122003** [comment]
raised this issue to work on it myself. I am just waiting for it to be assigned to me by the admins.

**Comment by lakshmishreea122003** [comment]
No, it is not stale. I have come up with a PR that is yet to be merged
