### ISSUE TITLE
[Adding Tool]: Add amazon-keyword-tool

### ISSUE THREAD

**Issue by lakshmishreea122003** [JasonDsouza212/free-hit#1416]
### What tool are you adding and to what category?

We need to add
Add amazon-keyword-tool.
It helps find what people are searching for on Amazon, and align your product listings with those terms.

### Add Tool Link

Add tool link
https://ahrefs.com/amazon-keyword-tool

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] The tool is free for use

**Comment by Piyush-Gambhir** [comment]
I would like to work on this issue. Kindly assign it to me under GSSOC'23.

**Comment by lakshmishreea122003** [comment]
raised this issue to work on it myself. I am just waiting for it to be assigned to me by the admins.

**Comment by lakshmishreea122003** [comment]
No, it is not stale. I have come up with a PR that is yet to be merged

**Comment by lakshmishreea122003** [comment]
No, it is not stale. I have come up with a PR that is yet to be merged

**Comment by lakshmishreea122003** [comment]
I raised this issue as a gssoc23 contributor
