### ISSUE TITLE
[Adding Tool]: Add youtube-keyword-tool

### ISSUE THREAD

**Issue by lakshmishreea122003** [JasonDsouza212/free-hit#1418]
### What tool are you adding and to what category?

We need to add
Add youtube-keyword-tool
it helps Get more views on YouTube by researching keywords people are searching for.

### Add Tool Link

Add tool link
https://ahrefs.com/youtube-keyword-tool

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] The tool is free for use

**Comment by Piyush-Gambhir** [comment]
I would like to work on this issue. Kindly assign it to me under GSSOC'23.

**Comment by lakshmishreea122003** [comment]
I raised this issue to work on it myself. I am just waiting for it to be assigned to me by the admins.

**Comment by lakshmishreea122003** [comment]
No, it is not stale. I have come up with a PR that is yet to be merged.
