### ISSUE TITLE
[Feat]: Enlisting all the contributors

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [JasonDsouza212/free-hit#1428]
### What feature?

I have an idea 

- In about section, enlist all the contributors.
- Adding the carousel effect into the cards.
- Enlisting contributors in decreasing order of the contributions, they done.

### Add screenshots

Add screenshots

![image](https://github.com/JasonDsouza212/free-hit/assets/114330097/9622a20f-2505-4241-a811-a3f28c3742a1)

<br>

or may be at the bottom of that section

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Avdhesh-Varshney** [comment]
@JasonDsouza212 @VenomFate-619 sir, please assign this task to me

**Comment by VenomFate-619** [comment]
https://free-hit.vercel.app/community
we have this.
