### ISSUE TITLE
[Adding Tool]: 

### ISSUE THREAD

**Issue by deepiikaa24** [JasonDsouza212/free-hit#1430]
### What tool are you adding and to what category?

We need to add a tool that can be helpful for startup enthusiasts who want to have a better understanding of Startup concepts.

### Add Tool Link

Add tool link- https://ajuniorvc.com/

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] The tool is free for use

**Comment by Haaziq386** [comment]
is this issue solved?
