### ISSUE TITLE
[Feat]: Add "Cheat sheets", "Hosting", "Blogs", "APIs", "Communities" , "Books", "Libraries", "Validators" Categories likewise Previous Ones

### ISSUE THREAD

**Issue by NarendraKoya999** [JasonDsouza212/free-hit#1432]
### What feature?

I have an idea  about adding Other Multiple Categories likewise Previous Ones.
- I want to add **`"Cheat sheets", "Hosting", "Blogs", "APIs", "Communities" , "Books", "Libraries", "Validator" Categories` in Categories Feature**

### Add screenshots

Add screenshots
### I want to add the above requested Categories in Below Categories List
![freehit-28](https://github.com/JasonDsouza212/free-hit/assets/84512164/cf3e97b0-a7eb-4c5b-8ff2-4638034bf790)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JasonDsouza212** [comment]
@NarendraKoya999, I am planning on removing some unnecessary tools that were added. After completing the GSSOC23, I want to concentrate solely on unique and free tools in the database. A cheat sheet is a resource; if you know of a website that provides multiple cheat sheets in one place, we can consider it. Similarly, all the blog applications are free, so I don't think there is much need for them. Communities can't be considered as tools. However, applications that provide free books can be considered as tools, and websites offering free hosting can also be considered as tools.

**Comment by NarendraKoya999** [comment]
Ok. @JasonDsouza212 . Which Options I want to add In Above Categories?. Please give me Clarity on that? .After that, I can Proceed to Make Changes in DB?
