### ISSUE TITLE
[Feat]: JSON CHECKER GITHUB WORKFLOW 🚀

### ISSUE THREAD

**Issue by 0xabdulkhalid** [JasonDsouza212/free-hit#1443]
### What feature?

- I would like to add a new workflow "JSON check" to include a step that checks whether the JSON syntax is valid or not. This will help ensure that the JSON files in the repository are correctly formatted and avoid potential issues caused by invalid JSON.

- By adding this workflow, you can ensure that the JSON files in the repository are not only checked for syntax errors but also validated against specific criteria, promoting better quality and correctness of the JSON data.

- Please consider implementing this enhancement to enhance the functionality of the existing "JSON check" workflow.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 0xabdulkhalid** [comment]
Hey there @JasonDsouza212, @VenomFate-619 👋🏻

Please make sure to assign this issue to me as soon possible so that i can make the work done!

Thank you!

**Comment by VenomFate-619** [comment]
Could you let me know which validation you'll add?

**Comment by JasonDsouza212** [comment]
@0xabdulkhalid there is already a JSON check in the workflow for that reason I'll be closing this issue

**Comment by 0xabdulkhalid** [comment]
@JasonDsouza212 can you close this as **Stale** ?

Closing this as Completed makes no sense, because this issue is the one which not appreciated **So better close this as Stale**.
