### ISSUE TITLE
[Feat]: Adding more number in forward sequence

### ISSUE THREAD

**Issue by AdityaKumar2408** [JasonDsouza212/free-hit#1445]
### What feature?

I have an idea to generate a four number sequence instead of three numbers in forward and backward of pages.

This feature help to skip 2 pages forward at once, helping user to more effectively.
(I know there's a search bar but still it helps in user interaction)

### Add screenshots

![Screenshot (500)](https://github.com/JasonDsouza212/free-hit/assets/110921916/334cda91-aa98-43cc-b8bd-142e8f6a73d3)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AdityaKumar2408** [comment]
Please assign this issue to me @VenomFate-619 @JasonDsouza212

**Comment by JasonDsouza212** [comment]
@AdityaKumar2408 that might cause a problem in the mobile view
