### ISSUE TITLE
[Bug]: The logos of some platform aren't visible in dark mode

### ISSUE THREAD

**Issue by AdityaKumar2408** [JasonDsouza212/free-hit#1447]
### What happened?

I found a BUG 🐞
Some logos of platform like AnimeSuge and RemixIcon are barely be seen in darkmode .

I will create a white background for these such that it will be visible to the users in dark mode.

### Add screenshots

![Screenshot (501)](https://github.com/JasonDsouza212/free-hit/assets/110921916/b604f34e-ada6-4504-be43-6838823e0a6a)
![Screenshot (502)](https://github.com/JasonDsouza212/free-hit/assets/110921916/56e1f991-e4e1-43c4-8dbb-b09b63221903)

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AdityaKumar2408** [comment]
Please assign me this issue @JasonDsouza212 @VenomFate-619

**Comment by VenomFate-619** [comment]
@AdityaKumar2408  give your update on this issue
