### ISSUE TITLE
[Bug]: Default message aren't visible in dark mode

### ISSUE THREAD

**Issue by AdityaKumar2408** [JasonDsouza212/free-hit#1448]
### What happened?

I found a BUG 🐞

The default message is not visible for not found items in dark mode.

I will change the text from black to whitish for dark mode and required styling.

### Add screenshots

![Screenshot (503)](https://github.com/JasonDsouza212/free-hit/assets/110921916/5e7860b2-4565-4593-8239-e9db15094efd)
![Screenshot (504)](https://github.com/JasonDsouza212/free-hit/assets/110921916/be1863ea-e0ab-46fb-9e20-f803d13b0fd4)

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AdityaKumar2408** [comment]
Please assign me this issue @JasonDsouza212 @VenomFate-619

**Comment by VenomFate-619** [comment]
@AdityaKumar2408 give your update.
