### ISSUE TITLE
[style]: Adding cancel option in search bar

### ISSUE THREAD

**Issue by AdityaKumar2408** [JasonDsouza212/free-hit#1449]
### What's the style idea?

We need to improve  

I would like to add a "x" cancel button to erase out the text written on search bar.

I will do this by adding a "x" button just before a search icon. 

### Add screenshots

![Screenshot (507)](https://github.com/JasonDsouza212/free-hit/assets/110921916/780dc4d4-fa59-4909-be0d-2885b71d6e14)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AdityaKumar2408** [comment]
Please assign me this issue @JasonDsouza212 @VenomFate-619

**Comment by JasonDsouza212** [comment]
When the user starts typing, the search symbol should transform into a cancel symbol. If there is no input, it should remain as the search icon itself. Also, take care of the styles in all media widths
