### ISSUE TITLE
[Bug]: Improving Search bar

### ISSUE THREAD

**Issue by AdityaKumar2408** [JasonDsouza212/free-hit#1450]
### What happened?

I found a BUG 🐞

The seperation between search icon and search bar gets removed or rather mixed with the dark mode setting.

I will solve this by adding a black border to make it visible.

### Add screenshots

![Screenshot (507)](https://github.com/JasonDsouza212/free-hit/assets/110921916/a8d6ee80-bbc3-4c3d-bef8-0e271ea2fba6)

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AdityaKumar2408** [comment]
Please assign me this issue @JasonDsouza212 @VenomFate-619

**Comment by JasonDsouza212** [comment]
@AdityaKumar2408 first you solve the previous assigned issue then we can think about this

**Comment by RishabhXD** [comment]
Can I do this?

**Comment by VenomFate-619** [comment]
@RishabhXD now you can work on this.
