### ISSUE TITLE
[Bug]:  Correction in footer

### ISSUE THREAD

**Issue by AdityaKumar2408** [JasonDsouza212/free-hit#1451]
### What happened?

I found a BUG 🐞

Hover effect of github doesn't matches with its recognised color as other platform do.

So, I would like to improve it.

### Add screenshots

![Screenshot (508)](https://github.com/JasonDsouza212/free-hit/assets/110921916/db3e4cda-eea5-41fc-b6e8-3b973fa006dd)

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AdityaKumar2408** [comment]
Please assign me this issue @JasonDsouza212 @VenomFate-619

**Comment by VenomFate-619** [comment]
you already had 3 issues to be fixed that why I am unassigning you

**Comment by Karmpatel960** [comment]
Hey, @VenomFate-619 I want to work on this issue Can you please Assign this to me?

**Comment by jamAL108** [comment]
Heyyy  @JasonDsouza212 @VenomFate-619  , Can you please assign this work to me ?

**Comment by RishabhXD** [comment]
Hi, I've fixed this issue
Kindly check
