### ISSUE TITLE
[Feat]: Add share icon

### ISSUE THREAD

**Issue by Akanksha-202** [JasonDsouza212/free-hit#1458]
### What feature?

The feature is to add a share icon to the top-right corner of the cards, enabling users to easily share the tools with others.

### Add screenshots

![image](https://github.com/JasonDsouza212/free-hit/assets/100708686/4c1a6124-15d2-4ee1-b092-8acd58f22fe2)

please assign this issue to me under GSSoC'23 label :)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by VenomFate-619** [comment]
What would be shared as tools do not have any specific link?

**Comment by Akanksha-202** [comment]
The site that they visit, they can share from the website only !

**Comment by VenomFate-619** [comment]
means the URL of the tool

**Comment by Akanksha-202** [comment]
Yeah

**Comment by VenomFate-619** [comment]
while implementing do add a [native share API ](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/share)

**Comment by Akanksha-202** [comment]
sure! will add that too

**Comment by JasonDsouza212** [comment]
@JasonDsouza212, I need you to improve the code. When someone shares the tool, the URL should be like this: if it's a 100L5 tool, then its URL should be **https://free-hit.vercel.app/?q=100L5**. By implementing this, more people will be directed to Free-hit, thus increasing the application's traffic. Additionally, they can explore Free-hit through this link.
