### ISSUE TITLE
Add chatGpt Sidebar

### ISSUE THREAD

**Issue by JasonDsouza212** [JasonDsouza212/free-hit#147]
Add chatGpt sidebar to extentions: https://chatgpt-sidebar.com/

**Comment by Bharadwajshivam28** [comment]
i want to work on it please assign sir

**Comment by Bharadwajshivam28** [comment]
> @Bharadwajshivam28 The issue has been solved, but there seem to be some spelling mistakes in the title. Do you want to work on that?"

Yes i want to work on it
