### ISSUE TITLE
[style]: Add "Prev & Next" Text in above Footer Pagination Design

### ISSUE THREAD

**Issue by NarendraKoya999** [JasonDsouza212/free-hit#1485]
### What's the style idea?

We need to improve  Pagination Design with **`Prev & Next`** to improving Best User Experience.
- **Please observe `Screenshots` of below like `Actual Behavior and Expected Behavior`**

### Add screenshots

Add screenshots:
### Actual UI:
![freehit-32](https://github.com/JasonDsouza212/free-hit/assets/84512164/7ee64779-1f4b-4734-ad92-c7eb6ceb2565)

### Expected UI:
![freehit-31](https://github.com/JasonDsouza212/free-hit/assets/84512164/3f5f9847-b09d-4811-91e1-2474bcdcb115)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by NarendraKoya999** [comment]
> @JasonDsouza212 . Please Review on My Issue? Also, Unassigned Issues are pending No : #891 #906 . Please Review on these 3 Issues. If Selectable , Kindly assign me

Hey @JasonDsouza212 . Kindly look onto My Query

**Comment by JasonDsouza212** [comment]
I have intentionally made it that way for a specific reason, so I'll be closing this issue.
