### ISSUE TITLE
[Bug]: Deceptive Site Warning!!!

### ISSUE THREAD

**Issue by bharathkalyans** [JasonDsouza212/free-hit#1493]
### What happened?

* I was testing out the speed of the website by changing the page continuously! and found  a BUG 🐞, where if I try to change the pages continuously, I am getting a Deceptive Warning. Not sure whether this bug is a specific one for my machine!

I am facing this issue only in chrome browsers!

### Add screenshots

https://github.com/JasonDsouza212/free-hit/assets/49526472/3d3f0e7b-4a4b-4f27-bf0a-573e4ab6ff55

* First I tried with Chrome browser and I started facing this issue, later when I tested with other browsers, there was no issue!

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge, Brave

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bharathkalyans** [comment]
Not sure what is causing this! 🧐

**Comment by JasonDsouza212** [comment]
@bharathkalyans, I think it's because of adding enhanced protection. I'll look into it and try to resolve it. Thank you, Bharat, for reporting the issue
