### ISSUE TITLE
[Bug]:  Searchbar text does not get updated!

### ISSUE THREAD

**Issue by adhamahmad** [JasonDsouza212/free-hit#1496]
### What happened?

I was trying the website and found a BUG 🐞. 
When I click on the autocomplete text in the searchbar, the searchbar text does not get updated.

### Add screenshots

https://github.com/JasonDsouza212/free-hit/assets/42949982/f65627f4-3058-4cce-8984-db5498ab6188

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JasonDsouza212** [comment]
@adhamahmad it has taken care now
