### ISSUE TITLE
Feature: Add Back to Top button

### ISSUE THREAD

**Issue by dhawal-793** [JasonDsouza212/free-hit#151]
As the app is getting bigger it is necessary to have a back to top button to  scroll up.

So I wanted to add a back to top button.

**Comment by Saurav-Pant** [comment]
assign it to me,i want to work on it

**Comment by dhawal-793** [comment]
> assign it to me,i want to work on it

Sorry brother, but I have already implemented it, if you want you can work on something else.

**Comment by Saurav-Pant** [comment]
> > assign it to me,i want to work on it
> 
> Sorry brother, but I have already implemented it, if you want you can work on something else.

No worries @dhawal-793, I will work on something else.
