### ISSUE TITLE
[Bug]: Warning Invalid DOM property

### ISSUE THREAD

**Issue by soubhik-111** [JasonDsouza212/free-hit#1516]
### What happened?

I found a BUG 🐞
Warning: Invalid DOM property

Assign me under GSSOC'23

### Add screenshots

![image](https://github.com/JasonDsouza212/free-hit/assets/90599826/d601ed0a-7c21-4b35-b345-c2d21054bc8f)

### What browsers are you seeing the problem on?

Chrome, Brave

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Coderdivine** [comment]
Hey, I want to work on this issue. Can you please assign it to me?

**Comment by soubhik-111** [comment]
The issue is been fixed in updated main branch So, I am closing this issue
