### ISSUE TITLE
Add removal.AI

### ISSUE THREAD

**Issue by JasonDsouza212** [JasonDsouza212/free-hit#152]
Add removal ai to AI: https://removal.ai/

**Comment by Bharadwajshivam28** [comment]
i want to work on it sir

**Comment by JasonDsouza212** [comment]
ok, you can start working on this @Bharadwajshivam28

**Comment by Bharadwajshivam28** [comment]
> ok, you can start working on this @Bharadwajshivam28 

Created a pr please check
