### ISSUE TITLE
[style]: updating and aligning the search bar and nav link items

### ISSUE THREAD

**Issue by shreyT19** [JasonDsouza212/free-hit#1529]
### What's the style idea?

We need to improve  the visual appearance and layout of the website's search bar and navigation link items.

### Add screenshots

Add screenshots

Before:
<img width="1414" alt="Screenshot 2023-07-31 at 4 24 33 PM" src="https://github.com/JasonDsouza212/free-hit/assets/116892456/0831627b-30e2-428a-ae5e-1ec262c6899d">

After:
<img width="1435" alt="Screenshot 2023-07-31 at 4 24 40 PM" src="https://github.com/JasonDsouza212/free-hit/assets/116892456/92ec1b33-1366-459a-a2e5-8b242126222b">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JasonDsouza212** [comment]
@shreyT19 can you align just the logo of the free-hit in the latest update of the code

**Comment by shreyT19** [comment]
Sure  !! Should i make it a bit smaller and allign it with the right side nav items ?

**Comment by JasonDsouza212** [comment]
I noticed that the Free-Hit logo in the desktop view is not aligned with the hamburger menu and search bar. Please work on fixing that
