### ISSUE TITLE
[Feat]: Adding a slider tool 

### ISSUE THREAD

**Issue by deepshikha2708** [JasonDsouza212/free-hit#1531]
### What feature?

Adding a slider in between the page number and view type, which will feature top websites.

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JasonDsouza212** [comment]
can you explain it properly?

**Comment by deepshikha2708** [comment]
basically, the dynamic slider which we see in news channels and websites featuring top news which keeps changing or moving
