### ISSUE TITLE
[Feat]: Add Multiple workflows for GitHub Repository[Description]

### ISSUE THREAD

**Issue by NarendraKoya999** [JasonDsouza212/free-hit#1537]
### What feature?
- **lock.yml:** This file is used for "Locking". It is likely used to prevent discussions or information from being modified or altered by locking conversations or threads.
- **prevent_multiple_issues.yml:** This file is used for "Preventing Multiple Issues". It helps in handling multiple issues in a project simultaneously by providing rules for managing and avoiding conflicting or overlapping issues.

### Add screenshots

Add screenshots

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by JasonDsouza212** [comment]
@NarendraKoya999, as of now, we don't need that feature. For that reason, I'll be closing this issue.
