### ISSUE TITLE
Add Super normal

### ISSUE THREAD

**Issue by JasonDsouza212** [JasonDsouza212/free-hit#154]
Add super normal to AI : https://supernormal.com/

**Comment by Bharadwajshivam28** [comment]
i want to work on it sir

**Comment by JasonDsouza212** [comment]
yes, you can work on this

**Comment by Bharadwajshivam28** [comment]
thanks

**Comment by Bharadwajshivam28** [comment]
@JasonDsouza212 Hello sir i have created a pr by adding super normal, magical and removal
