### ISSUE TITLE
[Bug]: Input is not getting empty on click of other sidemenu

### ISSUE THREAD

**Issue by biplavmz** [JasonDsouza212/free-hit#1542]
### What happened?

I found a BUG 🐞
Input is not getting empty on click of other side menu tab 
it should be empty while clicking on other menu after search 

### Add screenshots

<img width="930" alt="image" src="https://github.com/JasonDsouza212/free-hit/assets/68702055/ea65b3ff-a9ac-4736-bd3b-40f8e27bf1c8">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JasonDsouza212** [comment]
Attach a screen recording that demonstrates the changes you made to the code, showing how it affects the application across all media widths.

**Comment by biplavmz** [comment]
Hii @JasonDsouza212 I'm a GSSoC'23 contributor please add issue under gssoc label and level.

**Comment by SWASTI-SUNDAR** [comment]
Hey @JasonDsouza212 Can You assign this issue . I wants to Contribute

**Comment by JasonDsouza212** [comment]
You create a PR, Ill add the GSSOC label to your PR
