### ISSUE TITLE
[Feat]: Login Page using React Hooks

### ISSUE THREAD

**Issue by GiriprasadKrishnamurthy** [JasonDsouza212/free-hit#1555]
### What feature?

I have an idea to add a login page using react hooks

### Add screenshots

Add screenshots

![image](https://github.com/JasonDsouza212/free-hit/assets/96837347/6be0c6f0-480f-4163-91f0-ac0da966c212)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by JasonDsouza212** [comment]
As of now there is no database , so we cant do that
