### ISSUE TITLE
[Feat]: Add a LinkedIn share button in the About page

### ISSUE THREAD

**Issue by tanujbordikar** [JasonDsouza212/free-hit#1559]
### `Under GSSOC'23`

- I have an idea of adding a LinkedIn share button in the sidebar of the About page. 
- The LinkedIn Share Button is the easiest way to remind and encourage users to post and share your website on LinkedIn.

### Add screenshots

Example:
![linkedin](https://github.com/JasonDsouza212/free-hit/assets/91179998/5b222272-e6ab-49c3-ab22-47b32cbf5af1)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by PriyanshYawalkar** [comment]
assign me this issue

**Comment by tanujbordikar** [comment]
hey @JasonDsouza212, Can you please assign me this issue so that I can get the work done!

**Comment by tanujbordikar** [comment]
hey @JasonDsouza212, Can you please assign me this issue so that I can get the work done!

**Comment by CBID2** [comment]
Hey @JasonDsouza212. I see that it’s been a while since this issue has been solved. Can I be assigned to it?

**Comment by s1ddiq** [comment]
is this issue still open? i want to work on it.

**Comment by s1ddiq** [comment]
@JasonDsouza212
