### ISSUE TITLE
[Add]: Coding Ninjas in Coding Platforms 

### ISSUE THREAD

**Issue by ManishaSwain8** [JasonDsouza212/free-hit#1560]
### What tool are you adding and to what category?

We need to add Coding Ninjas in the coding platform.I have been using it personally and found it very effective for CP and DSA.So adding the link will be beneficial.

If this tool req. do assign under GSSOC 2023.

### Add Tool Link

Add tool link- https://www.codingninjas.com/

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] The tool is free for use

**Comment by agamswaroop619** [comment]
I can help with this. Can you please assign this issue to me?

**Comment by Muskan1009** [comment]
Please this issue to me

**Comment by JasonDsouza212** [comment]
The tool is already present in the Database
