### ISSUE TITLE
[Adding Tool]: Scrimba in Coding Platforms

### ISSUE THREAD

**Issue by ChiragAgg5k** [JasonDsouza212/free-hit#1561]
### What tool are you adding and to what category?

We need to add Scrimba, a Frontend coding platform. It has interactive screencasts that let you edit the code whenever you want, just as if you were pair programming with the teacher.

### Add Tool Link

Add tool link- https://scrimba.com/

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] The tool is free for use

**Comment by Muskan1009** [comment]
Please Assign this issue to me

**Comment by ChiragAgg5k** [comment]
https://free-hit.vercel.app/?q=scrimba

Scrimba already added.
