### ISSUE TITLE
Zoro.to needs to be updated to Aniwatch.to

### ISSUE THREAD

**Issue by agamswaroop619** [JasonDsouza212/free-hit#1562]
I noticed a little problem on the hosted site.

Zoro.to has been changed to Aniwatch.to for past 2 weeks.
Here is what should be done (would request maintainers to edit this checklist as required):

- [x] => Change link from 'Zoro.to' to 'aniwatch.to'

- [x]   => Update logo and details if necessary

Here are the screenshots of required pages:
<img width="1822" alt="Screenshot 2023-08-07 at 1 33 39 AM" src="https://github.com/JasonDsouza212/free-hit/assets/112094449/307d7380-6c06-4707-b9a3-0bc81d191462">

<img width="1822" alt="Screenshot 2023-08-07 at 1 37 01 AM" src="https://github.com/JasonDsouza212/free-hit/assets/112094449/1266f7c7-1394-4c5f-9851-06f13049d6d4">

### Code of [Conduct](`url`)

- [X] I agree to follow this project's Code of Conduct

**Comment by Muskan1009** [comment]
Assign this issue to me

**Comment by agamswaroop619** [comment]
Database has been updated. Thanks for solving issue #1562
