### ISSUE TITLE
[Bug]: Incorrect use of "class" attribute

### ISSUE THREAD

**Issue by tamannaaaaa** [JasonDsouza212/free-hit#1563]
### What happened?

In the JSX code, you are using the attribute "class" for your HTML elements, which is reserved for standard HTML. However, in React, the correct attribute to use for applying CSS classes is "className."

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Muskan1009** [comment]
please assign this issue to me
