### ISSUE TITLE
[Feat]: Add Sign in and sign up option

### ISSUE THREAD

**Issue by Muskan1009** [JasonDsouza212/free-hit#1565]
### What feature?

I have an idea, we can add a sign-in and sign-up option to make the website look more promising. I could help with the UI part of this feature. 

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Muskan1009** [comment]
Assign this issue to me

**Comment by agamswaroop619** [comment]
@Muskan1009  Can you please explain what does this feature do and how can it help users in detail?

**Comment by JasonDsouza212** [comment]
As of now, there is no database  so we cant achieve it
