### ISSUE TITLE
[Feat]:  Want to add our Contributor page in the website

### ISSUE THREAD

**Issue by HimanshuNarware** [JasonDsouza212/free-hit#1566]
### What feature?

I have an idea Details
Is your feature request related to a problem? Please describe.
Our Contributors page in the website
Describe the solution you'd like
We can add a Contributors page in the website. which is shows the name and the profile image of the contributor.and the number of commits is done by the contributor

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JasonDsouza212** [comment]
The page is already present in the application https://free-hit.vercel.app/community
