### ISSUE TITLE
[Feat]:  improve the style of next page pagination

### ISSUE THREAD

**Issue by biplavmz** [JasonDsouza212/free-hit#1576]
### What feature?

We need to improve the style of next page as there are many page of projects and on the screen it's visible only three so as my approach first 3 and last 3 pages number should be able to visible for user. Guess the user wants to go to last and first page

What we can do

Make visible like - < 1 2 3 ... 4 5 6 \>
Reason for requesting this change
As I am visiting the page and wants to get on last page but I have to click alot times to next button

<img width="152" alt="image" src="https://github.com/JasonDsouza212/free-hit/assets/68702055/09621dca-4261-44cf-8596-35541e7b0a1f">

Add screenshots
Place where the change will happen
image

I'm a GSSoC'23 contributor please assign me this issue under gssoc label and level. 

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JasonDsouza212** [comment]
In the mobile view, let it remain the same, but it can be changed in the desktop view as you mentioned.

**Comment by biplavmz** [comment]
ok

**Comment by biplavmz** [comment]
hii @JasonDsouza212 i am working on this can you please assign me
