### ISSUE TITLE
[Bug]: All the filters are not visible on the sidebar

### ISSUE THREAD

**Issue by kaifayazkhan** [JasonDsouza212/free-hit#1581]
### What happened?

The last filter option is not visible in the sidebar when we scroll.

# What we can do
We can add some padding at the bottom so all the options are clearly visible.

### Add screenshots

![image](https://github.com/JasonDsouza212/free-hit/assets/81459430/ce0f6034-9b81-4c16-939f-e2003a9d81db)

### What browsers are you seeing the problem on?

In google chrome and Microsoft edge.

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by kaifayazkhan** [comment]
@JasonDsouza212 Kindly assign this issue to me so I can fix the bug.

**Comment by s1ddiq** [comment]
assign me this issue please
