### ISSUE TITLE
[Adding Tool]: Want to add new tool

### ISSUE THREAD

**Issue by kaifayazkhan** [JasonDsouza212/free-hit#1583]
### What tool are you adding and to what category?

I want to add RAPID API which provides various APIs to developers which is free.and

### Add Tool Link

https://rapidapi.com/hub

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] The tool is free for use

**Comment by kaifayazkhan** [comment]
@JasonDsouza212  please assign it to me.

**Comment by carlos3020** [comment]
I'll try to solve this
