### ISSUE TITLE
[Bug]: "Deceptive Site Ahead" Error Triggered by Specific Letters in Search Bar (Chrome)

### ISSUE THREAD

**Issue by ansha001** [JasonDsouza212/free-hit#1596]
### What happened?

I found a BUG 🐞
I am encountering an issue when accessing the hosted demo site on Chrome browser. On entering any letter except for : f,j,l,p,q,v,y in the search bar, I'm given the "Deceptive Site Ahead" error by the browser.

### Add screenshots

Add screenshots: 
![image](https://github.com/JasonDsouza212/free-hit/assets/97624380/8eb9e163-cbbc-4650-ab12-389bd76c76a5)
![image](https://github.com/JasonDsouza212/free-hit/assets/97624380/abd2ceb9-fe2b-4674-b210-ef8492a248c1)

### What browsers are you seeing the problem on?
Chromium based browsers like Google Chrome, Brave

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JasonDsouza212** [comment]
@ansha001 do you know how to resolve it

**Comment by ansha001** [comment]
I have checked with the files: fuzzy_search.js, search_products.js, and the search portion under Home.jsx. I couldn't find any code that could lead to a false positive, or trigger such a warning. I think you check with the CSP rules defined.

**Comment by JasonDsouza212** [comment]
Ok, I'll look into it, or else We should avoid using use search params

**Comment by suraj719** [comment]
Is it solved now? i cant see any error like mentioned in the issue.

**Comment by JasonDsouza212** [comment]
If you use it in the chrome browser you might face this issue

**Comment by suraj719** [comment]
maybe but i am not facing this issue, i am using it in chrome browser only. !

**Comment by s1ddiq** [comment]
assign me this issue pls

**Comment by s1ddiq** [comment]
looked through some files, I am using chrome and am not experiencing an issue.
perhaps you may have to clear your cache

**Comment by ansha001** [comment]
I didn't clear the cache in any of the browsers however I'm not experiencing the issue now. Perhaps it was a false trigger that must have been resolved in any one of the previous commits.
