### ISSUE TITLE
[style]: Replace Alerts (from Bookmark and Link Share) to Toasts

### ISSUE THREAD

**Issue by vatsalsinghkv** [JasonDsouza212/free-hit#1600]
### What's the style idea?

We need to improve  the response we get from bookmark button and link share button with alert box which stops the flow of our app. Which is really annoying and a bad user experience.
<img width="1423" alt="Screenshot 2023-08-11 at 11 02 00 AM" src="https://github.com/JasonDsouza212/free-hit/assets/68834718/8bb66685-9eae-4504-9e54-1776c5ede508">

So I propose to implement toasts (notification like box with auto close functionality).
Example:
<img width="1140" alt="Screenshot 2023-08-11 at 11 02 31 AM" src="https://github.com/JasonDsouza212/free-hit/assets/68834718/0f4b2808-6299-4fe9-836d-0693dc0e9573">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JasonDsouza212** [comment]
@vatsalsinghkv looks cool and eligant go ahead and implement it
