### ISSUE TITLE
Add Merlin 

### ISSUE THREAD

**Issue by JasonDsouza212** [JasonDsouza212/free-hit#161]
Add Merlin to extensions :  https://chrome.google.com/webstore/detail/merlin-chatgpt-assistant/camppjleccjaphfdbohjdohecfnoikec

**Comment by Bharadwajshivam28** [comment]
i wan to work on it jason

**Comment by JasonDsouza212** [comment]
sure, go ahead @Bharadwajshivam28

**Comment by Bharadwajshivam28** [comment]
> sure, go ahead @Bharadwajshivam28 

Thanks 😊

**Comment by Bharadwajshivam28** [comment]
Its completed you can close it @JasonDsouza212
