### ISSUE TITLE
[Adding Tool]: Replit to the AI category

### ISSUE THREAD

**Issue by AhorIsaac** [JasonDsouza212/free-hit#1611]
### What tool are you adding and to what category?

We need to add replit to the database. Replit  is the collaborative browser based IDE that helps you build software collaboratively with the power of AI, on any device, without spending a second on setup.

### Add Tool Link

[Replit](https://replit.com/)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [ ] The tool is free for use

**Comment by H-SM** [comment]
Hey, @AhorIsaac! Hope you are having a great day. I wish to solve up this issue, it would be great if you can assign it up to me. I would try my best to complete it up. Thanks!
