### ISSUE TITLE
[Bug]: Replit as a duplicate tool in the db

### ISSUE THREAD

**Issue by AhorIsaac** [JasonDsouza212/free-hit#1612]
### What happened?

I found a BUG 🐞. Replit is duplicated in the database.

### Add screenshots

Add screenshots

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Utkarsh3128** [comment]
I have submitted a PR. Please review it.
