### ISSUE TITLE
[Feat]: Introducing a "Like" Button for Every Free Tool

### ISSUE THREAD

**Issue by Vanshika-Dargan** [JasonDsouza212/free-hit#1614]
### What feature?

I have an idea: why don't we introduce a "Like" button for our free tools? This way, users can express their appreciation, and we can sort the tools based on popularity. This feature would not only keep users informed about the most helpful tools but also encourage active participation in suggesting top-notch resources.

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JasonDsouza212** [comment]
@Vanshika-Dargan as of now we are not using a database ,if we use it in the future we can do that
