### ISSUE TITLE
refactor: use CDN link or make a separate folder for images 

### ISSUE THREAD

**Issue by priyankarpal** [JasonDsouza212/free-hit#1634]
Try to use the CDN link for images or make a separate folder for images. This will help to follow a clear project structure. Please tell me @JasonDsouza212 what should we use. CDN or separate `image` folder

- We are using images directly on the `assets` folder that's not a good practice.

![image](https://github.com/JasonDsouza212/free-hit/assets/88102392/6373649b-28d1-4fc8-a2de-2f3f31a2eed8)

**Comment by JasonDsouza212** [comment]
what service are you planning on using to store images?

**Comment by priyankarpal** [comment]
> what service are you planning on using to store images?

I will use github cdn

**Comment by priyankarpal** [comment]
@JasonDsouza212 you can assign someone

**Comment by JasonDsouza212** [comment]
@priyankarpal  sure
