### ISSUE TITLE
[Adding Tool]: onepace, heyMovies, hiAnime

### ISSUE THREAD

**Issue by bobbyy16** [JasonDsouza212/free-hit#1652]
### What tool are you adding and to what category?

We must add one pace, heyMovies, and hiAnime tools in the movies section for entertainment purposes

### Add Tool Link

Add tool link
one pace - https://onepace.net/watch
heyMovies - https://heymovies.to/home
Hi Anime - https://hianime.to/movie

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] The tool is free for use

**Comment by vaibhav18matere** [comment]
> ### What tool are you adding and to what category?
> We must add one pace, heyMovies, and hiAnime tools in the movies section for entertainment purposes
> 
> ### Add Tool Link
> Add tool link one pace - https://onepace.net/watch heyMovies - https://heymovies.to/home Hi Anime - https://hianime.to/movie
> 
> ### Code of Conduct
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  The tool is free for use

the website "heyMovies" has a weird UX; when we search any movie and click on it, then it redirects to the add and which blocks entire content of webpage. looks fishy, @bobbyy16 please check before merging this PR
