### ISSUE TITLE
Adding links

### ISSUE THREAD

**Issue by Bharadwajshivam28** [JasonDsouza212/free-hit#166]
![Screenshot from 2023-04-22 00-40-23](https://user-images.githubusercontent.com/108119109/233716483-fc1ad24b-9fe1-4d55-aaab-5947f1908a90.png)
 
We can create a Linkedin section also and in these we can give your profile link or if not then we can create a page and display "WE ARE BUILDING IT" page @JasonDsouza212

**Comment by Deva-1903** [comment]
Can we add free-hit repository link to the GitHub logo and your Twitter link to the twitter logo? @JasonDsouza212

**Comment by Bharadwajshivam28** [comment]
@Deva-1903 I have created this issue so i am working on this you can get on other one or create one of your

**Comment by Deva-1903** [comment]
Relax out, bro. I only inquired; I have not begun working on it, and I will not work on any issues until I am assigned to it. @Bharadwajshivam28

**Comment by Bharadwajshivam28** [comment]
okay brother @Deva-1903

**Comment by Bharadwajshivam28** [comment]
@JasonDsouza212 Can you suggest that which link to give or should we give it a text which will say WE ARE BUILDING IT
