### ISSUE TITLE
readme update 

### ISSUE THREAD

**Issue by scorcism** [JasonDsouza212/free-hit#17]
If the contributer wishesh to create new category 
we shoud also include the steps in readme.

**Comment by JasonDsouza212** [comment]
Yes, that is needed. We just need to change the UI design to implement this, and we are working on the UI. Once it is fixed, we can add these steps.

**Comment by scorcism** [comment]
okay

**Comment by priyankarpal** [comment]
@JasonDsouza212 still open?
