### ISSUE TITLE
Logo 

### ISSUE THREAD

**Issue by Bharadwajshivam28** [JasonDsouza212/free-hit#171]
These 2 logo are not clear visible . We can change these two logo and add clear visible logo

![Screenshot from 2023-04-22 19-05-52](https://user-images.githubusercontent.com/108119109/233788977-31ec611e-ca9a-4e24-9980-fe40cd24d4d0.png)

**Comment by JasonDsouza212** [comment]
Do you want to work on this @Bharadwajshivam28

**Comment by Bharadwajshivam28** [comment]
yes @JasonDsouza212
