### ISSUE TITLE
make navbar more Attractive

### ISSUE THREAD

**Issue by Ahtaxam** [JasonDsouza212/free-hit#174]
wanted to make navbar more beautiful and also improve search bar. 
can work on this issue ?

SearchBar like this

**Screenshots**
![Screenshot from 2023-04-25 11-04-45](https://user-images.githubusercontent.com/64573767/234188371-a6e6d77d-c08a-4248-9986-9c346ebcff82.png)

**Comment by JasonDsouza212** [comment]
Do you want to work on this @Ahtaxam

**Comment by Ahtaxam** [comment]
Yes, Sure

**Comment by Ahtaxam** [comment]
can i start working on this ?

**Comment by JasonDsouza212** [comment]
yes , you can start working on this @Ahtaxam

**Comment by Ahtaxam** [comment]
How is it now ? @JasonDsouza212 

![Screenshot from 2023-04-27 08-24-14](https://user-images.githubusercontent.com/64573767/234751744-d77c41dd-6fac-430b-97a8-6a138bcccba5.png)

**Comment by JasonDsouza212** [comment]
We now have a new UI. If you have any other ideas, let's discuss them here.

**Comment by Ahtaxam** [comment]
Yes. we can discuss. I have look into new UI there need to be more improvement.

**Comment by Ahtaxam** [comment]
Like if these are simple Card. then why is showing like clickable

![Screenshot from 2023-05-13 14-17-17](https://github.com/JasonDsouza212/free-hit/assets/64573767/6879b18f-b438-42e5-8e5e-a5ec9f628c25)

**Comment by JasonDsouza212** [comment]
I think we can remove the cursor: pointer; property.

**Comment by Ahtaxam** [comment]
Yes. And only set property to social links

**Comment by Ahtaxam** [comment]
resolve issue and open PR.
