### ISSUE TITLE
Changing user interface

### ISSUE THREAD

**Issue by bobbyy16** [JasonDsouza212/free-hit#177]
backgorund color - F1F1EF
primary color - 373530
font style - work sans

checkout illustartions and logo
![logo](https://user-images.githubusercontent.com/62874675/234447043-446f9d68-45dc-40e0-b003-67e2d46c7ec6.png)
![business-presentation-1 1](https://user-images.githubusercontent.com/62874675/234447227-3f8d354d-73e2-4211-9277-c3df5afef8ce.png)
![designer-desk-2 1](https://user-images.githubusercontent.com/62874675/234447228-6aa777e3-a5ca-4a99-97d5-04f17f08cf29.png)

**Comment by JasonDsouza212** [comment]
I didn't get you @bobbyy16

**Comment by bobbyy16** [comment]
These are the illustartions and logo, I used while designing user interface!

**Comment by JasonDsouza212** [comment]
Good we will start building it in some days

**Comment by bobbyy16** [comment]
sure! no worries
