### ISSUE TITLE
A default picture must be present if the image is not rendered.

### ISSUE THREAD

**Issue by aashay28** [JasonDsouza212/free-hit#178]
**Describe the bug**
A default picture must be present if the image is not rendered.

**Screenshots**

![must be a defalut image](https://user-images.githubusercontent.com/108337259/234521677-6fb86055-1826-43d3-88d6-1be267cd913f.png)

**Comment by JasonDsouza212** [comment]
Yes, that's a good suggestion. Do you want me to work on this, @aashay28 ?

**Comment by aashay28** [comment]
It's fine, you can assign it to me.

**Comment by masoudhsd** [comment]
Hello, I can do it as my first good issue! please assign it to me.

**Comment by JasonDsouza212** [comment]
@masoudhsd there are still many good first issue,that you can contribute to

**Comment by aashay28** [comment]
@JasonDsouza212 Please verify the changes.
