### ISSUE TITLE
A good and attractive Footer for page

### ISSUE THREAD

**Issue by Bharadwajshivam28** [JasonDsouza212/free-hit#180]
![Screenshot from 2023-04-26 17-46-09](https://user-images.githubusercontent.com/108119109/234572942-67252215-ca6f-4751-8cfa-fffc2811e4fe.png)

We can create a good footer for project. Currently footer is not more attractive

@JasonDsouza212

**Comment by JasonDsouza212** [comment]
Do you want to work on this @Bharadwajshivam28

**Comment by Bharadwajshivam28** [comment]
> Do you want to work on this @Bharadwajshivam28 

Yes i want to
