### ISSUE TITLE
Add OpenGraph

### ISSUE THREAD

**Issue by JasonDsouza212** [JasonDsouza212/free-hit#183]
**Add OpenGraph to tools** : https://www.opengraph.xyz/

**Comment by Bharadwajshivam28** [comment]
can i go with it @JasonDsouza212

**Comment by JasonDsouza212** [comment]
Yes @Bharadwajshivam28

**Comment by Bharadwajshivam28** [comment]
thanks @JasonDsouza212

**Comment by Bharadwajshivam28** [comment]
@JasonDsouza212 you can close this one as its completed
