### ISSUE TITLE
FEAT: Add an auto suggestion feature in search-bar

### ISSUE THREAD

**Issue by SowreRajan-dev** [JasonDsouza212/free-hit#186]
With auto suggestion, users can easily find what they're looking for without having to type out the entire search term. As they type, the search bar will suggest possible matches, allowing users to quickly find the content they need.
This feature not only saves time for the user, but also reduces the chances of spelling errors or incorrect search terms. Overall, adding auto suggestion to the Nav search bar is a simple yet effective way to improve user experience on your website.

![image](https://user-images.githubusercontent.com/75199296/235309241-9905ef9e-6e56-45be-8cbc-edbb3db45172.png)

It helps to suggest based on the website name's which helps user to quickly filter their needs. Like when user entered Re as per the image above, React dev tools will be suggested which helps to quick access for them.

**Comment by HarshPanchal26** [comment]
@SowreRajan-dev   good idea , I want to work with you on this issue , @JasonDsouza212  can you assign it to us ?

**Comment by SowreRajan-dev** [comment]
> @SowreRajan-dev good idea , I want to work with you on this issue , @JasonDsouza212 can you assign it to us ?

Yes , For sure , @HarshPanchal26

**Comment by JasonDsouza212** [comment]
Really, that's a very good optimization. Yes, both of you can start working on this. @SowreRajan-dev @HarshPanchal26
