### ISSUE TITLE
Add remixicon

### ISSUE THREAD

**Issue by JasonDsouza212** [JasonDsouza212/free-hit#197]
Add to remixicon tools: https://remixicon.com/

**Comment by mojjjtaba** [comment]
What do you want to add? can I help you?

**Comment by JasonDsouza212** [comment]
Yes, you can add this tool to database

**Comment by ydv-ankit** [comment]
working on it

**Comment by Tushar12222** [comment]
Hey @ydv-ankit ,
Is it fine if I work on this?

**Comment by JasonDsouza212** [comment]
Ya ,go ahead @Tushar12222

**Comment by Tushar12222** [comment]
Thanks @JasonDsouza212

**Comment by Tushar12222** [comment]
Hey @JasonDsouza212 ,
I have added remixicon to the db check PR #206 
Thank you.
