### ISSUE TITLE
Separate button for about page

### ISSUE THREAD

**Issue by suzy-g38** [JasonDsouza212/free-hit#215]
**Is your feature request related to a problem? Please describe.**

When you click on the free-hit logo it will redirect you to the "About" page. 

**Describe the solution you'd like**

If we can create a separate tab or section or button for about, it will be much better

**Comment by JasonDsouza212** [comment]
Yup that would be great , Do you want to work on this @suzy-g38

**Comment by suzy-g38** [comment]
Yup sure

**Comment by Karmpatel960** [comment]
Hey @JasonDsouza212 I would like to work on this Can you please assign this issue to me?
