### ISSUE TITLE
Spacing needed in About page

### ISSUE THREAD

**Issue by suzy-g38** [JasonDsouza212/free-hit#216]
**Describe the bug**
On the About page, there is no space around the "Learn More" option. That's why it is colliding with "Our Beloved Contributors" 
After the image card of the contributors, there is also very little space.

**To Reproduce**

1. Go to 'Home Page.'
2. Click on 'Free-Hit'
3. Scroll down to the bottom

**Expected behavior**
In the About page space is needed around the "Learn More" option and after the image card of the contributors.

**Screenshots**

![image](https://github.com/JasonDsouza212/free-hit/assets/62666287/958f0924-d40d-4585-8ccd-1e0d4943f74b)

![image](https://github.com/JasonDsouza212/free-hit/assets/62666287/085c8faa-560d-4345-b93d-f831c4102625)

**Comment by Shalini469717** [comment]
Can I work on this issue?

**Comment by Nishannaik** [comment]
Hey Is this issue assigned to anyone?

**Comment by suzy-g38** [comment]
Hey i am working and its almost done.
