### ISSUE TITLE
Add load more option

### ISSUE THREAD

**Issue by suzy-g38** [JasonDsouza212/free-hit#217]
**Is your feature request related to a problem? Please describe.**

On the home page, all the items are loaded at the beginning, and the list of items is really long, which is why the footer is not visible if we scroll down a little bit.

**Describe the solution you'd like**

So if we show some of the items and add a See More or a Load More button and after clicking that button rest of the items will be loaded that would be much better. A user who visited the site for the first time can get the gist of the site and also can see the footer, contact us and everything.

**Comment by suzy-g38** [comment]
> Ya that would be a good feature do you want to work on it @suzy-g38

yup

**Comment by bharathkalyans** [comment]
This feature will be good but the data is fetched from a local JSON file instead of a database(MongoDB or Supabase).
It would be great we can migrate the data to a remote db and fetch the data from the database right?

**Comment by suzy-g38** [comment]
> This feature will be good but the data is fetched from a local JSON file instead of a database(MongoDB or Supabase). It would be great we can migrate the data to a remote db and fetch the data from the database right?

yes indeed that will be great, I suggested that actually, it was maybe a month back- you can check the discussion section.....he didn't approve that because it was initial stage....but if he will approve it now that will be great.

**Comment by bharathkalyans** [comment]
Sure, will discuss it with Jason later once you will finish the pagination. 😃

**Comment by bharathkalyans** [comment]
Sure @JasonDsouza212 !! 😀

**Comment by suzy-g38** [comment]
@JasonDsouza212 I have set the load more option in this manner that, every time you click on see all it will show you the next 6 items(though this number can be changed if you want). So the user will have control over viewing stuff. Let me know if you want things in this manner or just click on See All button and all the products will be shown at once.

**Comment by JasonDsouza212** [comment]
I have worked on the pagination, and the UI is ready. However, there seems to be a small bug when searching for products. @suzy-g38, if you are working on this,  review the pagination branch and work on that branch.

**Comment by suzy-g38** [comment]
> I have worked on the pagination, and the UI is ready. However, there seems to be a small bug when searching for products. @suzy-g38, if you are working on this, review the pagination branch and work on that branch.

okay
