### ISSUE TITLE
SideBar covers the content

### ISSUE THREAD

**Issue by bobbyy16** [JasonDsouza212/free-hit#218]
A sidebar section in both home and bookmarks covers the card details.

We can move content little left, so that the card details can be visible

![Screenshot (1)](https://github.com/JasonDsouza212/free-hit/assets/62874675/24387c73-26ce-4fec-9e65-95a35cb866e4)
![Screenshot (2)](https://github.com/JasonDsouza212/free-hit/assets/62874675/01e0db2b-f75a-43fe-b49c-079dda078188)

**Comment by JasonDsouza212** [comment]
It was intentionally made like that ,but what you suggested is a good feature . Do you want to work on this @bobbyy16

**Comment by kedar1998** [comment]
Hi, I would like to work on this issue under GSSOC'23. We can make navbar cover full screen on click. Once user click on navbar item it will close and go to that section. Below are images that i am trying to explain for both mobile and desktop screens.

![image](https://github.com/JasonDsouza212/free-hit/assets/103363619/2994384e-9dce-46c1-b5e2-75878081b90a)

![image](https://github.com/JasonDsouza212/free-hit/assets/103363619/aef4fa79-de7a-485e-8dcc-3f3f66d3282a)

**Comment by kedar1998** [comment]
The solution I provided will also cover issue  #237

**Comment by bobbyy16** [comment]
Hii @kedar1998, the above-provided solution is good, but can you also make cards visible? 

Refer AWS website (products section)

**Comment by JasonDsouza212** [comment]
As the issue is inactive, I will be closing it.
