### ISSUE TITLE
typo in product.json

### ISSUE THREAD

**Issue by dev1ayush** [JasonDsouza212/free-hit#235]
{
    "productName": "MetaMask",
    "category": "extensions",
    "image": "https://bit.ly/423Iw9p",
    "link": "https://bit.ly/421AAp4",
    "description": "taMask is an extension for accessing Ethereum enabled distributed applications, or \"Dapps\" in your browser!"
  },

this is the code from product.json(code line -994) and in description there should be metamask instead of tamask.

**Comment by JasonDsouza212** [comment]
Can you correct it @jaydeepkhatri

**Comment by dev1ayush** [comment]
bro i was gonna fix this.
it would have been my first contribution 😭

**Comment by JasonDsouza212** [comment]
@dev1ayush , There are  many good first issues, You can contribute to it
