### ISSUE TITLE
Add daily.dev site 

### ISSUE THREAD

**Issue by Ayaan49** [JasonDsouza212/free-hit#236]
daily.dev is a professional network for developers to learn, collaborate, and grow together.

**Comment by JasonDsouza212** [comment]
@Saqlain-qark go ahead and add it

**Comment by Saqlain-qark** [comment]
Thanks will work on it and let you know asap

**Comment by Ayaan49** [comment]
I raised this issue. Why am I not getting assigned for this? @JasonDsouza212

**Comment by Saqlain-qark** [comment]
sorry for taking your issue, btw i wanted to mention i have made changes and added it and created a pull request hope it gets approved
