### ISSUE TITLE
Side Menu not closing after selecting an option 

### ISSUE THREAD

**Issue by Saqlain-qark** [JasonDsouza212/free-hit#237]
In the homepage when we are accessing the side menu to access a certain category like resume builder, AI tools, etc at that time after selecting a certain option/category, it shows the items of that certain category only but the issue is the side menu is not closing after selecting an option , The ideal scenario should be after selecting a category the side menu should be closed and the homepage should the display the tools/contents for their particular category 

Here, I have attached the screenshot of the issue for better understanding: https://github.com/JasonDsouza212/free-hit/assets/61051533/76c1d8fb-b88d-41f5-87c9-50f3db341384

**Comment by JasonDsouza212** [comment]
Yup, that would be a good feature. Do you want to work on it @Saqlain-qark

**Comment by Saqlain-qark** [comment]
I can try working on that but before that if you know can you please provide where exactly this function code is so i could start working right away

**Comment by haseebyousuf** [comment]
Hey, @JasonDsouza212  would love to work on this issue if @Saqlain-qark is not working.

**Comment by JasonDsouza212** [comment]
As the issue is inactive, I will be closing it.
