### ISSUE TITLE
[Feat]: Search By Category Option Can Be Included

### ISSUE THREAD

**Issue by Ishita-Ghosh-25** [JasonDsouza212/free-hit#238]
### What feature?

Search by category option can be included. Suppose we search AI or Remote Jobs then also the relevant tools should arrive.

### Add screenshots

Add screenshots
<img width="942" alt="image" src="https://github.com/JasonDsouza212/free-hit/assets/70560812/cce43ad2-e12b-4db3-ac11-6ed351541aaf">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JasonDsouza212** [comment]
Yes that would be good , Do you want to work on it @Ishita-Ghosh-25

**Comment by Ishita-Ghosh-25** [comment]
@JasonDsouza212 sure.

**Comment by RLTek** [comment]
@JasonDsouza212 It looks like this is no longer assigned. Could I work on it?
