### ISSUE TITLE
Button Sizes in Card

### ISSUE THREAD

**Issue by jaydeepkhatri** [JasonDsouza212/free-hit#240]
### What happened?

The actual clickable link(button) is small in size.
I am attaching screenshot. The red area in the button shows it's clickable portion. If the user clicks at other place it does nothing.

### Add screenshots

Current Button Clickable area (in red)
![image](https://github.com/JasonDsouza212/free-hit/assets/29619945/c58dc12f-b40c-4865-a8fe-0db98909420a)

Expected button clickable area( in area)
![image](https://github.com/JasonDsouza212/free-hit/assets/29619945/da3235ae-96fc-4428-91c2-8479f9551d9f)

### Possible Solution:

Remove the padding from the `<button>` & add that to the `<a>` tag.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Tushar12222** [comment]
Hey @jaydeepkhatri ,
I could work on this issue if you dont mind.

**Comment by JasonDsouza212** [comment]
While designing,  be aware of the design's responsiveness across all media queries. Test the design on different media sizes to ensure its compatibility, and then create a pull request to incorporate the changes.
