### ISSUE TITLE
[style]: Set cursor to pointer when hovering over items in the sidebar

### ISSUE THREAD

**Issue by alefDev-prog** [JasonDsouza212/free-hit#244]
### What's the style idea?

I think it would look better if the cursor was set to pointer when hovering over the items in the sidebar. 

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JasonDsouza212** [comment]
@alefDev-prog Do you want to work on this @alefDev-prog

**Comment by alefDev-prog** [comment]
Yes I could do that

**Comment by alefDev-prog** [comment]
Which branch?
