### ISSUE TITLE
bug : Hamburger menu is not working in latest PR

### ISSUE THREAD

**Issue by bobbyy16** [JasonDsouza212/free-hit#25]
Hamburger menu is not working in the mobile version and also, when you click the button(any button).

**Comment by bobbyy16** [comment]
![1](https://user-images.githubusercontent.com/62874675/222881827-a380e5b7-33ae-4301-b52a-9f71e53302b2.png)

**Comment by JasonDsouza212** [comment]
Can you work on that??

**Comment by bobbyy16** [comment]
Thats actually the new design from #24 . Now its actually displays github and twitter in mobile view as well
