### ISSUE TITLE
[Bug]: Responsiveness issue in mobile

### ISSUE THREAD

**Issue by SirSimon162** [JasonDsouza212/free-hit#255]
### What happened?

I found a BUG 🐞
Bug: There is white space on the right side of the website when viewing it in mobile. This white space is present between the content and the right edge of the browser window. It affects the overall appearance and layout of the website and doesn't give good impression on the user.

Expected Behavior: The website should utilize the available space and not have unnecessary white space on the right side.

PS: I would like to work on this issue.

### Add screenshots

Current behavior: 
![Before](https://github.com/JasonDsouza212/free-hit/assets/103681122/3afcfaea-f8d1-459c-b92e-e95114dd6699)
Expected behavior: 
![after](https://github.com/JasonDsouza212/free-hit/assets/103681122/4e5a1d22-9dd4-4e5b-a9af-6ec9a251041b)

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JasonDsouza212** [comment]
Yes, that was an unrecognized bug. Thank you for finding it. Shall I assign it to you so that you can work on it? @SirSimon162

**Comment by SirSimon162** [comment]
Sure! @JasonDsouza212
