### ISSUE TITLE
[Bug]: Broken Image

### ISSUE THREAD

**Issue by SaratAngajalaoffl** [JasonDsouza212/free-hit#256]
### What happened?

Image for awesome screen capture and recorder blocked due to cors

### Add screenshots

<img width="344" alt="image" src="https://github.com/JasonDsouza212/free-hit/assets/60383339/776d6ae9-45f4-4d4b-99a8-6f5878c22489">

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JasonDsouza212** [comment]
DO you want to work on this @SaratAngajalaoffl

**Comment by SaratAngajalaoffl** [comment]
@JasonDsouza212 already opened a PR for the fix
