### ISSUE TITLE
[Bug]: Text overlapping onto icon

### ISSUE THREAD

**Issue by SaratAngajalaoffl** [JasonDsouza212/free-hit#258]
### What happened?

If the name of the tool is too long, it overflows onto the icon as shown in the attached screenshot

### Add screenshots

<img width="352" alt="image" src="https://github.com/JasonDsouza212/free-hit/assets/60383339/69492fbe-f048-4eeb-b563-28fde8c758b5">

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JasonDsouza212** [comment]
I think we need to keep a limit on the Title

**Comment by SaratAngajalaoffl** [comment]
It can be truncated past a certain length @JasonDsouza212. I'll fix it if it's not picked up by anyone else in the next few hours

**Comment by shobhitexe** [comment]
I am willing to take it!

**Comment by JasonDsouza212** [comment]
is anyone working on this??

**Comment by shobhitexe** [comment]
> is anyone working on this??

i am willing to take it you can assign this to me

**Comment by JasonDsouza212** [comment]
yes you can work on this @shobhitexe

**Comment by shobhitexe** [comment]
Hello have created a PR #271 plz review it thanks
