### ISSUE TITLE
Add Showwcase site 

### ISSUE THREAD

**Issue by Ayaan49** [JasonDsouza212/free-hit#263]
### What feature?

Showwcase is a network built for developers where developers hang out and find new opportunities together as a community.

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JasonDsouza212** [comment]
@Ayaan49  It's more of a social app. Do you think we can consider it as a tool?

**Comment by Ayaan49** [comment]
Can I work on it?
