### ISSUE TITLE
[Feat]: Closing the menu after clicking outside the menu

### ISSUE THREAD

**Issue by AbhayaShankar** [JasonDsouza212/free-hit#267]
### What feature?

It would be a better UI experience if a user suppose clicks outside the menu bar once opened and then the menu closes.

### Add screenshots

![issue](https://github.com/JasonDsouza212/free-hit/assets/113185442/05bf2474-4f27-4db4-b9b3-5945285e62dd)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JasonDsouza212** [comment]
That would be good. Do you want to work on this @AbhayaShankar

**Comment by AbhayaShankar** [comment]
Yeah, @JasonDsouza212 I will add this feature. No issue 👍
