### ISSUE TITLE
[style]: Learn more button not clickable in /about route

### ISSUE THREAD

**Issue by AbhayaShankar** [JasonDsouza212/free-hit#268]
### What's the style idea?

This is in 1536px screen display

The cause for this is the z-index of OUR BELOVED CONTRIBUTORS is higher that rest text.

### Add screenshots

![image](https://github.com/JasonDsouza212/free-hit/assets/113185442/a86e8681-5147-4e93-bedb-832ef9741933)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AbhayaShankar** [comment]
I went through the code and found that the issue is not with the z-index but with the design with what the desktop size is used for designing
In 1536px desktop screen it's looking something similar to this.

**Comment by JasonDsouza212** [comment]
do you want to work on this @AbhayaShankar

**Comment by AbhayaShankar** [comment]
Yep, I will do this
