### ISSUE TITLE
ADD DARK MODE FEATURE

### ISSUE THREAD

**Issue by DHRUVKHANDELWAL00** [JasonDsouza212/free-hit#274]

**Comment by JasonDsouza212** [comment]
Do you have any ideas regarding this? I have tried it earlier, but it didn't turn out well and seemed odd for this theme.

**Comment by DHRUVKHANDELWAL00** [comment]
@JasonDsouza212  your UI is quite uique and basic. It would be easy to work on this feature as i have done the same in few other projects. We could use primary purple and teal or maybe some other combinations. I would try to add screenshots here only once i do, if u like it i would make a PR.

**Comment by JasonDsouza212** [comment]
Sorry for the late reply,Do you want to work on this @DHRUVKHANDELWAL00 and are you working under GSSOC23

**Comment by DHRUVKHANDELWAL00** [comment]
Yes @JasonDsouza212

**Comment by KamalSritha-04** [comment]
Can you please assign me this issue?

**Comment by rishuraj1** [comment]
hey @JasonDsouza212 if no one is working, could you please assign it to me.
