### ISSUE TITLE
ADD MORE ANIMATION TO THE CARDS

### ISSUE THREAD

**Issue by DHRUVKHANDELWAL00** [JasonDsouza212/free-hit#275]

**Comment by JasonDsouza212** [comment]
We had a flip card animation earlier, but it felt kind of annoying, so we removed it. If you have any other animation ideas, feel free to share them here.

**Comment by DHRUVKHANDELWAL00** [comment]
I will do it and show you video here once i do.

**Comment by JasonDsouza212** [comment]
Are you working under GSSOC23 @DHRUVKHANDELWAL00

**Comment by DHRUVKHANDELWAL00** [comment]
Yes @JasonDsouza212
