### ISSUE TITLE
[Feat]: Adding extension

### ISSUE THREAD

**Issue by iriteshmishra** [JasonDsouza212/free-hit#277]
### What feature?

I am adding extension

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by iriteshmishra** [comment]
I want to work on adding a volume booster extension #276 can you assign me. I forgot to get assign and I have already created a PR.

**Comment by JasonDsouza212** [comment]
yes @iriteshmishra go ahead and add it
