### ISSUE TITLE
[Feat]: GSSoC'23 | Addition New Tool (ChatGPT Writer)

### ISSUE THREAD

**Issue by YashkShrivas4491** [JasonDsouza212/free-hit#279]
### What feature?

I have an idea to add the ChatGpt Writer tool link:-https://chatgptwriter.ai/

Enter your command in the ChatGPT Writer command input field to generate the response. A command can be any instruction like:
1.write an email about any open position in marketing team
2.write email about salary negotiation.

could you assign me this issue @JasonDsouza212 

### Add screenshots

Add screenshots
![chrome-capture-2023-4-24](https://github.com/JasonDsouza212/free-hit/assets/87111197/f3e1b008-43a9-4805-8804-a1a1e6a354e3)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JasonDsouza212** [comment]
go ahead and add it @YashkShrivas4491
