### ISSUE TITLE
Want to improv the font styling in the website [style]: 

### ISSUE THREAD

**Issue by HimanshuNarware** [JasonDsouza212/free-hit#282]
### What's the style idea?

We need to improve   the font styling in the website,  we can change the font family,size, and font weight to improve the UI of the website,

### Add screenshots

Add screenshots
![font](https://github.com/JasonDsouza212/free-hit/assets/83147410/4a78b192-112c-4830-9bd8-cd55befe03b6)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JasonDsouza212** [comment]
Are you working under GSSOC23 @HimanshuNarware

**Comment by HimanshuNarware** [comment]
> Are you working under GSSOC23 @HimanshuNarware

Yess sir
