### ISSUE TITLE
[Feat]: Contributor page

### ISSUE THREAD

**Issue by suzy-g38** [JasonDsouza212/free-hit#285]
### What feature?

If we create a dedicated section to show all the name of the contributors that will be great I think.

I would like to work on it under GSSOC23

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JasonDsouza212** [comment]
That would be a good idea, and please try to maintain the theme style while creating the page.

**Comment by JasonDsouza212** [comment]
For the next contribution, you can work on making the page more beautiful, or should I assign it to someone?

**Comment by suzy-g38** [comment]
> For the next contribution, you can work on making the page more beautiful, or should I assign it to someone?

Nope I would love to do it

**Comment by JasonDsouza212** [comment]
> > For the next contribution, you can work on making the page more beautiful, or should I assign it to someone?
> 
> Nope I would love to do it

Create a separate issue for that
