### ISSUE TITLE
[Feat]: Add like or Upvote button

### ISSUE THREAD

**Issue by suzy-g38** [JasonDsouza212/free-hit#286]
### What feature?

If we add a like button or a Upvote button that will be much more interactive.

I would like to work on this issue under GSSOC23

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JasonDsouza212** [comment]
That would be good, but where should we store the upvotes?

**Comment by suzy-g38** [comment]
> That would be good, but where should we store the upvotes?

We can achieve it in two ways....1. we can create a db and store it or 2. we can manipulate the db to store the likes.

**Comment by JasonDsouza212** [comment]
As of now, there are fewer users. Therefore, let's not plan on migrating to a database. Once the number of users increases, we can consider storing the data in a database.

**Comment by kedar1998** [comment]
We don't need database to store upvote. We can use local storage. I have already implemented functionality. One use can only upvote once for one card. I am using state and local storage.

Can you please assign me this issue under GSSOC'23

**Comment by JasonDsouza212** [comment]
That's good, but what purpose will it solve? If this feature were global to all users and there was a database, it would be an amazing feature. However, as of now, I don't think it will serve any purpose. What are your thoughts about it, @kedar1998?

**Comment by kedar1998** [comment]
Yeah true, It won't be global.
