### ISSUE TITLE
[Bug]: Broken Images 

### ISSUE THREAD

**Issue by JasonDsouza212** [JasonDsouza212/free-hit#287]
### What happened?

I found a BUG 🐞:
Some tools have broken image links, so replace them with new images.

### Add screenshots

Add screenshots
![Screenshot from 2023-05-24 21-52-32](https://github.com/JasonDsouza212/free-hit/assets/74404894/bda9cb55-ff68-4ccd-a120-728d0c4936c2)

### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

**Comment by aashi-ihsaa** [comment]
Hello, I am a contributor under GSSOC'23 and I want to work in this issue. Please assign me this under GSSOC and I will solve it asap.

**Comment by Mayuresh-22** [comment]
Hey, @JasonDsouza212 I have been working on this issue and it is almost done. It would be great if you assign this issue to me.
Thank you
