### ISSUE TITLE
[Feat]: Adding About Us Page

### ISSUE THREAD

**Issue by lakhan06** [JasonDsouza212/free-hit#289]
### What feature?

I Want to add About us page in the website .

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Mayuresh-22** [comment]
Hey, @lakhan06 there is already an About page on the website.
Click on the FREE-HIT logo on the navbar and you will be redirected to the About page.
Thank You

**Comment by JasonDsouza212** [comment]
@lakhan06 If you click on the 'Free-Hit' title, it will redirect you to the about page. 

There is an issue regarding the addition of an 'About' button in the navbar. If any of you want to work on it, go ahead, but please keep in mind the design in all media queries.

**Comment by JasonDsouza212** [comment]
I think we can close this issue
