### ISSUE TITLE
[Bug]: Website is not working

### ISSUE THREAD

**Issue by shaikahmadnawaz** [JasonDsouza212/free-hit#293]
### What happened?

Website is not working properly, components on the Navbar are falling down.

Will you assign this issue to me.

I'm in GSSOC'23

### Add screenshots

![Screenshot (847)](https://github.com/JasonDsouza212/free-hit/assets/96189881/72ab0e39-63f4-4ed1-b2ee-bcd55fbfb276)
![Screenshot (848)](https://github.com/JasonDsouza212/free-hit/assets/96189881/db36f00f-3b39-41bf-ac8b-7cb2bf67a80b)

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JasonDsouza212** [comment]
@shaikahmadnawaz Please check with other devices because I haven't received any complaints about this. I have personally checked it as well. However, if you still encounter any issues, please let me know so that we can  work on resolving them.

**Comment by JasonDsouza212** [comment]
As the website is working fine ,I'll be closing this issue @shaikahmadnawaz
