### ISSUE TITLE
[style]: Fixing broken contributors page

### ISSUE THREAD

**Issue by dhrumishah** [JasonDsouza212/free-hit#297]
### What's the style idea?

We need to improve  contributors page. The page is colliding with footer. Also the button is colliding.

![image](https://github.com/JasonDsouza212/free-hit/assets/84569241/14a2e2bf-1f59-4dec-a94c-11d382cf7b29)

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dhrumishah** [comment]
> @dhrumishah  At what media queries are you experiencing this bug?

Dekstop view

**Comment by JasonDsouza212** [comment]
if it is still the case, Do you want to work on this?

**Comment by dhrumishah** [comment]
> Can you please check with other devices as well? It appears to be working on some devices.

yes working on other screens
