### ISSUE TITLE
[Feat]: Adding Piped 

### ISSUE THREAD

**Issue by prasanta10** [JasonDsouza212/free-hit#298]
### What feature?

Piped is an alternative privacy-friendly YouTube frontend which is efficient by design.

### Add screenshots

![Screenshot from 2023-05-25 10-17-53](https://github.com/JasonDsouza212/free-hit/assets/91861864/50a3d3e2-7bd2-4457-98fe-e00312bbfc57)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JasonDsouza212** [comment]
Go ahead and add it @prasanta10
