### ISSUE TITLE
[style]: add spacing

### ISSUE THREAD

**Issue by Abhiramjampani** [JasonDsouza212/free-hit#301]
### What's the style idea?

We need to improve  css of free hit logo page add some space between learn more and OUR BELOVED CONTRIBUTORS 
please assign this issue to me @JasonDsouza212  i can make it using css 

### Add screenshots

Add screenshots
![Screenshot (145)](https://github.com/JasonDsouza212/free-hit/assets/126624416/b1f1b7d3-953f-4ce4-94aa-fb9086554af3)
add some space between learn more and OUR BELOVED CONTRIBUTORS 
please assign this issue to me @JasonDsouza212  

### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

**Comment by JasonDsouza212** [comment]
What media query are you encountering this bug at?
