### ISSUE TITLE
[Feat]: Adding theme light/dark mode

### ISSUE THREAD

**Issue by Abhiramjampani** [JasonDsouza212/free-hit#302]
### What feature?

I have an idea i can create it by using react js
please assign it to me @JasonDsouza212 

### Add screenshots

Add screenshots
![image](https://github.com/JasonDsouza212/free-hit/assets/126624416/359708e7-366f-4b67-8513-a041822550eb)
i can add threme button there and add theme for background @JasonDsouza212 if you assign this issue to me i can start working on it 

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by JasonDsouza212** [comment]
Yes, you can start working on this. However, someone is already working on it, and this issue is a duplicate. Please talk to the assigned person and come up with a solution.

**Comment by JasonDsouza212** [comment]
Are you working under GSSOC23 @Abhiramjampani

**Comment by Abhiramjampani** [comment]
> Are you working under GSSOC23 @Abhiramjampani
yes

**Comment by Abhiramjampani** [comment]
can you please assign it to me @JasonDsouza212
