### ISSUE TITLE
[Feat]: Open the social media links in new tab 

### ISSUE THREAD

**Issue by mohammadshaad** [JasonDsouza212/free-hit#303]
### What feature?

The social media links should open in new tab. Right now it opens in the same tab.
 I am a GSSoC'23 contributor and want to work on this to improve the user experience.

### Add screenshots

<img width="1399" alt="image" src="https://github.com/JasonDsouza212/free-hit/assets/89409389/287e82ea-b992-41f3-8fb4-f3cceb0eea34">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mohammadshaad** [comment]
@JasonDsouza212 kindly assign me this issue

**Comment by JasonDsouza212** [comment]
You can work on it @mohammadshaad
