### ISSUE TITLE
[Bug]: Search button is not working

### ISSUE THREAD

**Issue by DEVANSHUKEJRIWAL** [JasonDsouza212/free-hit#304]
### What happened?

I found a BUG 🐞
 
When i click on search button it doesn't allow to search irrespective of clicking on the placeholder part.

I would like to work on this issue, so could you assign it under the GSSoC'23 tag

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JasonDsouza212** [comment]
It seems to be working fine can you confirm it with other device

**Comment by DEVANSHUKEJRIWAL** [comment]
the icon of the search button is not working so it want that to work

**Comment by JasonDsouza212** [comment]
@DEVANSHUKEJRIWAL  As of now, the button is just for showcasing that it's a search area.

 The search bar filters products as soon as you type something, and even the suggestions are loaded when you click on the suggested tool. 

So, what can the search icon do when clicked? What results are you expecting? If you provide justification, it would be easier for me to acknowledge it.

**Comment by JasonDsouza212** [comment]
Yes, that would be good. @DEVANSHUKEJRIWAL, would you like to work on it?

**Comment by DEVANSHUKEJRIWAL** [comment]
yes
