### ISSUE TITLE
[Bug]: Page doesnot redirect to other pages from Bookmarks

### ISSUE THREAD

**Issue by pooranjoyb** [JasonDsouza212/free-hit#306]
### I found a BUG 🐞

**The page deosn't redirect to other pages like `Remote Jobs`, `AI`, `Resume Builder` from the Bookmarks Tab**

I would like to fix this issue under GSSoC '23. Would be glad if you'd assign me. Thanks! @JasonDsouza212 @priyankarpal 

#### Here is a Demonstration

[screen-capture (2).webm](https://github.com/JasonDsouza212/free-hit/assets/90945182/4d8732a9-61c3-4f4d-a4a7-c09d924d18e1)

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JasonDsouza212** [comment]
Good one, @pooranjoyb We can display a message when there are no tools in the category in bookmarks. Do you want to work on this?

**Comment by pooranjoyb** [comment]
Hey @JasonDsouza212 
I went through the code and found that there's something else going around with the **Bookmarks Page**
so what happening is that
- say I bookmarked a tool from `AI` and `Remote Jobs`
- Then those are being shown in the respective `Bookmarks Links`, like when I click on `AI`, I can see the **Bookmarks** I made with `AI` and others respectively.
- But However, the rest are all empty. 
Perhaps, those buttons in the Bookmarks page were **not** for rendering the contents (like the Home Page does) but to display only the bookmarks. 

So, I was thinking, rather than displaying **No Bookmarks to Show**, we can say that **User didn't Bookmarked any tool in `AI` category**, hence removing any further confusions.

### Or you'd want to keep it as it is. Please Lemme know. Thanks!

![image](https://github.com/JasonDsouza212/free-hit/assets/90945182/94082657-16c1-416e-9266-002b1e8a8d22)
