### ISSUE TITLE
[Bug]: Hard-coded value of year in the copyright section.

### ISSUE THREAD

**Issue by abhinav-m22** [JasonDsouza212/free-hit#307]
### What happened?

In the copyright section of the web page, the year 2023 is hard-coded.
It is not the standard way of writing code.
Everytime the code will have to be changed for updating the year.
Instead, add a function to dynamically fetch the year from a function which is the best practice to add the copyright to any website to make it look formal.

I want to work on this feature implementation.
Please assign me task under GSSoC'23.

### Add screenshots

<img width="339" alt="image" src="https://github.com/JasonDsouza212/free-hit/assets/113239388/825853c9-aedd-4370-b341-c4d8b1a35218">

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JasonDsouza212** [comment]
Do you want to work on this @abhinav-m22 ?

**Comment by abhinav-m22** [comment]
> Do you want to work on this @abhinav-m22 ?

Yes I want to work on this issue under GSSoC'23. Please assign me the same.
