### ISSUE TITLE
[style]: PAGINATION on the home page

### ISSUE THREAD

**Issue by RJ025** [JasonDsouza212/free-hit#309]
### What's the style idea?

hello @JasonDsouza212 
issue : all the cards come on one page 
improvement : it would be better if website have **pagination** mean some amount of boxes on one page and then user can navigate to next page 
**pagination** is dividing content into discrete pages, usually for navigation.

I would like to work on this feature.
under GSSOC'23 tag 

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JasonDsouza212** [comment]
There is a branch names pagination ,you can work on that branch ,it has some bugs during searching so look into it once @RJ025
