### ISSUE TITLE
I want to enhance the whole UI on the whole page 

### ISSUE THREAD

**Issue by sarthak-star** [JasonDsouza212/free-hit#313]
### What's the style idea?

We need to improve overall UI of the Home page

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sarthak-star** [comment]
i would like to work on this issue under GSSOC'23 . please assign this to me

**Comment by JasonDsouza212** [comment]
Like what all things you want to enhance @sarthak-star . Give a brief idea about it

**Comment by sarthak-star** [comment]
i would like to add some hover effects ,make some transitions smoother and more pleasant.I want to make this website more aesthetic and visually appealing.

**Comment by JasonDsouza212** [comment]
Go ahead and work on it @sarthak-star
