### ISSUE TITLE
[style]:  Adding an image in the search not found page

### ISSUE THREAD

**Issue by NehaKariya0309** [JasonDsouza212/free-hit#314]
### What's the style idea?

When the search term does not give any result, we can attach an image along with a catchy message to inform them of the unavailability of tools.

### Add screenshots

Add screenshots
![Screenshot (63)](https://github.com/JasonDsouza212/free-hit/assets/100693529/85a6ec06-c53d-485b-932b-46cf58a991da)

I am willing to work on this issue.
Thanks,
Neha Kariya

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JasonDsouza212** [comment]
@NehaKariya0309 you can start working on it

**Comment by JasonDsouza212** [comment]
Are you working under GSSOC23 @NehaKariya0309

**Comment by NehaKariya0309** [comment]
@JasonDsouza212 , yes sir I am a GSSoC'23 contributor.

**Comment by NehaKariya0309** [comment]
@JasonDsouza212 , sir my PR #363 has been merged but the points have not been added for the same.(I got to know from the leaderboard). Kindly look into this.
Regards,
Neha Kariya
