### ISSUE TITLE
[Feat]: ADDING A FEED BACK SECTION

### ISSUE THREAD

**Issue by kharshita590** [JasonDsouza212/free-hit#315]
### What feature?

I have an idea 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JasonDsouza212** [comment]
As there is no database, we cannot store the feedback anywhere. Therefore, I think we cannot implement this feature for now.

**Comment by kharshita590** [comment]
I can create using react js and can show it below the feedback section

**Comment by kharshita590** [comment]
Hey can you provide me your email , as it is required.

**Comment by JasonDsouza212** [comment]
jasondsouza212@gmail.com.

**Comment by JasonDsouza212** [comment]
Are you working under GSSOC23 @kharshita590

**Comment by kharshita590** [comment]
Yes
