### ISSUE TITLE
[Adding Functionality]: Adding functionality of closing side Navbar on clicking anywhere in the body section

### ISSUE THREAD

**Issue by Sar-thak-3** [JasonDsouza212/free-hit#316]
### What happened?

I found a BUG 🐞
"Learn More" button on the About page is not responsive. It is not working well on my pc.

### Add screenshots

![image](https://github.com/JasonDsouza212/free-hit/assets/100359818/68e86cfb-7aa1-41cc-99b9-208a19a8b288)

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Sar-thak-3** [comment]
Mentors, Kindly assign me this issue under GSSoc 23

**Comment by JasonDsouza212** [comment]
@Sar-thak-3 This issue has already been addressed, so it is a duplicate version of it. You can work on it and create a pull request. If everything works well, I can merge it.

**Comment by Sar-thak-3** [comment]
@JasonDsouza212 I think this issue has already been resolved. I thought of adding another functionality to the project, closing the side navbar by clicking anywhere else. Currently, the side navbar close only when that "cross" button is clicked. So if you are okay with I will change this issue and pull the request for the same.

**Comment by Sar-thak-3** [comment]
https://github.com/JasonDsouza212/free-hit/assets/100359818/2ebe08bf-3884-4cc7-9526-8527e5e9f6e3

This functionality I am trying to add, kindly take a look.

**Comment by JasonDsouza212** [comment]
Are you working under GSSOC23 @Sar-thak-3

**Comment by Sar-thak-3** [comment]
Yes

> Are you working under GSSOC23 @Sar-thak-3

Yes @JasonDsouza212
