### ISSUE TITLE
Add Descriptions to cards

### ISSUE THREAD

**Issue by JasonDsouza212** [JasonDsouza212/free-hit#32]
- Most cards do not have a description section due to the new card design
- Please add a description of up to 12 words based on the tool.

**Comment by shyamtawli** [comment]
Hey @JasonDsouza212 I can work on it and can you please some example how you want descriptions?

**Comment by JasonDsouza212** [comment]
## The description should convey the purpose of the tool featured on the card, using a maximum of 10-12 words
![Screenshot from 2023-03-11 10-34-42](https://user-images.githubusercontent.com/74404894/224466351-1dd14e0e-494d-41e5-9b86-87bb8a9eff15.png)

**Comment by JasonDsouza212** [comment]
1 navigate to src/DB/product.js
2 There you can add a description

**Comment by shyamtawli** [comment]
@JasonDsouza212 Okay, can you please assign me.

**Comment by JasonDsouza212** [comment]
ya you can start working on this and create a pull request stating this issue
