### ISSUE TITLE
[Bug]: After clicking on bookmark it automatically scrolls up.

### ISSUE THREAD

**Issue by omk-coder** [JasonDsouza212/free-hit#321]
### What happened?

I found a BUG 🐞 when i tried to bookmark the bottom products as well as middle product it automatically scrolls up to the top of the page.. To understand this bug clearly I have aslo recorded an video. Please do take a look at it.  Like I need to go down again and again to visit or bookmark the product or tools.

https://github.com/JasonDsouza212/free-hit/assets/93393539/62c16489-b161-4b57-8b76-ab1a2bd3cd48

### Add screenshots

Add screenshots

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JasonDsouza212** [comment]
Good eye, @omk-coder  ! Would you like to work on this?

**Comment by CodeMongerrr** [comment]
Its not scrolling up. The <a> tag you have linked in the bookmarks have href="#" which reloads the page and it seems that you scrolled up. I have not gone through the entire code but you just have to pass the right link

**Comment by CodeMongerrr** [comment]
Just remove the anchor tag from the Bookmark button 

![image](https://github.com/JasonDsouza212/free-hit/assets/99281767/d8ef6492-0c3e-4709-a6bd-608d7a06bdf7)

**Comment by omk-coder** [comment]
@CodeMongerrr thanks for suggestion i was worked on it..

**Comment by omk-coder** [comment]
@CodeMongerrr thanks for the suggestion i am working on it.. I shared this issue cause sometime my browser end up running slow so just though that may be it not an actually issue but problem with my browser. anyways working on it.
