### ISSUE TITLE
[Docs]: add readme badges

### ISSUE THREAD

**Issue by S-ishita** [JasonDsouza212/free-hit#322]
### what's wrong in the documentation?

We need to add readme badges.Please assign this issue to me

### Add screenshots

![badges](https://github.com/JasonDsouza212/free-hit/assets/104543751/4dc6dc66-e74a-41c8-9a19-2896939df1bd)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JasonDsouza212** [comment]
Go ahead and add it @S-ishita

**Comment by Gautam-10137** [comment]
@JasonDsouza212 Please assign me this issue under GSSOC'23
