### ISSUE TITLE
[Feat]: wanted to add a like button 

### ISSUE THREAD

**Issue by doppedheart** [JasonDsouza212/free-hit#323]
### What feature?

I have an idea to add a like button to each of the website shown .
a user can upvote the website or leave it as it is .
this feature will show how popular the website is and we can sort the more popular website accordingly and show the user .
this will create great experience for user as he may know many familiar websites on top .
wanted to work on this feature

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dhawal-793** [comment]
@doppedheart I think this a great idea. We will only show the most popular tools on the Home page and when someone clicks on any category only then we will show the tools/products accordingly.

But for this, we have to use a database, because we can not store all the likes for this many tools on the website as it is dynamic not static.

**Comment by JasonDsouza212** [comment]
@doppedheart  Yes, as of now, we are not planning on storing data in a database. Therefore, I believe we cannot work on this at the moment. If you have any alternative ways to implement this feature, let us know so that we can discuss it further.

**Comment by dhawal-793** [comment]
Yes when we plan to use a database then will implement this.

**Comment by doppedheart** [comment]
Currently, I am not aware of any alternative approaches, but I am motivated to explore additional possibilities. If the decision is made to incorporate a database into the website, I would be enthusiastic about implementing this feature. Please inform me if you choose to proceed with integrating a database, as I would be delighted to assist in the implementation.

**Comment by JasonDsouza212** [comment]
As of now, we are not planning on storing the data in a database. However, if we decide to implement that feature in the future, we will reach out to you for assistance. For this reason, I will be closing this issue. Thank you for your time

There are still more issues that you can help us solve by contributing. We would be pleased to have you contribute to our project.
