### ISSUE TITLE
[Feat]: Add Community Page

### ISSUE THREAD

**Issue by mariamsayeed** [JasonDsouza212/free-hit#326]
Add Community Page

I have an idea to add community page where user can give feedback and can also add more websites. Developers can also request admin to add there websites.

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JasonDsouza212** [comment]
Since there is no database, how do you plan on implementing it?

**Comment by mariamsayeed** [comment]
I can implement it after the database is there in the website

**Comment by JasonDsouza212** [comment]
As of now, we are not planning on storing the data in a database. However, if we decide to implement that feature in the future, we will reach out to you for assistance. For this reason, I will be closing this issue. Thank you for your time.

**Comment by mariamsayeed** [comment]
thank you
