### ISSUE TITLE
[style]: Enhance Navbar

### ISSUE THREAD

**Issue by SxxAq** [JasonDsouza212/free-hit#327]
### What's the style idea?

We need to improve  the Navbar. The Current Navbar looks very basic and dull. 

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JasonDsouza212** [comment]
What extra things are you planning on adding?

**Comment by SxxAq** [comment]
Style the navbar to look more eye pleasing and dark mode toggle too

**Comment by JasonDsouza212** [comment]
Do you want to work on this @SxxAq

**Comment by SxxAq** [comment]
> Do you want to work on this @SxxAq 

Sure
