### ISSUE TITLE
[style]: Cards Design update[GSSOC'23]

### ISSUE THREAD

**Issue by Nagapadmini7** [JasonDsouza212/free-hit#328]
### What's the style idea?

We need to improve the card design.
Assign this to me under GSSOC'23.

### Add screenshots

Add screenshots

### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

**Comment by JasonDsouza212** [comment]
You can work on this, but please keep the website theme as it is.

**Comment by Nagapadmini7** [comment]
Can you please add GSSOC'23 tag too

**Comment by akanksha984** [comment]
Please assign it to me under gssoc'23. I want to work on this issue
