### ISSUE TITLE
[Feat]: Filter the projects using search query params.

### ISSUE THREAD

**Issue by kailashchoudhary11** [JasonDsouza212/free-hit#329]
### What feature?

We are filtering the tools with the help of `useState` hook. Suppose, if a user applies some filtering on the tools and then he/ she wants to share those filtered tools to his/her friends. With the current approach that is implemented in the codebase it is not possible. Instead of this if we filter based on query params the user will be able to share the filtered tools with others as well. And the filter will be still available even when the user refreshes the page.

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JasonDsouza212** [comment]
What do you mean by sharing the website??

**Comment by kailashchoudhary11** [comment]
> What do you mean by sharing the website??

Sharing the link of live site of course

**Comment by kailashchoudhary11** [comment]
Hey @JasonDsouza212 Can you share your discord username? Also have you joined the channel related to this project in the GSSoc Server?f

**Comment by JasonDsouza212** [comment]
Do you want to work on this issue @kailashchoudhary11

**Comment by kailashchoudhary11** [comment]
> Do you want to work on this issue @kailashchoudhary11

Yeah I would love to.

**Comment by JasonDsouza212** [comment]
Are you working under GSSOC23

**Comment by kailashchoudhary11** [comment]
> Are you working under GSSOC23

Yeah, We talked on discord.

**Comment by JasonDsouza212** [comment]
Yes I remember now

**Comment by kailashchoudhary11** [comment]
> Yes I remember now

There's a bug in the Navbar 🥲 Someone changed the conditions I guess. The search bar is only visible on the about us page and it's hidden on other pages

**Comment by JasonDsouza212** [comment]
It has been resolved, and now you can work on it. @kailashchoudhary11
