### ISSUE TITLE
[style]: Adding logo in footer

### ISSUE THREAD

**Issue by Dimple-Choudhary** [JasonDsouza212/free-hit#330]
### What's the style idea?

We need to add the **logo in the footer** but with a different color, so it will be visible when we change website from the light mode to dark or vice versa,  it should  be visible.
_under GSSoC_

### Add screenshots

Added a  screenshots
![Group 2](https://github.com/JasonDsouza212/free-hit/assets/96401557/46f37163-dad5-485c-99a7-2f263215675b)
_This is just an example I didn't find a free hit logo.  so just FH text inside a square_ 
If you want we can change the background color  

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JasonDsouza212** [comment]
Yes, that would be good. We can invert the logo so that it will suit the navbar.

**Comment by JasonDsouza212** [comment]
Are you willing to work on this, @Dimple-Choudhary?

**Comment by Dimple-Choudhary** [comment]
YES @JasonDsouza212 , I will can you tell me what you mean by  invert the logo?

**Comment by JasonDsouza212** [comment]
Do you want me to provide you with the logo? @Dimple-Choudhary

**Comment by Dimple-Choudhary** [comment]
yes Thank you, can you please assign me this issue? @JasonDsouza212
