### ISSUE TITLE
IMPROVE ABOUT US SECTION

### ISSUE THREAD

**Issue by whizzy23** [JasonDsouza212/free-hit#332]
There is a bug in about us page where Learn More button is coinciding with heading also the footer section is coinciding with the cards . Also , I will be making this page responsive.
I would like to fix that issue.
Please assign this issue to me
Earlier
![earlier](https://github.com/JasonDsouza212/free-hit/assets/129520458/44b18844-4d7d-4181-bab6-d6fa9724e2ec)
After Fix
![after fix](https://github.com/JasonDsouza212/free-hit/assets/129520458/e782e77b-3692-4a6e-b641-7e3c31ab9847)

**Comment by JasonDsouza212** [comment]
you can start working on this, but test the code with all media queries

**Comment by whizzy23** [comment]
Ok . Thanks for assigning it to me.

**Comment by whizzy23** [comment]
Sir currenty i am working on making this about page responsive , is it okay?

**Comment by whizzy23** [comment]
currently this much is done

Uploading Untitled.mp4…

**Comment by whizzy23** [comment]
currently this much is done

https://github.com/JasonDsouza212/free-hit/assets/129520458/7013a4b6-4efc-4b40-9ef1-8b654bcd20c7

**Comment by JasonDsouza212** [comment]
It looks okay. As far as I know, when I use Linux and view it in Chrome, I see the exact result.
[Screencast from 28-05-23 06:37:32 PM IST.webm](https://github.com/JasonDsouza212/free-hit/assets/74404894/d5907bf8-2da0-47c2-b51c-ff121046ca3e)

Can you confirm again using it in some other system

**Comment by whizzy23** [comment]
i have recorded from windows

**Comment by JasonDsouza212** [comment]
@whizzy23  can you increase the card width a little bit more , because it's looking too thin

**Comment by whizzy23** [comment]
ok I will increase the card width , also I have done these changes for mobile dimensions accordingly
