### ISSUE TITLE
[Feat]: Adding a new free too to the website

### ISSUE THREAD

**Issue by Mahitej28** [JasonDsouza212/free-hit#335]
### What feature?

Hello, I am Mahima Churi, a proud contributor of GSSoc ' 23.

I have an idea of adding a free UI/UX tool to the website, which would help the users in building creative stuff with less effort.
I would like to work on this project.
Also, I would like to enhance the UI of the Navbar Section.
Things I would be working on:
📌Adding a new free tool
📌Enhancing the UI of the Navbar like making the font size smaller, working on the search icon

If you think it is legit then do assign me the issue under GSSoC '23 with the level of the PR as well

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JasonDsouza212** [comment]
You can start working on it @Mahitej28

**Comment by Mahitej28** [comment]
Suree can u assign this issue to me under GSSoc'23, also as my exams are going on I would be working on this by the first week of june is that ok?

**Comment by JasonDsouza212** [comment]
Ok not a problem
