### ISSUE TITLE
[Bug]: Download Hub Website

### ISSUE THREAD

**Issue by Shiva-Sai-ssb** [JasonDsouza212/free-hit#336]
### What happened?

I have observed an issue with the URL for the download hub website. I suggest considering its removal or replacement with the updated link.

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JasonDsouza212** [comment]
Do you want to work on this @Shiva-Sai-ssb ?

**Comment by Shiva-Sai-ssb** [comment]
I will be happy to work on this issue.

**Comment by Shiva-Sai-ssb** [comment]
Please advise if you would like me to remove the website or replace it with the updated link. @JasonDsouza212

**Comment by JasonDsouza212** [comment]
Can you tell me what exactly is wrong with the url and are you working under GSSOC23

**Comment by Shiva-Sai-ssb** [comment]
> Can you tell me what exactly is wrong with the url and are you working under GSSOC23

I am attempting to access the website, but it appears to be unresponsive. I suspect that the website has undergone a URL change. Please review the attached screenshot for further reference. Furthermore, I would like to clarify that I am not affiliated with GSSOC23.


![Screenshot (78)](https://github.com/JasonDsouza212/free-hit/assets/112751524/5380f9ed-fcce-4090-8d40-ef2d8db92e3d)

**Comment by Shiva-Sai-ssb** [comment]
> ya you can work on it @Shiva-Sai-ssb

I apologize for the confusion, but I sought guidance regarding whether it would be more appropriate to remove the website entirely or update it with the new link.
