### ISSUE TITLE
[Bug]: Double border in cards content

### ISSUE THREAD

**Issue by Keshav76** [JasonDsouza212/free-hit#338]
### What happened?

I found a BUG 🐞. On the home page of the website we can find dual borders and that is not looking so attractive.
I want to improve it to a single border. 

### Add screenshots

Its currently like:
![image](https://github.com/JasonDsouza212/free-hit/assets/71920541/00d6d84c-359d-430b-8b55-fd14db46402e)
I want to improve it to: 
![image](https://github.com/JasonDsouza212/free-hit/assets/71920541/33f3f34c-f6d1-4c68-9b56-c6707fb2b951)

### What browsers are you seeing the problem on?

Microsoft Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JasonDsouza212** [comment]
I don't think the application has the design you mentioned. Someone created that pull request, but it has not been implemented yet

**Comment by rt-001** [comment]
@JasonDsouza212 I can implement this assign this to me
