### ISSUE TITLE
[Feat]:  Refactor the code to use only one Navbar.

### ISSUE THREAD

**Issue by kailashchoudhary11** [JasonDsouza212/free-hit#339]
### What feature?

Currently, we are using 2 navbars. One for the About page and one for the other pages. Although, what I noticed is that both the Navbars are almost identical. Instead of creating separate Navbar for about page we can just do conditional rendering to not render the search box in the about page. Creating a new component is not required.

### Add screenshots

Add screenshots

### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

**Comment by kailashchoudhary11** [comment]
@JasonDsouza212 Yeah of course.
Also, can your provide your discord username?

**Comment by JasonDsouza212** [comment]
> @JasonDsouza212 Yeah of course. Also, can you provide your discord username?
Jason212#4807

**Comment by kailashchoudhary11** [comment]
> > @JasonDsouza212 Yeah of course. Also, can you provide your discord username?
> > Jason212#4807

It's incorrect. If you're on the gssoc discord server can you just send a Hi in `#general`

**Comment by Mayuresh-22** [comment]
Hey @kailashchoudhary11,

I guess there is one thing you are missing out on aboutnav.jsx. The aboutnav.jsx of the About page not only focuses on the search bar in the navbar of the About page but also focuses on the sidebar of the page. If you just see the original version of the code you will get know that the About page has a different sidebar than other pages. 

Screenshots: 
(Home/Bookmark page sidebar)
![CaptureHome](https://github.com/JasonDsouza212/free-hit/assets/111348926/2cc0a1ca-141d-4a9a-87cc-aab4dcc4db0d)

(About page sidebar)
![CaptureAbout](https://github.com/JasonDsouza212/free-hit/assets/111348926/c39eb2bf-9f91-4f30-b2c4-fafb1baefa6c)

So I think this might be the reason the developer decided to make separate navbars. It will be great if you look into it.
Thank You.

**Comment by kailashchoudhary11** [comment]
Hey Thank you for pointing it out @Mayuresh-22 I'll take care of it as well.
