### ISSUE TITLE
Adding home Page button to redirect to home page [style]: 

### ISSUE THREAD

**Issue by SagarPatil007** [JasonDsouza212/free-hit#340]
### What's the style idea?

We need to improve  404 error page by adding home page button.
can you please assign me this role @JasonDsouza212 

### Add screenshots

Add screenshots[
![image](https://github.com/JasonDsouza212/free-hit/assets/58733512/127342d0-191c-4a9c-ab40-36d34ce28631)
](url)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JasonDsouza212** [comment]
Do you want to work on this @SagarPatil007

**Comment by SagarPatil007** [comment]
yes , because there is no button to go back to home page

**Comment by JasonDsouza212** [comment]
are you working under Gssoc23 @SagarPatil007

**Comment by SagarPatil007** [comment]
yes
