### ISSUE TITLE
Using tailwind css for styling [Enhancement🚀]

### ISSUE THREAD

**Issue by rohan9024** [JasonDsouza212/free-hit#341]
### What's the style idea?

Advantages of using tailwind css over plain css-

1) Easy and free-to-use.
2) Better CSS Styling Process.
3) Highly customizable.
4) Responsiveness and Security.

### Add screenshots

Add screenshots

### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

**Comment by JasonDsouza212** [comment]
Do you want to work on this
