### ISSUE TITLE
Adding Animations to the home page using framer motion

### ISSUE THREAD

**Issue by rohan9024** [JasonDsouza212/free-hit#342]
### What feature?

I can add animations to the website using framer motion. Please assign me

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JasonDsouza212** [comment]
Go ahead and add it @rohan9024

**Comment by JasonDsouza212** [comment]
Are you working under Gssoc23 @rohan9024

**Comment by rohan9024** [comment]
> Are you working under Gssoc23 @rohan9024 

Yess
