### ISSUE TITLE
description missing 

### ISSUE THREAD

**Issue by dev1ayush** [JasonDsouza212/free-hit#344]
### What happened?

this tools description is missing.
it should be updated 
see screenshot below 

i want to work on this 

### Add screenshots

Add screenshots
![Screenshot (22)](https://github.com/JasonDsouza212/free-hit/assets/103983890/7d60f2e7-66e0-428f-9b7a-a373b25970b8)

### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

**Comment by JasonDsouza212** [comment]
Do you want to work on this @dev1ayush

**Comment by dev1ayush** [comment]
yeah
