### ISSUE TITLE
Add background and dropdown option to navbar

### ISSUE THREAD

**Issue by manaver** [JasonDsouza212/free-hit#346]
The current navbar lacks a background and a dropdown option, which affects the visual appeal and user experience of the website. This issue aims to address these missing features and enhance the navbar's functionality.

## Proposed Solution

1. Add a background to the navbar to provide visual distinction and improve readability.

2. Implement a dropdown option that shows a menu when clicked. The menu should include the following options: Home, Bookmark, and About.

## Expected Behavior

- The navbar should have a visually appealing background that complements the overall design of the website.

- When the user clicks on the dropdown option, a menu should appear with the options: Home, Bookmark, and About. Clicking on any of these options should perform the corresponding action or navigate to the respective page.

Screenshots:
![image](https://github.com/JasonDsouza212/free-hit/assets/78682260/2d83b835-9a31-4165-9aae-59825d137063)

**Comment by manaver** [comment]
Please assign this issue to me as I am a GSSOC'23 contributor

**Comment by JasonDsouza212** [comment]
The navbar already has a background color, and it was intentionally designed that way. 

Additionally, there are navigation buttons on the navbar. Considering these factors, why do we need a dropdown button.

 In the mobile view, we already have a hamburger menu. Therefore, could you please justify the need for it?

**Comment by manaver** [comment]
Hi @JasonDsouza212 thanks for replying, my concern is For large width screen the two navbar cover most area(height aprox 20-30%) of the screen and the screen and the navbar is fixed. If we add a drop down in the 2nd navbar it will be more user friendly and user can see more info on the screen

**Comment by JasonDsouza212** [comment]
You can try implementing it, and then we can assess the results before making a decision. Should I assign this task to you? Are you participating in GSSoC23?

**Comment by manaver** [comment]
> You can try implementing it, and then we can assess the results before making a decision. Should I assign this task to you? Are you participating in GSSoC23?

Yes I'm a gssoc 23 participant 🙂

**Comment by manaver** [comment]
> > You can try implementing it, and then we can assess the results before making a decision. Should I assign this task to you? Are you participating in GSSoC23?
> 
> Yes I'm a gssoc 23 participant 🙂



> You can try implementing it, and then we can assess the results before making a decision. Should I assign this task to you? Are you participating in GSSoC23?

Hi @JasonDsouza212  , just let u know I check the updated website and it seems like the issue is solved, now the navlinks is in one nav instead of two so i am closing the issue.

**Comment by manaver** [comment]
@JasonDsouza212 can i raise a issue on pagination and search feature? or this is already assigned?

**Comment by JasonDsouza212** [comment]
@manaver you can do that

**Comment by JasonDsouza212** [comment]
Sorry, @manaver , I didn't see your reply here. However, this issue has already been resolved, so I'll be closing it.
