### ISSUE TITLE
remove duplicate tools from database

### ISSUE THREAD

**Issue by dev1ayush** [JasonDsouza212/free-hit#347]
### What happened?

some tools are duplicated in database i think it need to be fixed...

see screenshot below👇

i want to work on this 

### Add screenshots

Add screenshots
![Screenshot (24)](https://github.com/JasonDsouza212/free-hit/assets/103983890/597ef076-ddf2-451d-9b8a-2d59392670d7)
![Screenshot (25)](https://github.com/JasonDsouza212/free-hit/assets/103983890/51d0b411-c384-4e1c-9150-18e6fa7a48d7)

### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

**Comment by dev1ayush** [comment]
so far i found 4 tools that has been duplicated - fatkun, css shadow , reduce image and sd moviepoint

**Comment by JasonDsouza212** [comment]
Do you want to work on this @dev1ayush

**Comment by dev1ayush** [comment]
yeah sure
