### ISSUE TITLE
[Feat]: SideBar Closing

### ISSUE THREAD

**Issue by arin-paliwal** [JasonDsouza212/free-hit#349]
### What feature?

# Issue: Sidebar Closing Behavior

## Description
Currently, when the sidebar is opened, it can only be closed by clicking on the cross icon that appears within the sidebar. However, it would be more user-friendly if the sidebar could also be closed by clicking anywhere on the screen outside the sidebar.

## Steps to Reproduce
1. Open the application or website.
2. Locate the sidebar and click on it to open it.
3. Try clicking anywhere outside the sidebar to close it.

## Expected Behavior
When the sidebar is open, clicking anywhere outside the sidebar should close it.

## Actual Behavior
Currently, clicking anywhere outside the sidebar does not close it. The sidebar can only be closed by clicking on the cross icon within the sidebar.

## Possible Solution
Implement a functionality where clicking anywhere outside the sidebar will trigger the closing action, in addition to the existing cross icon.

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JasonDsouza212** [comment]
This issue has been addressed earlier by others

Do you want to work on this @arin-paliwal

**Comment by arin-paliwal** [comment]
> This issue has been addressed earlier by others
> 
> Do you want to work on this @arin-paliwal

yes

**Comment by JasonDsouza212** [comment]
are you working under Gssoc23 @arin-paliwal

**Comment by arin-paliwal** [comment]
> are you working under Gssoc23 @arin-paliwal

Yes
I had resolved the conflicts but i am sorry to say that I tried every possible solution but the issue is not reslolving
clicking anywhere else on the screen to close is working but it is getting conflicted with close button 
I am still trying to figure it our

**Comment by JasonDsouza212** [comment]
This issue is resolved, so I'll be closing it.
