### ISSUE TITLE
[style]:  Redesigning a the website with Figma. [GSSoC'23]

### ISSUE THREAD

**Issue by 1Shubham7** [JasonDsouza212/free-hit#351]
### What's the style idea?

We need to improve  The style of the website. the design of the website is too basic. I can create a good figma file for a new design for the website. Starting with buttons I have designed a few buttons that can replace the existing buttons on website.

### Add screenshots

Add screenshots

Existing buttons can be replaced by: 
![buttons_design](https://github.com/JasonDsouza212/free-hit/assets/116020663/db4cdef5-a2f9-43f9-b791-67b6190e9439)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 1Shubham7** [comment]
Please assign me this issue under GSSoC'23

**Comment by JasonDsouza212** [comment]
We intentionally made the website look as it does now. If you have any ideas for enhancing the website based on the current theme, you can start working on it. @1Shubham7

**Comment by 1Shubham7** [comment]
Ok @JasonDsouza212  . I will show you some ideas.
