### ISSUE TITLE
[Feat]: Add codesandbox 

### ISSUE THREAD

**Issue by sumitkr2000** [JasonDsouza212/free-hit#356]
### What feature?

I have an idea to add a code-sandbox to free tools. It is an online code editor which is very convenient for making small applications. Please assign me this issue. Thank you!

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dev1ayush** [comment]
but its already added .
search on website

**Comment by JasonDsouza212** [comment]
@sumitkr2000 It is already present in DB. For this reason, I'll be closing this issue

**Comment by sumitkr2000** [comment]
@JasonDsouza212 ok bro sorry i didn't see
