### ISSUE TITLE
Add a section [CONTRIBUTING.md]

### ISSUE THREAD

**Issue by JasonDsouza212** [JasonDsouza212/free-hit#369]
### what's wrong in the documentation?

**We need to add** 

A step-by-step procedure in the CONTRIBUTING.md file on how to add a section.

### Add screenshots

you can add it before the Note
![Screenshot from 2023-05-28 17-36-13](https://github.com/JasonDsouza212/free-hit/assets/74404894/cb94ac46-3fdf-4ab8-aefa-0d2001cc7471)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mukul314** [comment]
Hello @JasonDsouza212 , can I work on this under GSSOC'23 ?

**Comment by JasonDsouza212** [comment]
yes @mukul314

**Comment by mukul314** [comment]
Hello @JasonDsouza212 , actually I was a bit confused about something. By Section do you mean a new section in the website like footer, a new page or do you mean a new category in the tools.

Please help me out on this.

**Comment by Snigdha2712** [comment]
Please assign this issue to me. I would like to work on it. I will add contributing.md
