### ISSUE TITLE
Implement Pagination and Search Functionality in Website

### ISSUE THREAD

**Issue by manaver** [JasonDsouza212/free-hit#373]
The website lacks pagination and search functionality, leading to a suboptimal user experience. To address this, pagination needs to implement by dividing content into smaller pages with navigation controls. Additionally, we should add a search bar to enable users to find specific content quickly. 
This enhancement will significantly improve usability and user satisfaction.

Please Assign this issue to me. I'm a GSSOC'23 contributor

**Comment by JasonDsouza212** [comment]
You can start working on this @manaver

**Comment by manaver** [comment]
@JasonDsouza212  i am currently beasy for few days so i can't work on this issue I am unassigning this issue from me when I get free if the issue is not completed I will work on this issue

**Comment by kailashchoudhary11** [comment]
@JasonDsouza212 I can work on this.
