### ISSUE TITLE
[Feat]: Show Active Page on Navbar

### ISSUE THREAD

**Issue by kailashchoudhary11** [JasonDsouza212/free-hit#374]
### What feature?

We can add styling to show the active page. For example, if the user is on the about page, we can make the `About` link in navbar to have different styling that other links.

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JasonDsouza212** [comment]
Do you want to work on this @kailashchoudhary11 . Are you working under GSSOC23??

**Comment by kailashchoudhary11** [comment]
Hey @JasonDsouza212  yeah I would like to work on this. Also review #329  As well.

**Comment by JasonDsouza212** [comment]
You can only be assigned to other issues only after you finish both of the assigned issues

**Comment by kailashchoudhary11** [comment]
> You can only be assigned to other issues only after you finish both of the assigned issues

I've already made a PR for the other issue.
