### ISSUE TITLE
[Bug]: No Navigation for /community page.

### ISSUE THREAD

**Issue by kailashchoudhary11** [JasonDsouza212/free-hit#375]
### What happened?

The Community Link is not present in the Navbar. We can add a Link in Navbar so that the users can Navigate to /community.

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JasonDsouza212** [comment]
If needed, you can add it in the footer to avoid making the navbar lengthier.

**Comment by JasonDsouza212** [comment]
Since you are currently working on two issues, I can only assign this issue to you after you complete the earlier two issues.

**Comment by kailashchoudhary11** [comment]
> Since you are currently working on two issues, I can only assign this issue to you after you complete the earlier two issues.

I've already made a PR for all the assigned issues. You can assign other issues now
