### ISSUE TITLE
[Feat]: Select multiple filters at a time

### ISSUE THREAD

**Issue by kailashchoudhary11** [JasonDsouza212/free-hit#378]
### What feature?

We can allow the users to select multiple filters at a time.
As of now, the user can select any one of the available filters.

### Add screenshots

Add screenshots

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by JasonDsouza212** [comment]
That's a great feature! How do you plan on implementing it? @kailashchoudhary11

**Comment by kailashchoudhary11** [comment]
> That's a great feature! How do you plan on implementing it? @kailashchoudhary11

I'm thinking of using query params like, when the user clicks on a filter we'll append `?filter=filter1` to the URL and when user clicks on another filter we'll append it as well URL `?filter=filter1&filter=filter2`. Issue number #329 will set a base for this issue.
We can also implement is using useState hook but there is an issue with it. Once the user refreshes the page the filters will be removed. Even now when the user selects a particular filter and if he/she refreshes the page by mistake the filter will be gone.
Using search params will solve this issue as well.
