### ISSUE TITLE
[Bug]: Navbar responsiveness,

### ISSUE THREAD

**Issue by Singh-Vibhor** [JasonDsouza212/free-hit#379]
### What happened?

Bug in navbar appears for certain configurations.
I will like to fix it under GSSOC'23.

### Add screenshots

Add screenshots
![image](https://github.com/JasonDsouza212/free-hit/assets/69532057/538d35dd-e3ea-40b6-8f3b-5cafd4291dab)

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JasonDsouza212** [comment]
go ahead and work on it @Singh-Vibhor
