### ISSUE TITLE
[Feat]: Add a Signup and a Login Page 

### ISSUE THREAD

**Issue by Esha-01** [JasonDsouza212/free-hit#380]
### What feature?

I have an idea why not add a signup and login page feature that will collect the user information like name and email id. The main idea behind this is just to make the user updated with the latest features or links that get on added. in future. for this, I will be adding one sign-up button on the navbar that when clicked takes the user to the signup page if already a member the signup will have a sign-in link that will take to the sign-in page. 

### Add screenshots

Add screenshots
![signup](https://github.com/JasonDsouza212/free-hit/assets/98593600/f36de30d-64a3-43d2-a4c4-96217a0739f2)
![login](https://github.com/JasonDsouza212/free-hit/assets/98593600/58cfc3d0-bb79-41d0-9bad-5d4364ff5ded)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JasonDsouza212** [comment]
As of now, there is no Database, so how are you planning on implementing it @Esha-01

**Comment by JasonDsouza212** [comment]
are you working under Gssoc23?

**Comment by Esha-01** [comment]
yes i m working under Gssoc'23

**Comment by nandk4552** [comment]
I can implement login and signup and I can also implement CRUD operation to add tools using NodeJs, express, and MongoDB

Assign me under Gssoc'23

**Comment by JasonDsouza212** [comment]
As of now, we don't have a database, @nandk4552. So, I don't think it will be necessary for now. If we migrate to a database in the future, we will contact you.

**Comment by JasonDsouza212** [comment]
> As of now, there is no Database, so how are you planning on implementing it @Esha-01

can you answer this ??

**Comment by ruchagosavi** [comment]
@JasonDsouza212  Can u assign this to me I have done various sign up and login pages !!
