### ISSUE TITLE
[Feat]: Add a section 

### ISSUE THREAD

**Issue by Esha-01** [JasonDsouza212/free-hit#381]
### What feature?

I have an idea that I can add a section before the footer for subscribing to the website and get the email ids of the user of the website and update them with the latest news and new extension added to the website a new feature .after making the section I will make it responsive as well.

### Add screenshots

Add screenshots
![subscribe to the newsletter](https://github.com/JasonDsouza212/free-hit/assets/98593600/d53461bf-2ff2-4cbe-a4b2-f0e1229ed942)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JasonDsouza212** [comment]
are you working under Gssoc23 ??

**Comment by Esha-01** [comment]
yes
