### ISSUE TITLE
[Bug]:  About page is not completely responsive

### ISSUE THREAD

**Issue by ayushkumarbhadani** [JasonDsouza212/free-hit#382]
### What happened?

I found a BUG 🐞
The About page is not entirely responsive. An image is overflowing the screen causing the whole page to look smaller.

I can solve this issue, kindly assign this to me under GSSOC23 Label, please.

### Add screenshots

Add screenshots<img width="541" alt="Screenshot 2023-05-29 at 4 24 36 PM" src="https://github.com/JasonDsouza212/free-hit/assets/73775939/c7783c95-6d4f-427f-a380-cd71892fef60">

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JasonDsouza212** [comment]
As of now, someone is working on this issue. If he is unable to solve it, I will assign it to you, @ayushkumarbhadani.

**Comment by ayushkumarbhadani** [comment]
Hey @JasonDsouza212, it's been 5 days today and I still see this issue on the webpage. Kindly assign this issue to me as I want to work on it.
