### ISSUE TITLE
[Bug]: no space between cards and footer

### ISSUE THREAD

**Issue by VenomFate-619** [JasonDsouza212/free-hit#384]
### What happened?

I found that there is no space between contributor cards and the footer on the About page.
It is happening on 1440px width dimension 15inch laptop screen

### Add screenshots

![image](https://github.com/JasonDsouza212/free-hit/assets/67755128/b7adb13d-f10b-43e9-9555-fa3444474b00)

### What browsers are you seeing the problem on?

Brave

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JasonDsouza212** [comment]
I have already assigned this issue to someone. If they fail to resolve it, I will assign the issue to you.

**Comment by anjali29singh** [comment]
can you assign this issue to me?
