### ISSUE TITLE
[Feat]: Add a new tool to the list. {GSSoC '23} 

### ISSUE THREAD

**Issue by youraj-08** [JasonDsouza212/free-hit#386]
### What feature?

I want to add a free useful website to this list. 

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by khadesamrudhi** [comment]
please assign me this issue under GSSoC'23.

**Comment by youraj-08** [comment]
I want to work on this issue.
