### ISSUE TITLE
Add ABBYY FineReader in Home

### ISSUE THREAD

**Issue by rayarka26** [JasonDsouza212/free-hit#389]
### What feature?

ABBYY FineReader is an advanced OCR and PDF conversion tool. It uses AI and machine learning algorithms to accurately convert scanned PDFs and images into editable formats, including Word, Excel, and searchable PDFs.

### Add screenshots

Add screenshots

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by kedar1998** [comment]
Hey, I would like to work on  this issue. Can you please assign it to me under GSSOC'23

**Comment by rayarka26** [comment]
@JasonDsouza212 please assign me

**Comment by ruchagosavi** [comment]
@JasonDsouza212  I would like to work on this issue plz assign me!!
