### ISSUE TITLE
[Bug]: Clicking FREE-HIT logo redirects to about page not homepage

### ISSUE THREAD

**Issue by kartikjoshi267** [JasonDsouza212/free-hit#390]
### What happened?

When we click on the FREE-HIT logo, it redirects to the about page. Instead, it should redirect to the homepage.
Can you assign me this issue under GSSOC'23?

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JasonDsouza212** [comment]
@kartikjoshi267, it was intentionally made that way because in the mobile view, we don't have an "About" button. So, we added it to the logo. Additionally, when someone clicks on the logo, it is usually to know more about the website.

**Comment by kartikjoshi267** [comment]
@JasonDsouza212 Ok then I can add About, Bookmark, etc. options available on mobile devices also.

**Comment by JasonDsouza212** [comment]
@kartikjoshi267 where are you planning to add it ?
