### ISSUE TITLE
[Feat]: Add a new tool to the website

### ISSUE THREAD

**Issue by mukul314** [JasonDsouza212/free-hit#392]
### What feature?

I would like to add a new tool to this website, which will be a tool for paraphrasing. This will be very valuable to the website's resources.

@JasonDsouza212 , I'd like to work on this under GSSOC'23 if you approve.

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JasonDsouza212** [comment]
you can start working on this @mukul314
