### ISSUE TITLE
[Bug]: Missing logos on some of the tools

### ISSUE THREAD

**Issue by mukul314** [JasonDsouza212/free-hit#393]
### What happened?

There are some tools such as ChaiJs, Chatgptwriter that do not have the corresponding logos with them, see the below image for more reference:

<img width="236" alt="2023-05-30 11_32_23-FREE-HIT - Brave" src="https://github.com/JasonDsouza212/free-hit/assets/76463001/da7f7c48-13c3-4800-ba93-a05cf366b1c7">

<img width="236" alt="2023-05-30 11_32_18-FREE-HIT - Brave" src="https://github.com/JasonDsouza212/free-hit/assets/76463001/78421de6-a97f-4650-b48c-00d1e0d824ea">

And there are some tools that do not have a logo at all like Linkedin, hackthebox .

<img width="197" alt="2023-05-30 11_01_36-FREE-HIT - Brave" src="https://github.com/JasonDsouza212/free-hit/assets/76463001/ea09cf17-fc3d-4c8d-a810-83d390bbf2ba">

<img width="208" alt="2023-05-30 11_01_53-FREE-HIT - Brave" src="https://github.com/JasonDsouza212/free-hit/assets/76463001/6c6074b3-9eb8-4604-b6d3-06e0b49ec71c">

@JasonDsouza212 , I'd like to work on this issue under GSSOC'23 if you approve!!

### What browsers are you seeing the problem on?

I checked this on google and firefox there the logos are showing, but the logos are not visible in Brave browser.

### Code of Conduct

- [ x] I agree to follow this project's Code of Conduct

**Comment by JasonDsouza212** [comment]
you can start working on this @mukul314

**Comment by Prajwal1110** [comment]
Could you Please assign this work under GSSOC@23
