### ISSUE TITLE
Add Category UI/UX Tools

### ISSUE THREAD

**Issue by kritriv** [JasonDsouza212/free-hit#395]
### What feature?

Hello, Vishal Saraiwal this side I am a React Developer and a UI/Ux Designer
Can we add UI/UX category to separate UI/UX Tools as I have a lot of UI/UX Tools and helpful UI Kits.
So As a Part of GSSoc Contributor, can you assign this to me ?? @johnsonAyo @Fiddler46 @shobhitexe @jaydeepkhatri @sangdeepganvir @ 
Thanks  let me know

### Add screenshots

<img width="960" alt="image" src="https://github.com/JasonDsouza212/free-hit/assets/71539186/eac231d2-adf8-4157-8c11-c80055dfdcfb">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JasonDsouza212** [comment]
@kritriv  Yes, you can add it, but the category should contain more than 8 tools. Only then can we consider it as a category.
