### ISSUE TITLE
[Feat]: Adding favicon.cc website to free-hit

### ISSUE THREAD

**Issue by Prajwal0225** [JasonDsouza212/free-hit#398]
### What feature?

Favicon.cc is a website that allows users to create and customize favicon icons for their websites. It provides a simple and intuitive interface to design and generate favicon images in various formats.

### Add screenshots

**Add screenshots**
![favicon](https://github.com/JasonDsouza212/free-hit/assets/103810119/064db779-bd77-4f26-84f6-aabf4d434061)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Prajwal0225** [comment]
Please assign this issue to me so that I can contribute to your amazing project 😇

**Comment by JasonDsouza212** [comment]
@Prajwal0225 are you working under gssoc23

**Comment by KamalSritha-04** [comment]
Can you please assign me this issue under GSSOC'23?

**Comment by Prajwal0225** [comment]
Yes I am working under GSSOC
