### ISSUE TITLE
[Feat]: Add glassdoor and cuvete in remote jobs

### ISSUE THREAD

**Issue by sumitkr2000** [JasonDsouza212/free-hit#407]
### What feature?

I have an idea to add glassdoor and cuvette in remote jobs. Please assign me this issue. Thank you!

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JasonDsouza212** [comment]
Cuvette is a remote job offering platform, so you can add it. However, I am not sure if Glassdoor is a remote job platform. Are you working under GSSoC?

**Comment by sumitkr2000** [comment]
Yea i am working under gssoc.
I'll add cuvete to the list.
