### ISSUE TITLE
[Feat]: Adding Unlighthouse , regexr to useful tools

### ISSUE THREAD

**Issue by USERSATOSHI** [JasonDsouza212/free-hit#408]
### What feature?

I would like to add [Unlighthouse](https://unlighthouse.dev) and [regexr](https://regexr.com) to useful tools section

Unlighthouse generate google lighthouse reports for all routes at same time 

Regexr is a site to test and build regular expressions

I would like to contribute this under GSSOC23 

### Add screenshots

![image](https://github.com/JasonDsouza212/free-hit/assets/73595362/4f9497bf-bbb8-4fb4-808f-220db9534182)

![image](https://github.com/JasonDsouza212/free-hit/assets/73595362/cf38207d-4a0a-4281-8556-9f3aef4d47bf)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JasonDsouza212** [comment]
You can add it only if the mentioned platforms are free to use.

**Comment by USERSATOSHI** [comment]
> You can add it only if the mentioned platforms are free to use.

Yes, they are free to use

**Comment by USERSATOSHI** [comment]
thx for assigning me 😊
