### ISSUE TITLE
[style]: Ui of the about page

### ISSUE THREAD

**Issue by Pragati-3003** [JasonDsouza212/free-hit#409]
### What's the style idea?

I would like to improve the ui of the home page by changing background color and adding box shadows.
So,please assign this to me under GSSOC'23.

### Add screenshots

![Screenshot 2023-05-31 153034](https://github.com/JasonDsouza212/free-hit/assets/132778037/5a7d1d2d-cadd-49f0-acb0-a45a274c37dc)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JasonDsouza212** [comment]
I don't think changing the background is necessary, but you can work on enhancing the UI of the About page. If the results are good, we can merge it.

**Comment by Pragati-3003** [comment]
> I don't think changing the background is necessary, but you can work on enhancing the UI of the About page. If the results are good, we can merge it.

Thanks for assigning me.

**Comment by akanksha984** [comment]
Please assign it to me under gssoc'23. I want to work on this issue
