### ISSUE TITLE
[Feat]: Restructure the codebase.

### ISSUE THREAD

**Issue by kailashchoudhary11** [JasonDsouza212/free-hit#410]
### What feature?

The current codebase is difficult to read and understand. We can improve this by separating components and functions into different files and folders.

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by NNL-Keerthana** [comment]
Hi! I would like to work on this issue as a part of GSSOC'23.
Please assign this to me. I shall start working on it right away!
