### ISSUE TITLE
[Feat]: Adding a new section for research tools

### ISSUE THREAD

**Issue by randiepathirage** [JasonDsouza212/free-hit#411]
### What feature?

I have an idea to add a new section dedicated to research tools on your platform. This section would provide a collection of websites and tools that can be extremely helpful for researchers during their research process. Here are some suggestions for the tools and websites to include:

[Mendeley ](https://www.mendeley.com/)and [Zotero](https://www.zotero.org/): These are reference management tools that help researchers organize and manage their citations, references, and documents.

[Papers with Code](https://paperswithcode.com/) and [Hugging Face](https://huggingface.co/): These platforms provide resources for researchers interested in the field of machine learning and artificial intelligence. Papers with Code offers a collection of research papers along with their corresponding code implementations, while Hugging Face provides various natural language processing models and tools.

[Google Scholar](https://scholar.google.com/): This widely-used academic search engine allows researchers to find scholarly articles across different disciplines. It also provides options to save and organize research papers.

[Sci-Hub](https://www.sci-hub.se/): While controversial, Sci-Hub is a website that provides free access to academic articles, making it a valuable resource for researchers who may not have access to certain journals or papers.

[Connected Papers](https://www.connectedpapers.com/): This tool visualizes research papers and their connections, helping researchers discover related works and explore new avenues of research.

[Overleaf](https://www.overleaf.com/): Overleaf is an online collaborative writing and publishing tool that simplifies the process of creating scientific documents, including research papers and reports. It offers a real-time collaboration feature, making it easier for researchers to work together on documents.

These tools and websites can greatly enhance the research experience and productivity of academics and scientists.

I would like to contribute to this under GSSOC23. Could you please assign me?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JasonDsouza212** [comment]
Are all the tools free? Additionally, the research section should include a minimum of 8 tools. Could you also specify the type of research we are discussing?

**Comment by randiepathirage** [comment]
Yes, all these tools are free and I have used them for my research.

1. [Mendeley ](https://www.mendeley.com/)
2.  [Zotero](https://www.zotero.org/)
3. [Papers with Code](https://paperswithcode.com/) 
4.  [Hugging Face](https://huggingface.co/)
5. [Google Scholar](https://scholar.google.com/)
6. [Sci-Hub](https://www.sci-hub.se/)
7. [Connected Papers](https://www.connectedpapers.com/)
8. [Overleaf](https://www.overleaf.com/)

I can add these 8 tools and websites. These can be used in any type of research to read research papers , citation, documentation etc.
