### ISSUE TITLE
[Docs]: Grammatical and Spelling Errors in README.md File

### ISSUE THREAD

**Issue by randiepathirage** [JasonDsouza212/free-hit#412]
### what's wrong in the documentation?

I noticed that there are some grammatical and spelling errors in the README.md file, and I would like to contribute to fixing them as part of GSSOC23. Could you please assign me this task?

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Janvi-Sungroya** [comment]
I want to work on this issue . Plz assign me with this

**Comment by Snigdha2712** [comment]
Please assign this issue to me. I would like to work on it
