### ISSUE TITLE
[Feat]: Adding a category section

### ISSUE THREAD

**Issue by RashakDude** [JasonDsouza212/free-hit#414]
### What feature?

I wanted to add some category sections for the websites. 

It can be implemented by adding some tags to each card. Then assigning each card into each category. 

This category will be in the top bar for better user experience.

### Add screenshots

Will add screenshots after implementing it. Kindly assign it to me.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by RashakDude** [comment]
@JasonDsouza212 Oh okay. I didn't see it. Bad user experience I guess. Can we make it in the upper section only for better user experience and add tags as mentioned in the side column with the corresponding cards.

**Comment by JasonDsouza212** [comment]
We had that feature earlier, but as the number of tags increases, it takes up a lot of space. So, I think it's better this way. @RashakDude, I apologize for the delayed response. If you would like to discuss further, please feel free to contact me through Twitter. As the issue grows, it becomes challenging to keep track of the messages.
