### ISSUE TITLE
[style]: Improving the UI of the error page

### ISSUE THREAD

**Issue by Google-Ka-Dinosaur** [JasonDsouza212/free-hit#417]
### What's the style idea?

We need to improve  the error page by adding a suitable image that matches with the theme. also there seems to be a bit of white space under the footer in my device.  Kindly assign me the issue so that I can work on fixing it. 
![Screenshot (198)](https://github.com/JasonDsouza212/free-hit/assets/98577878/2e24efa7-ad32-4296-ac7d-e424d348d209)

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by abhinav-m22** [comment]
@JasonDsouza212 Can I work on this issue?
Please assign me!

**Comment by JasonDsouza212** [comment]
@abhinav-m22, the issue has been resolved, but there is a small bug remaining. Do you want to work on it?

**Comment by abhinav-m22** [comment]
Yes I am ready to work on it.... What is the bug?
