### ISSUE TITLE
[Bug]: Home Button Not Working in Both Navbar and Main Home button

### ISSUE THREAD

**Issue by kumar007ambi** [JasonDsouza212/free-hit#418]
### What happened?

I found a BUG 🐞

### Add screenshots

Add screenshots
![HomeButtonIssue](https://github.com/JasonDsouza212/free-hit/assets/60788663/27436cfc-2463-4342-b90c-f497cd33508b)
After Clicking in Navabar as well as Main Home button not redirecting to home page

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kumar007ambi** [comment]
Chrome (latest version)

**Comment by JasonDsouza212** [comment]
What page are you expecting it to navigate when clicked on home button @kumar007ambi

**Comment by kumar007ambi** [comment]
Basically when we click home button it redirect to home page.For example I click Remote Jobs then Its showing it related content,
but after clicking home the page remain same as where it was like remote jobs.

**Comment by kumar007ambi** [comment]
@JasonDsouza212 Have you checked this issue

**Comment by youngancient** [comment]
Hey @JasonDsouza212 I would like to work on this issue! There's probably an issue with the routing. I would like to work on this issue!

**Comment by youngancient** [comment]
Hi, @kumar007ambi do you mind shedding more light on the bug? I am glancing through the codebase and testing the web app to figure out where the bug you spotted is but I can't. After searching, the home buttons work. @JasonDsouza212 any insight on this?
