### ISSUE TITLE
Grid view and list view

### ISSUE THREAD

**Issue by JasonDsouza212** [JasonDsouza212/free-hit#42]
We can create two types of views, such as **grid view** and **list view**. The user can use whichever view he feels comfortable with

**Comment by himanshukrmr** [comment]
Hi, @JasonDsouza212 mayI try this?

**Comment by JasonDsouza212** [comment]
ok @himanshukrmr go ahead and work on it

**Comment by Bharadwajshivam28** [comment]
@JasonDsouza212 Can i get assigned and work on it

**Comment by himanshukrmr** [comment]
> ok @himanshukrmr go ahead and work on it

Hi @JasonDsouza212 I am not getting time to work on this please assign to someone else

**Comment by JasonDsouza212** [comment]
OK @himanshukrmr

**Comment by AbhayaShankar** [comment]
I am willing to work on that !

**Comment by JasonDsouza212** [comment]
@AbhayaShankar go ahead and work on it

**Comment by AbhayaShankar** [comment]
@JasonDsouza212 Created a pull request for this now along with other changes. In depth mentioned what changes were made. Check them out.
