### ISSUE TITLE
[Bug]: Website too slow at starting 

### ISSUE THREAD

**Issue by programerr01** [JasonDsouza212/free-hit#421]
### What happened?

Given the size of `/src/DB/product.json`, it's making site very slow because of all the data/images it has to fetch.

## Solution 
We will have to implement pagination. By incorporating pagination, we can efficiently manage and present data in smaller, manageable chunks, reducing the strain on resources and enhancing overall performance

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JasonDsouza212** [comment]
he issue already exists. Would you like to work on the pagination?

**Comment by programerr01** [comment]
@JasonDsouza212 yes, I can work on it

**Comment by JasonDsouza212** [comment]
There are multiple people working on it, but no one has given any updates on this. Whoever creates the PR with no bugs, I'll merge it. To make things easier, there is a branch called '**pagination**' that you can use to build the pagination. It has all the functionality related to the feature, but there is a small bug regarding the search. You can take care of it and then make a pull request.

**Comment by JasonDsouza212** [comment]
are you working under Gssoc23

**Comment by JasonDsouza212** [comment]
Are all the tools free? Additionally, the research section should include a minimum of 8 tools. Could you also specify the type of research we are discussing?
