### ISSUE TITLE
[Bug]: SideBar not closing after category selection

### ISSUE THREAD

**Issue by arin-paliwal** [JasonDsouza212/free-hit#422]
### Description
Currently, the sidebar remains open even after selecting a category from the list. This behavior can be improved to provide a better user experience by automatically closing the sidebar when a category is selected.

### Steps to Reproduce
1. Open the application and navigate to the sidebar.
2. Click on any category from the list.

### Expected Behavior
After selecting a category, the sidebar should automatically close, allowing the user to focus on the selected category's content.

### Possible Solution
1. Identify the event handler or function that is triggered when a category is selected.
2. Implement the necessary logic within the event handler or function to close the sidebar. This can be achieved by setting the 'checked' property of the sidebar toggle to false.

## Resolved !
https://github.com/JasonDsouza212/free-hit/assets/100232893/369537f9-5f20-41cf-929d-ed9a4b7cf418

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JasonDsouza212** [comment]
Do you want to work in this

**Comment by arin-paliwal** [comment]
> Do you want to work in this

Yes
