### ISSUE TITLE
[Feat]: Adding Dark mode to the website.

### ISSUE THREAD

**Issue by raghav1482** [JasonDsouza212/free-hit#425]
### What feature?

Adding dark mode in the website would enhance the attractiveness

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by raghav1482** [comment]
@JasonDsouza212 Kindly assign me this issue #425 under GSSOC 2023

**Comment by JasonDsouza212** [comment]
This issue is a duplicate and has already been assigned to someone. If they fail to resolve it, you will be assigned to handle it.
