### ISSUE TITLE
Cursor is changed to pointer during hover on cards

### ISSUE THREAD

**Issue by reny-pacheco** [JasonDsouza212/free-hit#43]
When hovering over a card, the cursor changes to a pointer, giving the impression that the card is clickable. However, clicking on the card does not result in any action. This can lead to confusion and frustration for users who expect to be able to interact with the card. I suggest to either make the card clickable or change the cursor back to its default state when hovering over a non-clickable card to avoid any confusion for users.

**Comment by JasonDsouza212** [comment]
Ya thats a good point, Do you want to work on this

**Comment by reny-pacheco** [comment]
Yes, Thank you

**Comment by reny-pacheco** [comment]
@JasonDsouza212 Please assign this to me, Thanks 😄
