### ISSUE TITLE
[Feat]: Add Flex Jobs,Remote Work mate,FindAsync and Few more remote Job portals to remote Jobs

### ISSUE THREAD

**Issue by kumar007ambi** [JasonDsouza212/free-hit#433]
### What feature?

I am under GSSOC23 and I have an idea to add Flex Jobs,Remote Work mate,FindAsync and Few more remote Job portals to remote Jobs.

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JasonDsouza212** [comment]
Go ahead and add it.
