### ISSUE TITLE
Add CodeQL workflow

### ISSUE THREAD

**Issue by metabiswadeep** [JasonDsouza212/free-hit#435]
Add the codeql semantic analysis workflow for the repo to be enabled on every push, commit and pull request using GitHub actions.

I want to work on this issue as a part of GSSoc'23. Please assign this issue to me.

**Comment by JasonDsouza212** [comment]
What will the workflow do?

**Comment by metabiswadeep** [comment]
CodeQL scans the repo for security vulnerabilities, allowing you to find potential vulnerabilities in your code with greater confidence than traditional static analyzers like coverity.

**Comment by metabiswadeep** [comment]
@JasonDsouza212
