### ISSUE TITLE
Showing on the searched object as a result

### ISSUE THREAD

**Issue by mukul314** [JasonDsouza212/free-hit#439]
Currently when we search something on the website , for example linkedin then after typing it completely still some other results show beside it. I guess if a user has completely typed a query then only that query should appear.

See the below image:
<img width="658" alt="2023-06-02 08_50_55-FREE-HIT - Brave" src="https://github.com/JasonDsouza212/free-hit/assets/76463001/f7254ae7-affb-436c-a284-5f2ad0592771">

In the above image Linksave is still visible even after linkedin is searched. I'd like to work on this issue @JasonDsouza212 , if you approve.

**Comment by Visbhavesh** [comment]
please assign it to me and I will complete by tonight

**Comment by JasonDsouza212** [comment]
@mukul314 Do you want to work on this, and are you working under GSSOC23?

**Comment by JasonDsouza212** [comment]
> Please assign it to me and I will complete by tonight

If @mukul314 refuses to do You will be assigned

**Comment by mukul314** [comment]
> @mukul314 Do you want to work on this, and are you working under GSSOC23?

yes @JasonDsouza212 !!
