### ISSUE TITLE
[Feat]: adding new tool

### ISSUE THREAD

**Issue by Hypertext-Workaholics** [JasonDsouza212/free-hit#442]
### What feature?

I have an idea 

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Visbhavesh** [comment]
please assign it to me and I will complete by tonight

**Comment by JasonDsouza212** [comment]
are you working under GSSOC23

**Comment by Hypertext-Workaholics** [comment]
> are you working under GSSOC23

yes

**Comment by maithrivh** [comment]
How to start with a contribution? Would you be able to support?

**Comment by KaKashi1210** [comment]
is this assigned ?
