### ISSUE TITLE
[Feat]: Pagination

### ISSUE THREAD

**Issue by Harshu467** [JasonDsouza212/free-hit#448]
### What feature?

There should be Pagination feature 

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JasonDsouza212** [comment]
This is a duplicate issue. Someone is currently working on it. If they are unable to resolve it, you will be assigned to handle it.

**Comment by Harshu467** [comment]
@JasonDsouza212 I did not see any other issue similar to it , Can u please share it ? Please Assign it to me
