### ISSUE TITLE
Change name from product.js to product.json

### ISSUE THREAD

**Issue by priyankarpal** [JasonDsouza212/free-hit#45]
- change the name to product.json
- Format json code.  remove `,` after `description` 

![image](https://user-images.githubusercontent.com/88102392/227697714-315f336a-1691-48c9-ab0a-89bae39ebe44.png)

![Screenshot from 2023-03-25 10-41-36](https://user-images.githubusercontent.com/88102392/227697763-b0ffe8c2-01d4-4a19-b8e9-cf6743ffc24e.png)

**Comment by JasonDsouza212** [comment]
Do you want to work on this?

**Comment by sushilpandeyy** [comment]
@JasonDsouza212 I am working on this

**Comment by sushilpandeyy** [comment]
#47 Created Pull Request please check
