### ISSUE TITLE
[Feat]: a contact form for users to suggest free tools

### ISSUE THREAD

**Issue by Arjyahi** [JasonDsouza212/free-hit#455]
### What feature?

A contact form where users can provide names and links of tools that they think might be a valuable addition to the existing list. That way the community will be more open to users and their opinions. They can also let us know if any of the free tools listed on the website have now become paid or not so that we can remove those from the list.

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JasonDsouza212** [comment]
How do you plan to implement it, @Arjyahi? Are you working under GSSOC23?

**Comment by kailashchoudhary11** [comment]
I think we need backend for this to work.

**Comment by Arjyahi** [comment]
@JasonDsouza212 We could create a new component for the contact form, which will contain the necessary form fields for users to enter their names, tool suggestions, and other information. Then, we can implement a form submission handler in the contact form component, to capture the form inputs and send them to the server for processing. In the server-side endpoint, we retrieve the form data sent from the React front end. Also, we need to validate and sanitize the data to ensure it is safe and meets the required criteria. For the backend, we can set up a server, and a database, and as an optional feature, we can implement email notifications as well. I am open to suggestions too, in order to make the process simpler and smoother.

And yes, I am working under GSSOC'23.
