### ISSUE TITLE
[style]: Font change

### ISSUE THREAD

**Issue by kartikkc** [JasonDsouza212/free-hit#457]
### What's the style idea?

I'm from GSSOC'23 and I noticed that the font of the website is really primitive, and 

We need to improve the font of the website. Changes in the font will give the website a new look and it will complete the theme of the website. 

Assign me this issue, I would like to work on this issue.

### Add screenshots

Screenshot

this font can be improved.

![font-improvement](https://github.com/JasonDsouza212/free-hit/assets/63699242/198384d2-3be1-48ba-9ee7-f2b93715cdff)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Snigdha2712** [comment]
Please assign this project to me. i will fix the issue

**Comment by JasonDsouza212** [comment]
@kartikkc you can start working on this

**Comment by JasonDsouza212** [comment]
> Please assign this project to me. I will fix the issue

If @kartikkc fails to do it in a week , You will be next to be assigned

**Comment by Snigdha2712** [comment]
what about this project? please assign it to me under gssoc23
