### ISSUE TITLE
[Feat]: Clean the App component.

### ISSUE THREAD

**Issue by kailashchoudhary11** [JasonDsouza212/free-hit#460]
### What feature?

We can clean the App component and move the attributes and functions related to Home Page into the Home component and those related to the Bookmarks Page into Bookmark Component. The App component will just contain the Routes.

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JasonDsouza212** [comment]
Do you want to work on this
