### ISSUE TITLE
[Feat]: Adding Loader

### ISSUE THREAD

**Issue by kailashchoudhary11** [JasonDsouza212/free-hit#461]
### What feature?

We can show a loader to the user whenver the user changes the pages and when the website loads for the first time.

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JasonDsouza212** [comment]
You can work on this after completing the previously assigned issue.

**Comment by ruchagosavi** [comment]
I would like to work on this issue plz assign me!! @JasonDsouza212
