### ISSUE TITLE
[Bug]: Duplicate tool in the website

### ISSUE THREAD

**Issue by mukul314** [JasonDsouza212/free-hit#464]
### What happened?

I found a BUG 🐞
I was searching for some tools in the website and found that there is a duplicate tool in the webiste by the name of "futurepedia".

One of them must be removed.

### Add screenshots

<img width="699" alt="2023-06-03 11_53_35-FREE-HIT - Brave" src="https://github.com/JasonDsouza212/free-hit/assets/76463001/d9dc9d9e-dbd0-4179-9d57-12785fbae996">

I'd like to work on this issue under GSSOC'23, @JasonDsouza212 .

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JasonDsouza212** [comment]
@mukul314 you can start working on this
