### ISSUE TITLE
[Feat]: List view in the Bookmarks section too

### ISSUE THREAD

**Issue by mukul314** [JasonDsouza212/free-hit#465]
### What feature?

I have an idea 

Since we have a list as well as grid view in the tools section, I think that the list view should also be available in the saved bookmarks section. Currently the saved bookmarks can only be viewed in the grid view.

I'd like to work on this @JasonDsouza212 .

### Add screenshots

Add screenshots

### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

**Comment by JasonDsouza212** [comment]
After completing the previously assigned issue, please DM me. I will then assign you the next task.

**Comment by ruchagosavi** [comment]
I would like to work on this issue plz assign me!! @JasonDsouza212

**Comment by mukul314** [comment]
So can start working on this @JasonDsouza212 ?

**Comment by mukul314** [comment]
@JasonDsouza212 , can you assign it to me? So that I can start working on it.
