### ISSUE TITLE
[style]: Search Icon's CSS Modification [GsSOC'23]

### ISSUE THREAD

**Issue by Monilprajapati** [JasonDsouza212/free-hit#470]
## Before :
![image](https://github.com/JasonDsouza212/free-hit/assets/99136041/61f6f10b-4db7-4f23-ab79-17531bb79187)

## After Changes : 
![image](https://github.com/JasonDsouza212/free-hit/assets/99136041/5ad6f898-995f-4cba-9a11-e077b28f0625)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by shadwar123** [comment]
Hey @Monilprajapati  I'm interested in working on the issue. Assign Me Please.

**Comment by JasonDsouza212** [comment]
@Monilprajapati sorry for not looking into the issue. I think this issue is being solved so I think we don't need this feature anymore. Once again sorry for not replying
