### ISSUE TITLE
[style]: change the hover and animation effect on footer buttons

### ISSUE THREAD

**Issue by AmanSingh6574** [JasonDsouza212/free-hit#472]
### What's the style idea?

on hover to any buttons all the colour are same need to change the colour according to their og one

@JasonDsouza212 

### Add screenshots

![image](https://github.com/JasonDsouza212/free-hit/assets/113782984/04a0ea1c-be78-480f-ab75-51c27d4a5c0b)
![image](https://github.com/JasonDsouza212/free-hit/assets/113782984/226413dd-479f-4735-889d-26ddfefb56a9)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
pls Assign this issue under GSSOC23

**Comment by JasonDsouza212** [comment]
@AmanSingh6574 you can start working on this
