### ISSUE TITLE
[Feat]: Improve the NotFound page.

### ISSUE THREAD

**Issue by kailashchoudhary11** [JasonDsouza212/free-hit#482]
### What feature?

The sidebar should be changed for the NotFound page.
Also, we can improve the error message and provide the link to home page.

### Add screenshots

Add screenshots

### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

**Comment by Shahil093** [comment]
Assign me this project issue

**Comment by JasonDsouza212** [comment]
@whizzy23  is this pithambar

**Comment by whizzy23** [comment]
yes @JasonDsouza212 thanks for assigning this issue to me .
