### ISSUE TITLE
[Feat]: Create Sidebar component

### ISSUE THREAD

**Issue by kailashchoudhary11** [JasonDsouza212/free-hit#484]
### What feature?

We can create a seperate component for Sidebar instead of putting all the code inside the Navbar component. It is creating a mess, we can clean the code.

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by codin-AWMKAR** [comment]
Please Assign Me this Issue I have added similar features in my portfolio website.
