### ISSUE TITLE
[Bug]: The footer is not fixed at the bottom.

### ISSUE THREAD

**Issue by kailashchoudhary11** [JasonDsouza212/free-hit#486]
### What happened?

The footer should stick to the bottom of the page even when there is not enough content on the page.

### Add screenshots

![image](https://github.com/JasonDsouza212/free-hit/assets/75559082/8d9329c4-7f12-49df-96b3-188faa6304d4)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Anjali1822** [comment]
I would like to work on this issue plz assign me !! @JasonDsouza212
