### ISSUE TITLE
[style]: Make the bookmarks page of greater size when no bookmarks are in sight so that the footer is not visible on on initial load 

### ISSUE THREAD

**Issue by rhithesh** [JasonDsouza212/free-hit#488]
### What's the style idea?

setting minheight

### Add screenshots

Add screenshots
![image](https://github.com/JasonDsouza212/free-hit/assets/115660976/061ac7c4-4072-46d1-aa9c-fbdb5fc14c94)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by rawasaditya** [comment]
Assign this to me I have a solution for this, this issue is not limited to bookmark page. I persist on other pages too. Assign it to me so that I can contribute

**Comment by JasonDsouza212** [comment]
@rhithesh , do you want work on this under gssoc23

**Comment by rhithesh** [comment]
Yes @JasonDsouza212
