### ISSUE TITLE
Addition of stars or clicks for each product[Feat]: 

### ISSUE THREAD

**Issue by Manikantan-S** [JasonDsouza212/free-hit#492]
### What feature?

I have an idea 
We can add stars for each product, which will enable users to choose the best product for the purpose that they require andwill help in easy comparison 
like under this I have added screenshot where 3 products are competing in the same market space if we give each of them a rating then it will make the website user friendly. Please assign me this issue and allow me to work on it 
![image](https://github.com/JasonDsouza212/free-hit/assets/111214511/8c0b4444-a4e9-4edc-a70f-69f9cf9f7a90)

**Comment by Manikantan-S** [comment]
So am I assigned?

**Comment by kailashchoudhary11** [comment]
> So am I assigned?

Not yet, The project admin will assign to you.

**Comment by JasonDsouza212** [comment]
As there is no DB , what purpose will this achieve @Manikantan-S

**Comment by Manikantan-S** [comment]
It will achieve the following things:
1)User Feedback: Ratings help users make informed decisions about resources based on user opinions.
2)User Engagement: Incorporating ratings encourages active user participation, fostering a vibrant community.
3)Continuous Improvement: Ratings provide insights for website owners to enhance user experience and guide future resource development.
Moreover this will also give the most recommended websites for the required purpose and ensure that they go that website and it fulfills it

**Comment by JasonDsouza212** [comment]
But there is no data base to store the user data

**Comment by Manikantan-S** [comment]
I feel that we can use:
Coookies :they have to be updated regularly
or
Session storage API: This will save the data in user side
or 
Local Storage API

**Comment by JasonDsouza212** [comment]
I Don't think it's gonna server any purpose

**Comment by Manikantan-S** [comment]
ok
