### ISSUE TITLE
[style]: I want to improve the UI of icons 

### ISSUE THREAD

**Issue by Hardikaz** [JasonDsouza212/free-hit#498]
### What's the style idea?

# I want to change the UI of these icons
 1  These icons for display
![image](https://github.com/JasonDsouza212/free-hit/assets/95474096/1d8b08bc-1440-4c3b-b187-733a1c1c2ca2)
2  These icons for links to other accounts 
![image](https://github.com/JasonDsouza212/free-hit/assets/95474096/e4e90d1d-a48a-4305-b609-4d550a85a946)

### Add screenshots

# I will convert them like this with some animations like this
![image](https://github.com/JasonDsouza212/free-hit/assets/95474096/d83a90ef-4b02-4ca4-9f8c-01013562381d)

Please assign me this work as I m in GSSOC ' 23.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JasonDsouza212** [comment]
You can give it a try  @Hardikaz

**Comment by Hardikaz** [comment]
Sure sir I will do it under GSSOC'23

**Comment by akanksha984** [comment]
Please assign it to me under gssoc'23. I want to work on this issue

**Comment by Muskan1009** [comment]
Assign it to me i am an experiences designer

**Comment by Poisonlocket** [comment]
Is this issue currently being worked on? it seems to have gone inactive. If so, i'd like to take over to make my first contribution.

**Comment by JasonDsouza212** [comment]
@Poisonlocket It would be great if you resolve this issue

**Comment by Poisonlocket** [comment]
> @Poisonlocket It would be great if you resolve this issue

No Problem, im on it, do you have a deadline?

**Comment by Poisonlocket** [comment]
Is there a style that needs to be achieved or am i free in Design?

**Comment by JasonDsouza212** [comment]
@Poisonlocket , try matching same design pattern and there is no deadline take your time
