### ISSUE TITLE
[Feat]: Wanted to add cssbattle website 

### ISSUE THREAD

**Issue by Prajwal0225** [JasonDsouza212/free-hit#499]
### What feature?

CSS Battle is a platform that provides a unique and interactive way to improve your CSS skills through challenges and battles. It offers a collection of creative and visually appealing design puzzles that require you to recreate a specific design using only HTML and CSS.

### Add screenshots

Add screenshots
![css battle](https://github.com/JasonDsouza212/free-hit/assets/103810119/b540ecaa-975e-48cf-865f-78fac96ad28a)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JasonDsouza212** [comment]
Go ahead and add it @Prajwal0225
