### ISSUE TITLE
[style]: UI enhancement of cards

### ISSUE THREAD

**Issue by Pranav-Rustagi** [JasonDsouza212/free-hit#501]
### What's the style idea?

The present UI of cards does not seem very clean as the descriptions and corresponding logos of tools do not have much separation. Also, the center alignment of the description content decreased the readability of the description context. 

### Add screenshots

![image](https://github.com/JasonDsouza212/free-hit/assets/57594891/6e6c471a-1552-47f9-aa9e-e23aef2993c6)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Pranav-Rustagi** [comment]
@JasonDsouza212 @VenomFate-619 Kindly assign this issue to me under GSSOC

**Comment by JasonDsouza212** [comment]
@Pranav-Rustagi , go ahead and do it

**Comment by rahulrana701** [comment]
here is the screenshot @JasonDsouza212 @VenomFate-619 
<img width="953" alt="Screenshot 2023-06-07 120226" src="https://github.com/JasonDsouza212/free-hit/assets/123585591/34c5c560-593f-401b-a3e5-bea4abe9ce9c">

**Comment by rahulrana701** [comment]
@Pranav-Rustagi I have already solved the issue brother..

**Comment by rahulrana701** [comment]
Don't know what is going on in this program @JasonDsouza212 @VenomFate-619 i was the one who assigned this issue first and I have already created a pr and submitted it and it was approved as well and this was a duplicate issue and you merged his pr great work

**Comment by JasonDsouza212** [comment]
@rahulrana701 Sorry mate , I really thought I had merged your PR . See as there are many PRs present some times we get confused and this happens. Can you ping me the PR number so that I can look into it ,also keep in touch with through discord or Twitter
