### ISSUE TITLE
[style]: Active view for cards

### ISSUE THREAD

**Issue by Pranav-Rustagi** [JasonDsouza212/free-hit#502]
### What's the style idea?

From the attached screenshots, we can't tell whether the box view is active or the tile view. This can be improved.

### Add screenshots

![image](https://github.com/JasonDsouza212/free-hit/assets/57594891/8a1097aa-d48d-409c-975d-f468bb5bee5c)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Pranav-Rustagi** [comment]
@JasonDsouza212 @VenomFate-619 Kindly assign this issue to me under GSSOC

**Comment by VenomFate-619** [comment]
How your gonna fix this? 
give some idea, has this is related to UI do  provide some design or image
