### ISSUE TITLE
[Bug]: The slide bar in the about page is entirely black and unreadable. [GSSoC'23]

### ISSUE THREAD

**Issue by 1Shubham7** [JasonDsouza212/free-hit#505]
### What happened?

I found a BUG 🐞
In the about page of the website, when you open the slide bar. The slide bar is entirely black and unreadable.

### Add screenshots

![slidebarissue](https://github.com/JasonDsouza212/free-hit/assets/116020663/83d92d90-d281-4473-8826-6ec88dc5fef1)

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JasonDsouza212** [comment]
@1Shubham7 this issue is duplicate and has been assigned to someone else, if he fails to do it Then you will be assigned

**Comment by 1Shubham7** [comment]
But I solved it locally.

**Comment by 1Shubham7** [comment]
I just had to push. Now what should  I do? wait ?

**Comment by 1Shubham7** [comment]
![doenissue](https://github.com/JasonDsouza212/free-hit/assets/116020663/718111f1-8a9a-45a8-b130-71037fd65e25)

Please do let me know what to do?
