### ISSUE TITLE
[Bug]: Remove console.log messages

### ISSUE THREAD

**Issue by Avinash905** [JasonDsouza212/free-hit#508]
### What happened?

There are console.log messages in the code which are displayed on the browser console.

### Add screenshots

![Screenshot (459)](https://github.com/JasonDsouza212/free-hit/assets/56786344/bf8c2001-e1fa-4ac9-871d-1dc751f2dc52)

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Avinash905** [comment]
Please assign me this issue so that I can work on this issue under **GSSOC'23**.

**Comment by youngancient** [comment]
Hi @VenomFate-619 , can you assign this issue to me, there are errors still logged to the console.
![freehit](https://github.com/JasonDsouza212/free-hit/assets/93747805/7ca31ad3-49ab-41f5-b3d5-bc3c33306214)

**Comment by VenomFate-619** [comment]
@youngancient do create another issue regarding removing this warning.
I will assign you there
