### ISSUE TITLE
Remove Duplicate cards [Bug]: 

### ISSUE THREAD

**Issue by rahulrana701** [JasonDsouza212/free-hit#520]
### What happened?

There are duplicate cards which needs to be removed..

### Add screenshots

Add screenshots
<img width="944" alt="Screenshot 2023-06-07 131857" src="https://github.com/JasonDsouza212/free-hit/assets/123585591/3193afc9-4eb7-4a4f-b217-a57e0f79233a">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rahulrana701** [comment]
hi @VenomFate-619 @JasonDsouza212 I would like to work on this issue..

**Comment by JasonDsouza212** [comment]
This is a duplicate issue and been assigned to someone else
