### ISSUE TITLE
[Feat]: website Preloader

### ISSUE THREAD

**Issue by Once-kaur** [JasonDsouza212/free-hit#521]
### What feature?

I have an idea to add a  website preloader

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JasonDsouza212** [comment]
go ahead and add it @Once-kaur

**Comment by abhinav-m22** [comment]
@JasonDsouza212 @VenomFate-619 
Can I work on this feature implementation?
Please assign me the issue if it is inactive.
