### ISSUE TITLE
[Feat]: Add a New Tool

### ISSUE THREAD

**Issue by ERHolguin** [JasonDsouza212/free-hit#525]
### What feature?

Hello,

I'm Ellis and I'm a contributor under GSSoC '23.

I have an idea to add a new UI tool to the website. It's called "Coolors". It's a color palette generator with a vast color library. They also provide info on color conversion, combinations, blindness simulation, and more!

Please assign this issue to me.

### Add screenshots

![Screenshot from 2023-06-07 23-03-23](https://github.com/JasonDsouza212/free-hit/assets/122590041/ebc37221-1719-4e44-8013-549819421f0c)

![Screenshot from 2023-06-07 23-04-37](https://github.com/JasonDsouza212/free-hit/assets/122590041/4cd02673-fc51-4750-8a93-e5daa706239c)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by VenomFate-619** [comment]
I think this tool is already present do check and confirm

**Comment by JasonDsouza212** [comment]
@ERHolguin, the tools are already present, but the title is wrong. If you want, you can work on it. Are you working under Gssoc23?

**Comment by ERHolguin** [comment]
Hello,

Thanks for the prompt response! I double-checked and you're correct. It is there and it is misspelled so I missed it yesterday. Yes, I can absolutely fix it, and I am working under Gssoc'23.

![Screenshot from 2023-06-08 13-05-09](https://github.com/JasonDsouza212/free-hit/assets/122590041/3d362f33-c7fa-4d33-a0d1-60ae2f6beab7)
