### ISSUE TITLE
Change description for Poet.so and Pika Style

### ISSUE THREAD

**Issue by buneeIsSlo** [JasonDsouza212/free-hit#53]
Currently, the descriptions for Poet.so and Pika Style are incorrect. Please add the appropriate descriptions.
*"Capture and share Twitter posts as beautiful images"* is a good example.

**Comment by JasonDsouza212** [comment]
go ahead and add it

**Comment by buneeIsSlo** [comment]
> go ahead and add it

Sure, please assign it to me.
