### ISSUE TITLE
error in display content or resources as dual 

### ISSUE THREAD

**Issue by AravindAkuthota** [JasonDsouza212/free-hit#539]
below image discribes the issue 

<img width="547" alt="Screenshot 2023-06-09 080243" src="https://github.com/JasonDsouza212/free-hit/assets/92900345/19aad201-ec35-485a-9cea-6ef136e48332">

i want to work on this and solve it

**Comment by JasonDsouza212** [comment]
@AravindAkuthota, please go ahead and remove it. There are many duplicate entries, so make sure to remove all of them.

**Comment by AravindAkuthota** [comment]
the issue is resolved
