### ISSUE TITLE
[Feat]: Bootstrap Docs

### ISSUE THREAD

**Issue by Vidip-Ghosh** [JasonDsouza212/free-hit#542]
### What feature?

I have an idea to add the bootstrap documentation so that users would be familiar to use its components.

### Add screenshots

<img width="1680" alt="Screenshot 2023-06-09 at 11 50 10" src="https://github.com/JasonDsouza212/free-hit/assets/91741581/42a1c854-f98a-4789-8ed5-95642084f94c">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JasonDsouza212** [comment]
I dont think that can be considered a free tool

**Comment by Vidip-Ghosh** [comment]
> I dont think that can be considered a free tool

Its a free and open source web development framework.

**Comment by Vidip-Ghosh** [comment]
@JasonDsouza212 can you please assign this issue?

**Comment by khushboo-9876** [comment]
hey is this issue available can you please assign thi?
