### ISSUE TITLE
[Bug]:  card-container img not working

### ISSUE THREAD

**Issue by Gurnav224** [JasonDsouza212/free-hit#551]
### What happened?

I found a BUG 🐞 some card-container img are not because their link must be expired and I want to add new img link 

card-container having bugs 

showcase 
zety
zarla
reduce img
undraw 
hired.com

### Add screenshots

Add screenshots
![Screenshot 2023-06-09 220336](https://github.com/JasonDsouza212/free-hit/assets/72142482/c1d0efd3-969c-4a49-b57b-ccf6f4aa887f)

![Screenshot 2023-06-09 220418](https://github.com/JasonDsouza212/free-hit/assets/72142482/429dc5fa-08c7-47c2-b223-b87838ccc881)

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JasonDsouza212** [comment]
@Gurnav224 you can start working on this

**Comment by techmannih** [comment]
hello @JasonDsouza212 ,
I found a BUG, some card-containers are repeated like shown below
I want to handle this issue....., please assigned me 
I have solved them .please take pull request and merged.
![Screenshot_2023-06-10_21-02-06](https://github.com/JasonDsouza212/free-hit/assets/125847751/1b0c03e2-be2e-4445-b31d-1a95bb45cd85)
![Screenshot_2023-06-10_21-03-00](https://github.com/JasonDsouza212/free-hit/assets/125847751/7c457027-156b-4649-9b4b-275b0e1b5f5a)
![Screenshot_2023-06-10_22-00-4333337](https://github.com/JasonDsouza212/free-hit/assets/125847751/9c6e9ff0-b585-42f8-829a-2a285bff5b93)
![Screenshot_2023-06-10_21-59-2311111](https://github.com/JasonDsouza212/free-hit/assets/125847751/f4a20abc-54d6-4e7a-b580-e906074875f0)

**Comment by techmannih** [comment]
I handle this issue ... please assign me
