### ISSUE TITLE
Website UI not responsive [Bug]: 

### ISSUE THREAD

**Issue by rahulrana701** [JasonDsouza212/free-hit#557]
### What happened?

The UI of the website is not responsive it is breaking at some points , I would like to make it completely responsive at all widths.

### Add screenshots

Add screenshots
<div class='d-flex'>
<img width="160" alt="Screenshot 2023-06-10 001640" src="https://github.com/JasonDsouza212/free-hit/assets/123585591/574f8974-a68f-4fb7-adf8-5b7765eba889">
<img width="195" alt="Screenshot 2023-06-10 001707" src="https://github.com/JasonDsouza212/free-hit/assets/123585591/ab0691e8-7c05-4a56-921c-736d0c0e406a">
<img width="117" alt="Screenshot 2023-06-10 001747" src="https://github.com/JasonDsouza212/free-hit/assets/123585591/98e7c66a-7f3d-4282-af90-f004def7f3c0">
</div>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rahulrana701** [comment]
hi @JasonDsouza212 I would like to work on this issue please assign it to me.

**Comment by JasonDsouza212** [comment]
Ya work on this ASAP

**Comment by JasonDsouza212** [comment]
And add all width screenshots

**Comment by JasonDsouza212** [comment]
@rahulrana701, if you fail to reply to this issue today, it will be assigned to someone else as it is a high-priority bug.

**Comment by rahulrana701** [comment]
@JasonDsouza212 i will submit a pr by today or around 1 am at tomorrow's morning..

**Comment by JasonDsouza212** [comment]
Yes, don't worry. Submit it tomorrow, no rush, but make sure you do it by tomorrow. Your level of determination is great, so keep it up!

**Comment by rahulrana701** [comment]
@JasonDsouza212 yeah sure
