### ISSUE TITLE
[Feat]: Dark mode

### ISSUE THREAD

**Issue by kaashikaagrawal** [JasonDsouza212/free-hit#561]
### What feature?

We can add a moon icon at the top right to indicate dark mode. Clicking it will invert the color scheme making it look dark instead of light. Please assign me this issue.

### Add screenshots

Add screenshots

### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

**Comment by JasonDsouza212** [comment]
This is a duplicate issue, but as of now, it has been assigned to others. However, there has been no response from them, so I will assign it to you.

**Comment by kaashikaagrawal** [comment]
alright. What are the steps to run the project? Is it just npm install and then npm start?
