### ISSUE TITLE
NavBar UI not responsive [style]: 

### ISSUE THREAD

**Issue by liNikham** [JasonDsouza212/free-hit#567]
### What's the style idea?

The navbar breaks for small screens and the name of the website Free Hit Disappears and only logo/About us remains visible . My idea is that in small screens to display it in flex  column in small screens.
These will create 3 rows first row will contain website name, second row will contain  hamburger and website logo/About us and third row will contain search box

### Add screenshots

![Screenshot (288)](https://github.com/JasonDsouza212/free-hit/assets/136007026/bd8e1228-6224-487b-81a1-c8489cd5517d)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bharathkalyans** [comment]
* `search_box` needs the width to be changed on smaller screens!
* Also we can hide the logo on small screens!

**Comment by JasonDsouza212** [comment]
> * `search_box` needs the width to be changed on smaller screens!
> * Also we can hide the logo on small screens!

Yes, some recent PR merging has caused this issue.

**Comment by JasonDsouza212** [comment]
This is a crucial issue and needs to be resolved ASAP so can you work on this now @liNikham

**Comment by Aman-Manwani** [comment]
@JasonDsouza212 Hey! I wanna do it. Can you please assign this issue to me 
Can you also suggest how you want the search bar

**Comment by liNikham** [comment]
if we hide the logo we cant reach the about us page .
so on small screen screen can we put the about us link in the sidebar section
because on small screen we can hide the logo but can still access the about us page

**Comment by liNikham** [comment]
or is it better to not hide the logo

**Comment by Aman-Manwani** [comment]
@liNikham Are you still working for this issue ??

**Comment by bharathkalyans** [comment]
* Change the `search_box` on the media query for smaller screens and hide the logo on smaller screens!

**Comment by Aman-Manwani** [comment]
@JasonDsouza212 Its already Done,can you close this issue
