### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by itsarraj** [JasonDsouza212/free-hit#572]
### What happened?

I found a BUG 🐞
![image](https://github.com/JasonDsouza212/free-hit/assets/69187344/a138ad36-49f7-4d00-b61c-ea5e3f3cb7c5)
duplicate zety 

### Add screenshots

Add screenshots
![image](https://github.com/JasonDsouza212/free-hit/assets/69187344/aac3a3f6-c619-4d3c-8ece-f05c3a8374d4)
duplicate zety 

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by itsarraj** [comment]
![Screenshot from 2023-06-11 00-28-17](https://github.com/JasonDsouza212/free-hit/assets/69187344/a1413d67-f200-4141-9f46-2fafa90a37f7)
![Screenshot from 2023-06-11 00-28-21](https://github.com/JasonDsouza212/free-hit/assets/69187344/3be4ce0f-5a82-4fca-90c4-ff9d23e2c65a)
![Screenshot from 2023-06-11 00-28-37](https://github.com/JasonDsouza212/free-hit/assets/69187344/ea2b6e0f-4a7e-4e59-af39-73203320f585)


All these problems occur because of multiple info of same thing in db

**Comment by itsarraj** [comment]
![image](https://github.com/JasonDsouza212/free-hit/assets/69187344/7d99257b-04c6-43ca-8aef-5904d9214880)


fix animoto image

i am removing duplicates

**Comment by itsarraj** [comment]
boxicons
canva
cataz
dashboard kit 
material ui
piped 
previewed mockups 
quill
regexr
resume.io

muzli
ui design daily 
ui kit figma
unblast	
unlighthouse
usertesting
zarla
zety
these are duplicates

**Comment by itsarraj** [comment]
![image](https://github.com/JasonDsouza212/free-hit/assets/69187344/ce39c577-642e-479d-b018-6b867c551830)

**Comment by JasonDsouza212** [comment]
The issue has been assigned to someone. If he fails, then you can work on it because there are some rules that we need to follow.

**Comment by itsarraj** [comment]
solved in fix: fixed duplicates in database #573
