### ISSUE TITLE
[Feat]: Add WatchSeriesHD to "movies" list

### ISSUE THREAD

**Issue by hxrii** [JasonDsouza212/free-hit#574]
### What feature?

- Feature: Add WatchSeriesHD to "movies" list.
- Description : WatchSeriesHD is a free movies and series streaming platform.

### Add screenshots

Screenshots
<img width="1440" alt="Screenshot 2023-06-11 at 10 03 48 AM" src="https://github.com/JasonDsouza212/free-hit/assets/70883415/1a5a5c6b-8409-48d9-ba95-6ace8c62a2a5">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JasonDsouza212** [comment]
Happy to have you @hxrii
