### ISSUE TITLE
[Bug]: 3D icons is two times on the website

### ISSUE THREAD

**Issue by sumitkr2000** [JasonDsouza212/free-hit#577]
### What happened?

I found that the 3D icons tool is two times on the website. It should appear only one time. Please assign me this issue. Thank you!

### Add screenshots

![image](https://github.com/JasonDsouza212/free-hit/assets/100675296/2397fd18-8fc3-46f9-94e9-aed140a579e8)

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JasonDsouza212** [comment]
The issue has been assigned to others @sumitkr2000
