### ISSUE TITLE
[Bug]: Duplicate Websites

### ISSUE THREAD

**Issue by shyamtawli** [JasonDsouza212/free-hit#579]
### What happened?

I found a BUG 🐞
3D Icons and 6.5M Design Assets are appearing two times. Should Remove one of them.

### Add screenshots

![ss](https://github.com/JasonDsouza212/free-hit/assets/104145978/3ade3459-f082-4c62-857c-491d179c5a28)

### What browsers are you seeing the problem on?

Brave

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JasonDsouza212** [comment]
@shyamtawli this issue has been assigned to someone

**Comment by shyamtawli** [comment]
Okay @JasonDsouza212 I am closing it.
