### ISSUE TITLE
Description not matching

### ISSUE THREAD

**Issue by JasonDsouza212** [JasonDsouza212/free-hit#58]
## There are many tools that do not match their correct description.
- Correct the description of the tools and make your first contribution. 
- This is the best way to start your open-source journey.

**Comment by Bharadwajshivam28** [comment]
@JasonDsouza212 can i wok on it

**Comment by JasonDsouza212** [comment]
Yes, go ahead, @Bharadwajshivam28

**Comment by Bharadwajshivam28** [comment]
thanks @JasonDsouza212

**Comment by Bharadwajshivam28** [comment]
Please drop where is the exsisting description

**Comment by JasonDsouza212** [comment]
I didn't get you

**Comment by Bharadwajshivam28** [comment]
sir like where is description .

**Comment by JasonDsouza212** [comment]
navigate to src/DB/products.json  you can find the descriptions there. 
You can call me Jason

**Comment by Bharadwajshivam28** [comment]
okay jason

**Comment by priyankarpal** [comment]
is this issue completed?

**Comment by Mudassirkhan2** [comment]
can you assign this to me
