### ISSUE TITLE
[style]: Fixing footer

### ISSUE THREAD

**Issue by ayushsachan123** [JasonDsouza212/free-hit#580]
### What's the style idea?

I want improve the position of the footer in the Bookmarks section.

Please assign me this Issue under GSSOC'23.

### Add screenshots

![FREEHIT](https://github.com/JasonDsouza212/free-hit/assets/97084090/bbaf3ebe-e5ab-4097-b547-595fdc98ef17)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by VenomFate-619** [comment]
what is the issue with the position?
can you elaborate it?

**Comment by ayushsachan123** [comment]
> what is the issue with the position? can you elaborate it?

The footer is coming in the middle of the page and just below the image. Fixing it to the bottom of the page.

**Comment by JasonDsouza212** [comment]
Okay, give it a minimum width so that it never appears in the middle or top.

**Comment by ayushsachan123** [comment]
Issue has been solved
