### ISSUE TITLE
[Bug]: Want to Improve Hover Issue at About Navigation bar

### ISSUE THREAD

**Issue by rishit-gupta** [JasonDsouza212/free-hit#586]
### What happened?

When Cursor Hovering on Home , Bookmarks It highlight the tag but At About it stuck to highlight ( Background Color )

### Add screenshots

![image](https://github.com/JasonDsouza212/free-hit/assets/83339859/2e3ac6bc-b802-4061-b783-aa602c146f43)

### What browsers are you seeing the problem on?

Microsoft Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by afreen-ahmed12** [comment]
please assign me this task...
i will do as soon as possible

**Comment by ayushsachan123** [comment]
Please assign this issue to me under GSSOC'23

**Comment by JasonDsouza212** [comment]
That was intentionally designed so that the user can easily identify which page they are currently on.
