### ISSUE TITLE
UI still not responsive for small devices[Bug]: 

### ISSUE THREAD

**Issue by rahulrana701** [JasonDsouza212/free-hit#588]
### What happened?

The UI is still not responsive for small devices like mobile phones.

### Add screenshots

Add screenshots
<img width="152" alt="Screenshot 2023-06-12 125257" src="https://github.com/JasonDsouza212/free-hit/assets/123585591/51d4aa04-5bc0-4b8a-9017-90dd97b5d1c5">
<img width="157" alt="Screenshot 2023-06-12 125239" src="https://github.com/JasonDsouza212/free-hit/assets/123585591/bff3587f-911b-4749-a60d-3a7d69cfcbaa">
<img width="161" alt="Screenshot 2023-06-12 125220" src="https://github.com/JasonDsouza212/free-hit/assets/123585591/793157cb-ef03-43e0-9a7c-d6d3ad37deef">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by VenomFate-619** [comment]
are you working under gssoc'23 ?

**Comment by rahulrana701** [comment]
@VenomFate-619 yes I am working under gssoc 23

**Comment by rahulrana701** [comment]
@VenomFate-619 I opened this issue earlier and created a pr for it and I had fixed this and it is working under all devices , but my pr was closed saying this that the issue was high priority so it was taken care of and still the issue was not solved so therefore I opened the issue again

**Comment by rahulrana701** [comment]
@VenomFate-619 you can check it out https://github.com/JasonDsouza212/free-hit/pull/578#issue-1751381165

**Comment by rahulrana701** [comment]
@VenomFate-619 so please tell me can you reopen this pr ??

**Comment by VenomFate-619** [comment]
@JasonDsouza212

**Comment by rahulrana701** [comment]
@VenomFate-619 any updates..

**Comment by rahulrana701** [comment]
hi @JasonDsouza212 @VenomFate-619 can you please assign this issue to me again , I somehow unassigned myself by mistake 
, I am going to submit a pr right now...

**Comment by rahulrana701** [comment]
Here is the link of the pr @JasonDsouza212 @VenomFate-619 https://github.com/JasonDsouza212/free-hit/pull/649#issue-1761694244

**Comment by rahulrana701** [comment]
hi @JasonDsouza212 @VenomFate-619 will you consider this ???

**Comment by rahulrana701** [comment]
hi @JasonDsouza212 you can check it out I updated the issue no.

**Comment by JasonDsouza212** [comment]
@rahulrana701 done
