### ISSUE TITLE
[Feature]: Want to add Color themes in the website

### ISSUE THREAD

**Issue by lakhan06** [JasonDsouza212/free-hit#604]
### What feature?

- I want that their should be a option so that user can select color theme of the website according to his/her choice and get a better user experience .
- I will add a themes option on the right side of each page and will change the color according to user choice by using JavaScript.
- I will uses root elements to change the color according to user choice.
- I will also stored the data of color theme in user local storage that user choose and when user again come on website then he will see the color theme according to his/her choice.

### Add screenshots

Color theme1:
![image](https://github.com/JasonDsouza212/free-hit/assets/119161467/5f8257ed-84c0-4518-b495-eaf1ebbd6690)

Color Theme 2:
![image](https://github.com/JasonDsouza212/free-hit/assets/119161467/d240376a-d5b0-482a-90a4-8c9543a212cb)

Color Theme 3:
![image](https://github.com/JasonDsouza212/free-hit/assets/119161467/0679cdbf-0d4b-4666-9ac6-e55d0c12f0d1)
 

and more can be added according to what better look for website and bellow is the video how theme button will lok

https://github.com/JasonDsouza212/free-hit/assets/119161467/4cbb3fcd-3919-4f17-920b-b021235ddb60

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JasonDsouza212** [comment]
Great! You can go ahead and implement it. Please let us know by recording the screen once it's done.

**Comment by lakhan06** [comment]
> Great! You can go ahead and implement it. Please let us know by recording the screen once it's done.

@JasonDsouza212  sir i am getting problem in running this file in my local pc after clone .
I never work using pnpm so can you please help me ho i can run this in my local so after that only i can work on this issue

**Comment by JasonDsouza212** [comment]
First install pnpm in your system

**Comment by JasonDsouza212** [comment]
Read the CONTRIBUTING.md file you will understand it

**Comment by lakhan06** [comment]
> Read the CONTRIBUTING.md file you will understand it

ok sir thankyou
