### ISSUE TITLE
[STYLE]: Remove Clicking Actions and Better Use Hovering Movable Effects in Hamburger Menu[Left]

### ISSUE THREAD

**Issue by NarendraKoya999** [JasonDsouza212/free-hit#611]
### Issue Description:
- **When Click on Hamburger menu On Left Side Of Header Bar, It's shows Respective Menu Details.**
- **If you want to Close this Menu Sections List Again Using Clickable Cross Mark Icon.**
- **So, If you want to Opens and Closes this Hamburger Menu Using Only Clickable Actions.**

### Suggest Style:
- **Instead of Using Clickable Actions on Menu Bar Sections List Using Cross Mark. Allow Hovering Movable Effects.**
> Example:
-  **When Put Mouse on Hamburger Menu, It automatically Opens Whole Menu Sections List.**
- **And again want to Close this Menu Sections List. Just Move Mouse Away on The Other Free Area in Website.**

### Screenshot of My suggested Style
<img width="255" alt="freehit-1" src="https://github.com/JasonDsouza212/free-hit/assets/84512164/67a8f15b-db2a-4c74-8c9a-d6e65c07c444">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by NANDHINI45** [comment]
I am interested to work on this issue please assign me this under GSSOC'23 @JasonDsouza212

**Comment by JasonDsouza212** [comment]
@NarendraKoya999 , Do you want to work on this?

**Comment by NarendraKoya999** [comment]
No @JasonDsouza212 . I do not work on this Issue. Please assign this Issue Others.

**Comment by JasonDsouza212** [comment]
> I am interested to work on this issue please assign me this under GSSOC'23 @JasonDsouza212

@NANDHINI45 you can start working on this

**Comment by NANDHINI45** [comment]
Sure sir

**Comment by NarendraKoya999** [comment]
Hi @JasonDsouza212 . This Issue Raised 3 weeks Ago. No Update about PR. If any Problem to Assigned Person, I will take up this Issue

**Comment by NANDHINI45** [comment]
Hi @NarendraKoya999  I changed the mousedown event into mouseover event  in Navbar.jsx, but it doesn't work so I am still in searching the event . When iam placing the mouse on that hamburger menu it hover but it does'nt show the menu item ,that's the problem. what event could  I use to  resolve this issue?
