### ISSUE TITLE
Add website 

### ISSUE THREAD

**Issue by samailamalima** [JasonDsouza212/free-hit#62]
I have some websites for web3 testing 

ChaiJS
Chai BDD Styled
Chai Assert
Mocha Hooks
Solidity Chai Matchers

should I go ahead to add them?

**Comment by samailamalima** [comment]
Yes they are all free

**Comment by JasonDsouza212** [comment]
go ahead and add it

**Comment by priyankarpal** [comment]
@samailamalima are you working on this issue?

**Comment by samailamalima** [comment]
Yes
