### ISSUE TITLE
[Feat]: Gssoc'23 Add feature jam extension

### ISSUE THREAD

**Issue by l9vanya** [JasonDsouza212/free-hit#633]
### What feature?

Report bugs in seconds, without disrupting your work flow. 
Link: https://jam.dev/ 

Could you assign me this issue @JasonDsouza212 

### Add screenshots

![Jam-Build-a-bug-free-product-](https://github.com/JasonDsouza212/free-hit/assets/120164254/025eedd3-ed49-40af-b8df-d34699717bec)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by VenomFate-619** [comment]
awesome tool
