### ISSUE TITLE
[Feat]: improvements in pagination buttons

### ISSUE THREAD

**Issue by shobhitexe** [JasonDsouza212/free-hit#636]
### What feature?

See as we can see on attached SS if i go to page number 4 or something like that 
its hard to goto page 1 after that like we have to navigate all the way upto page 1

instead we can put something like first page or jump to page feature
![image](https://github.com/JasonDsouza212/free-hit/assets/29349136/581e5ec5-828c-4d5f-86a0-9b86a6a99706)
something like this

### Add screenshots

![image](https://github.com/JasonDsouza212/free-hit/assets/29349136/c6b8b164-4a48-4e73-adae-5223636e7d1b)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JasonDsouza212** [comment]
What about in mobile view

**Comment by shobhitexe** [comment]
> See as we can see on attached SS if i go to page number 4 or something like that its hard to goto page 1 after that like we have to navigate all the way upto page 1
> 
> instead we can put something like first page or jump to page feature

i guess you didnt get it Instead of having to scroll back through multiple pages to reach the first page, it would be more convenient to have a button or option that takes you directly to the first page. This way, you can easily jump back to the beginning without the hassle of navigating through all the pages one by one.

which will be same for all views

**Comment by dhruv8433** [comment]
i would like to work on this issue under gssoc'23
