### ISSUE TITLE
[New Feature]: Toggle Dark/Light Mode

### ISSUE THREAD

**Issue by codeburn12** [JasonDsouza212/free-hit#640]
### What feature?

I want to add a toggle button from normal theme to dark theme of whole requires section of website. The users can easily switch between a dark or light scheme by clicking on the toggle button. This will be beneficial for their eye.

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JasonDsouza212** [comment]
@codeburn12 As of now someone is working on it , If he fails to do it Ill assign it to you

**Comment by SarveshGholap** [comment]
I want to work on this issue under gssoc
