### ISSUE TITLE
[Docs]: Improve the GSSoC logo for both light and dark mode

### ISSUE THREAD

**Issue by Hardikaz** [JasonDsouza212/free-hit#644]
### what's wrong in the documentation?

# This logo does not seems to be perfect for the light mode
![image](https://github.com/JasonDsouza212/free-hit/assets/95474096/63eb7da5-7cf9-4c5f-8b68-e7b708a3071f)

# I wish to change it like this 

- For light mode
 
![image](https://github.com/JasonDsouza212/free-hit/assets/95474096/cbe55d2e-0ebf-43d7-9a09-1a8343c2678f)

- For dark mode
 
![image](https://github.com/JasonDsouza212/free-hit/assets/95474096/42c681de-e493-4c23-83fc-4e25a51a54b7)

# Pls assign me this issue under GSSoC'23. I'm a GSSoC'23 contributor.

### Add screenshots

added

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ayesha-firdaus** [comment]
can i do this?

**Comment by Hardikaz** [comment]
Solved and send PR at #1277
