### ISSUE TITLE
[style]: Change the style of Navbar

### ISSUE THREAD

**Issue by chinmayjain08** [JasonDsouza212/free-hit#645]
### What's the style idea?

We need to improve  the design of navbar to make it look more professional and appealing with proper font-size, padding, animations and interactions.

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JasonDsouza212** [comment]
You can give it a try. If we like it, we can proceed with your design.

**Comment by chinmayjain08** [comment]
okay, thanks
