### ISSUE TITLE
[Feat]: Add some AI tools like Slidesai, Uizard, Autodraw, Starrytars

### ISSUE THREAD

**Issue by madhurafulkar** [JasonDsouza212/free-hit#647]
### What feature?

Slides AI
Slides AI is an AI-powered tool that assists in creating and enhancing presentation slides. It leverages artificial intelligence technology to automate certain tasks and provide intelligent suggestions to improve the overall design and content of slides.

AutoDraw
AutoDraw is an AI-powered tool developed by Google that assists users in creating drawings and sketches by providing intelligent suggestions and predictions. It aims to simplify the drawing process, especially for individuals who may not have strong artistic skills or struggle to translate their ideas into visual representations.

Uizard
Uizard is an AI-powered UI design tool that helps you design wireframes, mockups, and prototypes in minutes. It has a number of features that make it ideal for both non-designers and designers alike, including AI-powered design features, pre-made design templates, easy-to-use drag-and-drop editor.

Starrytars
Starrytars helps users to create high-quality avatars with AI in minutes. It allows users to establish their online presence, create personalized avatars, and cartoonify their faces. 

### Add screenshots

Slides AI
![slidesai](https://github.com/JasonDsouza212/free-hit/assets/120560129/a7481459-c904-4b84-9be4-5d77aea43539)

AutoDraw
![autodraw](https://github.com/JasonDsouza212/free-hit/assets/120560129/d13587a9-b020-4865-8032-dff782e84cfd)

Uizard
![uizard](https://github.com/JasonDsouza212/free-hit/assets/120560129/680af08b-321a-47b2-b950-3c1773889b55)

Starrytars
![starrytars](https://github.com/JasonDsouza212/free-hit/assets/120560129/0dd3bfb9-a8a8-409d-84e5-8ec2e61b0b0f)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by VenomFate-619** [comment]
are you working under gssoc'23 ?
