### ISSUE TITLE
 Shrunk footer's top and bottom 

### ISSUE THREAD

**Issue by Deva-1903** [JasonDsouza212/free-hit#65]
**The footer's top and bottom should be shrunk to look nice, and the color of Jason Dsouza's text should be changed to make it more visible.**

![Screenshot (292)](https://user-images.githubusercontent.com/97371915/228606259-da01036f-564d-47e4-b80e-e36ab5ecc863.png)

**Comment by JasonDsouza212** [comment]
changing the color of the name would be a good idea, But I don't recommend you yo change the padding of the footer

**Comment by Deva-1903** [comment]
@JasonDsouza212 Check the PR, The snapshot of the footer is attached. Moreover, if you decide against changing the padding in the footer, I will do so. Yet everything now appears prettier and cleaner.
