### ISSUE TITLE
Add a newsletter subscription in footer

### ISSUE THREAD

**Issue by akshaysoni10** [JasonDsouza212/free-hit#651]
### What feature?

I want to add a newsletter subscription so that user get updated through email.

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JasonDsouza212** [comment]
Can you explain me how exactly it works

**Comment by akshaysoni10** [comment]
I want to add a email newsletter where a user can subscribe through their email id. After subscribing through email he/she got updated through mail if any new things is added in website.

**Comment by VenomFate-619** [comment]
currently, we do not have any plan of starting a newsletter, therefor I an closing this issue.
