### ISSUE TITLE
[style]: Design the home page.

### ISSUE THREAD

**Issue by kailashchoudhary11** [JasonDsouza212/free-hit#653]
### What's the style idea?

Let's redesign this page to introduce "Free-Hit" and explain why we need it in our daily lives. After that, we can specify the features such as categories, how to use filters, selecting multiple filters, the search functionality, and other related aspects. Finally, we can highlight the most frequently used tools and present them at the end. If we structure the page in this way, it will be the best choice.

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ShreyaDhiman24** [comment]
I would like to work on this issue under GSSoC'23
