### ISSUE TITLE
FIX: cards heights

### ISSUE THREAD

**Issue by priyankarpal** [JasonDsouza212/free-hit#66]
I just noticed that the website's height needs to adjust. 

https://user-images.githubusercontent.com/88102392/228606979-a81e5e48-4b18-41ed-8f01-db6de0f198fd.mp4

**Comment by JasonDsouza212** [comment]
Can you fix this Priyankar

**Comment by priyankarpal** [comment]
> Can you fix this Priyankar

yeah sure.

**Comment by priyankarpal** [comment]
I think this issue solved
