### ISSUE TITLE
Redesign the page navigator section

### ISSUE THREAD

**Issue by inkerton** [JasonDsouza212/free-hit#666]
### What's the style idea?

We need to improve  The current style as it does not give an idea on how many pages are there. We may use something like what google uses or show the current page in between and use dots to show that there are more available.

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by VenomFate-619** [comment]
can you add an example of that

**Comment by inkerton** [comment]
i was recommending something like this to have an idea of how many pages are there;
Example 1:
![image](https://github.com/JasonDsouza212/free-hit/assets/127668005/0de22ba9-5460-4778-96a0-09ab65ee28bf)
Example 2:
![image](https://github.com/JasonDsouza212/free-hit/assets/127668005/2d1ef963-48c9-410b-bf69-8cbfc46554fd)

**Comment by inkerton** [comment]
To show exactly what I meant, these are the designs I made myself:
![image](https://github.com/JasonDsouza212/free-hit/assets/127668005/a985b89b-a92f-48cc-a455-08d706b86c93)
and 
![image](https://github.com/JasonDsouza212/free-hit/assets/127668005/bdc837b0-5ba0-486b-812a-d81c2ddf642b)
It would help navigate through the pages and give an absolute idea of how many pages it has. Sometimes navigating one by one is time consuming so it would directly go for a search.

**Comment by JasonDsouza212** [comment]
Looks good , Do you want to work on this?

**Comment by inkerton** [comment]
yes, please.

**Comment by inkerton** [comment]
sir, I got this error and I don't understand it so if you can help me here.
![image](https://github.com/JasonDsouza212/free-hit/assets/127668005/5948f3da-9df6-4f6d-bebd-c3e1b7eb345b)

**Comment by VenomFate-619** [comment]
@JasonDsouza212 do look into it
