### ISSUE TITLE
Add the prettier linter workflow

### ISSUE THREAD

**Issue by metabiswadeep** [JasonDsouza212/free-hit#668]
### What feature?

Add the prettier linter to ensure proper linting of the code. As a project with multiple users contributing to it, it is essential to maintain a proper and uniform linting style to ensure better code readability by users. An excellent way to do this is by automatic linting checks using GitHub actions.

I would like to work on this as a part of GSSoC 23.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by VenomFate-619** [comment]
That is a good suggestion, but we were thinking to add a pre-commit hook that will run prettier directly in your system instead of at GitHub.
I will create an issue for it.

**Comment by metabiswadeep** [comment]
@VenomFate-619 in that case please assign me that issue as I would like to work on it. Alternatively, I can modify the description of this issue to align with your requirements. Please inform me regarding the same.
