### ISSUE TITLE
GSSoC'23: Hover Effect around Next amd Prev Button to make it more alive.

### ISSUE THREAD

**Issue by ShreyaDhiman24** [JasonDsouza212/free-hit#671]
### What feature?
Hover Effect around Next amd Prev Button to make it more alive.
I want to work on this issue under GSSoC'23.

### Add screenshots
[Screencast from 19-06-23 01:31:26 AM IST.webm](https://github.com/JasonDsouza212/free-hit/assets/98320971/f9065a64-19e2-4b09-b553-754c0b6e9966)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JasonDsouza212** [comment]
You can add a hover effect, but the effect you specified doesn't look good. If you'd like, you can try a different approach, and if we like it, we can merge it.

**Comment by ShreyaDhiman24** [comment]
[Screencast from 21-06-23 01:16:00 AM IST.webm](https://github.com/JasonDsouza212/free-hit/assets/98320971/23007f68-baa7-48d6-9204-af58f2c16db7)
How about this one?

**Comment by ShreyaDhiman24** [comment]
what about this one @JasonDsouza212 . We will be changing colours according to website.
