### ISSUE TITLE
[🐞]: Buttons border transformation

### ISSUE THREAD

**Issue by dheeraj1129** [JasonDsouza212/free-hit#681]
### What happened?

When we click on the nav bar (Home, bookmark, About) buttons the border-radius does not transform in a proper way it changes into a square first, and then changes into a rounded border.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JasonDsouza212** [comment]
Do you want to work on this @dheeraj1129

**Comment by dheeraj1129** [comment]
Yes Sure,
