### ISSUE TITLE
[Feat]:  search box performance improve

### ISSUE THREAD

**Issue by mandliyarajendra11** [JasonDsouza212/free-hit#685]
### What feature?

I have an idea 
we can use debouncing in search box to improve performance 

what is debouncing in search box - 
In the context of a search box, debouncing is a technique used to control and optimize the execution of search queries or other related actions triggered by user input. When a user types into a search box, it often results in frequent events firing, such as keypress or input events. Each event may trigger an action, such as sending a request to a server to retrieve search results or updating the search suggestions

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JasonDsouza212** [comment]
So, what are the uses of these changes you mentioned?

**Comment by mandliyarajendra11** [comment]
> So, what are the uses of these changes you mentioned?

To optimize the search box, currently, a call is made for each text input, and we receive results based on the entered word. However, we don't need to make a call for every word typed. For example, if someone is typing the word "game," instead of making separate calls for each letter ("g," "ga," "gam," "game"), we can implement debouncing. This means that as soon as the user pauses typing, the search call will be initiated. The debounce time can be set to 1 second or 500 milliseconds, depending on how long we want to wait after the user stops typing before making the call.



### BY CHAT GPT - 

User input: As the user types in the search box, an event (such as "keyup" or "input") is triggered for each keystroke.

Debounce function: Implement a debounce function that wraps the search call. This function ensures that the search call is not made immediately for each keystroke, but rather after a specified delay once the user has paused typing.

Delay timer: Set a timer within the debounce function. When the debounce function is invoked, it resets the timer to the specified delay (e.g., 1 second or 500 milliseconds).

User pauses typing: If the user continues typing within the specified delay, the timer is reset again. This restarts the delay period.

Timer expiry: Once the delay period elapses without any further user input, the debounce function is triggered, and the search call is made based on the entered text.

By using debouncing, unnecessary search calls for each intermediate keystroke are avoided. Instead, the search call is delayed until the user pauses typing, which improves performance by reducing unnecessary network requests and improves the overall user experience.

**Comment by JasonDsouza212** [comment]
@mandliyarajendra11, you can implement it first, and then create a screen recording of the changes.

**Comment by mandliyarajendra11** [comment]
> @mandliyarajendra11, you can implement it first, and then create a screen recording of the changes.

sure
