### ISSUE TITLE
[Bug]:  link should be open on the new page 

### ISSUE THREAD

**Issue by mandliyarajendra11** [JasonDsouza212/free-hit#687]
### What happened?

When we click on the "Learn More" or "Star the Repo" button, the link should open on a new page/tab. The target attribute should be set to "_blank" for this purpose.

### Add screenshots

Add screenshots
![Screenshot (123)](https://github.com/JasonDsouza212/free-hit/assets/119125519/49c2c21e-f623-4510-ba9a-8214134041a1)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by VijayalakshmiGanesh** [comment]
Hi, 

I would like to work on this issue. Can this be assigned to me under GSSOC'23 label please. Thank you.

**Comment by JasonDsouza212** [comment]
Hey @VijayalakshmiGanesh, as @mandliyarajendra11 created the issue, he will be assigned.
