### ISSUE TITLE
[Feat]:  home page looking empty

### ISSUE THREAD

**Issue by mandliyarajendra11** [JasonDsouza212/free-hit#688]
### What feature?

The home page feels a bit empty when I first visited the website. It was not clear what it was related to. There should be a section here that provides some information and eliminates the feeling of emptiness on the page.

### Add screenshots

Add screenshots

we can add section like this ( not this but look like this in home page  ) 
then we transfer search box from navbar to near at grid list view
![Screenshot (122)](https://github.com/JasonDsouza212/free-hit/assets/119125519/4837f1c3-7080-462a-9bde-f853741ae8b4)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by JasonDsouza212** [comment]
As of now, someone is working on this. If he fails to do it, you will be assigned.

**Comment by mandliyarajendra11** [comment]
> As of now, someone is working on this. If he fails to do it, you will be assigned.

okay

**Comment by mandliyarajendra11** [comment]
> As of now, someone is working on this. If he fails to do it, you will be assigned.

sir still someone working on this issue , if not please assign me this issue

**Comment by JasonDsouza212** [comment]
@mandliyarajendra11 you can start working on this. Can you please tell me what changes are you proposing?

**Comment by mandliyarajendra11** [comment]
> @mandliyarajendra11 you can start working on this. Can you please tell me what changes are you proposing?

Sir, I am going to add the About Us/star the repo  section here with a different image, some different text, and a "Read More" button that will navigate to the About Us page.

Sir, I have noticed some other issues here as well. Could you please assign this issue with a Level-3 label? I will be updating all the items mentioned below.


I didn't notice this earlier. I thought it was part of the design, but when I clicked on it by mistake then i realized it is filter topic feature but it look unnecessary here. We can place it in the red-lined area along with the filter button, and we can also move the search button to that same red-lined area.

![Screenshot (160)](https://github.com/JasonDsouza212/free-hit/assets/119125519/199f245e-abeb-4899-8ed7-31cb18787d4a)
![Screenshot (161)](https://github.com/JasonDsouza212/free-hit/assets/119125519/aa9ff7af-f07a-40d4-bf12-2d46789204f6)

![Screenshot (162)](https://github.com/JasonDsouza212/free-hit/assets/119125519/e3988d3f-b1ba-48b3-b3d3-281a3be255e2)

**Comment by VenomFate-619** [comment]
That is a good suggestion, users indeed find it difficult to know where are filter options until they click it.
do open another issue for this as the current issue is unrelated to it.
we will discuss there further.

**Comment by mandliyarajendra11** [comment]
> That is a good suggestion, users indeed find it difficult to know where are filter options until they click it. do open another issue for this as the current issue is unrelated to it. we will discuss there further.

but it related to home page redesign
