### ISSUE TITLE
Feature: Changing the website style

### ISSUE THREAD

**Issue by priyankarpal** [JasonDsouza212/free-hit#7]
* hey @JasonDsouza212, I'm thinking that we could change the website style.
* Buttons style
* Change the header style & name
* Add a logo, better favicon, meta tags, footer

![Screenshot from 2023-02-19 23-06-39](https://user-images.githubusercontent.com/88102392/219965068-04b1a0c5-ec57-40d7-8ef8-89efbcb2644c.png)

**Comment by JasonDsouza212** [comment]
Ya should make the buttons small, And I was surely thinking of changing the header style

**Comment by priyankarpal** [comment]
@JasonDsouza212 Buttons styles are ready just have to PR
