### ISSUE TITLE
[Feat]: Adding Contact Us Page

### ISSUE THREAD

**Issue by AlabhyaG** [JasonDsouza212/free-hit#707]
### What feature?

There should be a Contact Us page where user can send their enquiry directly to the website.
There is only a contact us button but nothing happens when clicked, so we can add a contact us page

### Add screenshots

![image](https://github.com/JasonDsouza212/free-hit/assets/98676224/8d2b07de-0c37-4f8c-aa46-29fd1aa0efd2)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JasonDsouza212** [comment]
It is just a title

**Comment by AlabhyaG** [comment]
Ok my mistake.
But still we can add a Contact Us page upon clicking the main icon instead of going to mail websites

**Comment by dboatengg** [comment]
I don't think that's necessary.

**Comment by youngancient** [comment]
Hi @AlabhyaG  I figured that a much more proper way would be to add a Contact link to the header on the desktop and mobile sidebar, then there should be a page to which it links to. Pls, assign this issue to me. Thank you.

**Comment by YashPatel-22602** [comment]
@JasonDsouza212 @AlabhyaG  I have Review The issue and i can make the attractive contact page . Please Assign me This issue.
