### ISSUE TITLE
Change button bg-color

### ISSUE THREAD

**Issue by Deva-1903** [JasonDsouza212/free-hit#72]
**To indicate which button is now being clicked, change the button background color**

For instance, when the Remote Jobs button is pressed, the background color of the button should change to indicate that the user is on the Remote Jobs page. When another button is clicked, the color of that button should change, and the Remote Jobs button should return to normal.

![Screenshot (294)](https://user-images.githubusercontent.com/97371915/228735589-1df4acfa-dfe9-4f13-b04e-c23cbd9460b5.png)

**Comment by mishba-ai** [comment]
exactly ,It should button background color should be there

**Comment by JasonDsouza212** [comment]
Yes, that's a good feature you are suggesting. Do you want to work on this, @Deva-1903  ?

**Comment by itsarraj** [comment]
@JasonDsouza212 I almost completed it.

**Comment by itsarraj** [comment]
@JasonDsouza212 Done

**Comment by itsarraj** [comment]
![Screenshot from 2023-03-31 00-25-02](https://user-images.githubusercontent.com/69187344/228936381-90f27762-7fe3-467b-a7b6-7c6e01684938.png)

**Comment by itsarraj** [comment]
@done bro

**Comment by itsarraj** [comment]
accept this pr https://github.com/JasonDsouza212/free-hit/pull/87

**Comment by JasonDsouza212** [comment]
The issue was resolved from @itsarraj
