### ISSUE TITLE
[Feat]: Adding a row for reviews of the users

### ISSUE THREAD

**Issue by deepshikha2708** [JasonDsouza212/free-hit#733]
### What feature?

As we have seen in the e-commerce always having a section for user reviews, similarly we can keep a reviews row fot this website in the home page too. For eg how this website has been useful for all of us.

### Add screenshots

Like this
![image](https://github.com/JasonDsouza212/free-hit/assets/80972038/21847c19-a6f2-4ce5-af3b-b1496e6d586b)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JasonDsouza212** [comment]
@deepshikha2708, Since there is no database, we cannot implement this. Therefore, I'll be closing this issue.
