### ISSUE TITLE
[Feat]: Adding  erviceNow website

### ISSUE THREAD

**Issue by deepshikha2708** [JasonDsouza212/free-hit#737]
### What feature?

ServiceNow is an American software company based in Santa Clara, California that develops a cloud computing platform to help companies manage digital workflows for enterprise operations.

### Add screenshots

![image](https://github.com/JasonDsouza212/free-hit/assets/80972038/964e3366-241d-49df-9fa2-c8c1d3fca015)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by JasonDsouza212** [comment]
I dont think its free

**Comment by deepshikha2708** [comment]
so only the free platforms be provided here?

**Comment by deepshikha2708** [comment]
if not can I add any other website instead of it?
