### ISSUE TITLE
[Feat]: Add coding ninjas to coding platforms

### ISSUE THREAD

**Issue by sumitkr2000** [JasonDsouza212/free-hit#738]
### What feature?

I have an idea to add coding ninjas to coding platforms. It is a very popular coding platform for beginners and professionals also. Please assign me this issue. Thank you!

### Add screenshots

![image](https://github.com/JasonDsouza212/free-hit/assets/100675296/233e562a-ecf4-4471-b919-2ef487adc8dc)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sumitkr2000** [comment]
@JasonDsouza212 @VenomFate-619 Please assign me this issue

**Comment by JasonDsouza212** [comment]
There is a tool in the database called CodeStudio, which is Coding Ninjas, so please edit that name as it is already in the database.
