### ISSUE TITLE
[Feat]: Convert PNG Images to WebP Format for Improved GitHub Project Performance

### ISSUE THREAD

**Issue by Avinash905** [JasonDsouza212/free-hit#743]
### What feature?

Currently, the images in our GitHub project are stored in the PNG image format. However, I would like to convert them to the more efficient WebP format. This conversion will help us reduce file sizes while maintaining image quality, leading to improved website performance and faster loading times. This issue aims to update the entire project's image assets from PNG to WebP format.

In order to optimize our project's image assets and enhance user experience, I propose converting all the PNG images to WebP format. 

### Add screenshots

Add screenshots
![Screenshot (520)](https://github.com/JasonDsouza212/free-hit/assets/56786344/f34e0fe0-b66e-4f7f-bc04-f961881f535d)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Avinash905** [comment]
Please assign me this issue so that I can work on this issue under **GSSOC'23**.

**Comment by VenomFate-619** [comment]
what's your approach to the conversion?
how can we future-proof this issue?

**Comment by Avinash905** [comment]
> what's your approach to the conversion? how can we future-proof this issue?

We can add instructions in the contribution rules to only add webp instead of png/jpg.
