### ISSUE TITLE
[style]: Left aligned website's descriptions.

### ISSUE THREAD

**Issue by ManavMalhotra** [JasonDsouza212/free-hit#753]
### What's the style idea?

To improve consistency and readability on some websites, the descriptions should be left-aligned 

### Add screenshots

![image](https://github.com/JasonDsouza212/free-hit/assets/64147782/4d021592-44c6-4c9d-bd1c-6d120afab3bc)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ManavMalhotra** [comment]
Please assign this issue to me. I can fix it.

**Comment by JasonDsouza212** [comment]
@ManavMalhotra try implementing it and attach screenshot so that I can see the changes

**Comment by ManavMalhotra** [comment]
![image](https://github.com/JasonDsouza212/free-hit/assets/64147782/45831dc3-b2ae-45b4-ba41-deb44f2ce9e9)
@JasonDsouza212 Please review

**Comment by ManavMalhotra** [comment]
Adding a ‘read more’ span tag can improve to show the full description in some websites 
![image](https://github.com/JasonDsouza212/free-hit/assets/64147782/b9c7974c-1f3c-4b9b-bf7a-812e3dfb5bce)
