### ISSUE TITLE
[Feat]: Add Medium blog website

### ISSUE THREAD

**Issue by Pragati76** [JasonDsouza212/free-hit#767]
### What feature?

I have an idea to add medium blog website.

### Add screenshots

![image](https://github.com/JasonDsouza212/free-hit/assets/112195495/b002d851-71dc-4059-8355-72dee3ef15d2)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JasonDsouza212** [comment]
I dont think we can add the blog website as free-tool
