### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by bhavyanarnoli** [JasonDsouza212/free-hit#777]
### What's the style idea?

We need to improve  the footer design 
<img width="756" alt="image" src="https://github.com/JasonDsouza212/free-hit/assets/108413315/33a72597-7910-4bd8-b107-cb4d285d9370">

It looks empty i can make it like this 
<img width="960" alt="image" src="https://github.com/JasonDsouza212/free-hit/assets/108413315/50d07424-7dc4-4fd1-a0b0-eb5014fc041f">

### Add screenshots

Add screenshots
<img width="960" alt="image" src="https://github.com/JasonDsouza212/free-hit/assets/108413315/28584a15-f320-459f-b1b2-d45a10fa324e">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JasonDsouza212** [comment]
If you make the design compatible with all the media queries, we can merge it.
