### ISSUE TITLE
Use Vite instead of create-react-app 

### ISSUE THREAD

**Issue by dhawal-793** [JasonDsouza212/free-hit#78]
Current project uses create-react-app, which internally uses webpack, and this leads to slower build time thus the website is slow.

When any new user try to install dependencies it takes a lot of time to install the dependencies and the real-time updation all not good. 

By using Vite the Website will be very fast, and the build time will reduce, also it is recommended to not use CRA.

**Comment by JasonDsouza212** [comment]
I'm not very familiar with this. I'll comment on this after I read about it

**Comment by priyankarpal** [comment]
should I work on it?

**Comment by dhawal-793** [comment]
> I'm not very familiar with this. I'll comment on this after I read about it

Vite is like create-react-app but very fast, there are no such differences.
Also, the project structure will not change much after using vite.
If you want I can create a pull request and then you can merge it if you want.

If you want to check what will be the project structure you can check out my repository : [dhawal-793.github.io](https://github.com/dhawal-793/dhawal-793.github.io) .

**Comment by priyankarpal** [comment]
> > I'm not very familiar with this. I'll comment on this after I read about it
> 
> Vite is like create-react-app but very fast, there are no such differences. Also, the project structure will not change much after using vite. If you want I can create a pull request and then you can merge it if you want.
> 
> If you want to check what will be the project structure you can check out my repository : [dhawal-793.github.io](https://github.com/dhawal-793/dhawal-793.github.io) .

amazing ❤️

**Comment by dhawal-793** [comment]
Should I start working on this?

**Comment by JasonDsouza212** [comment]
Ok work on it

**Comment by dhawal-793** [comment]
There are some problems in running vite because of pnpm and some deprecated dependencies like "commit".

**Comment by priyankarpal** [comment]
> There are some problems in running vite because of pnpm and some deprecated dependencies like "commit".

just delete that package. also, delete `node_modules` & install fresh packages.

**Comment by dhawal-793** [comment]
I have completely removed all the files and rebuilt the project using vite and it worked.
- I also removed some unwanted dependencies which were preinstalled when creating a react app.
- I also updated the doker file to use the "dev" command instead of "start" as vite uses the dev command.
- Also the new port is 5173 instead of 3000

**Comment by priyankarpal** [comment]
> I have completely removed all the files and rebuilt the project using vite and it worked.
> 
> * I also removed some unwanted dependencies which were preinstalled when creating a react app.
> * I also updated the doker file to use the "dev" command instead of "start" as vite uses the dev command.
> * Also the new port is 5173 instead of 3000
> 
> View pull request #96

sounds good 🎉
