### ISSUE TITLE
[style]: menu icon enability

### ISSUE THREAD

**Issue by BhartiNagpure** [JasonDsouza212/free-hit#780]
### What's the style idea?

Menu icon in navbar shows menu items which is already shows in navbar.
It would be looks more perfect when menu icon enable only in responsive view  and disable in desktop view.

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JasonDsouza212** [comment]
@BhartiNagpure, but that makes the navbar look very empty, which appears odd considering the current feature. With the current setup, users can easily navigate either from the weather sidebar or the navbar.

**Comment by BhartiNagpure** [comment]
we have sign in sign up option also to add in navbar

**Comment by JasonDsouza212** [comment]
As of now, there is no database, so I think we can't use that feature.
