### ISSUE TITLE
[style]: Will improve About Page

### ISSUE THREAD

**Issue by Anubhavgupta14** [JasonDsouza212/free-hit#781]
### What's the style idea?

We need to improve the UI of about page as it is looking so simple, I will add a interactive background, animations, adjust the contents and improve fonts of the texts.

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JasonDsouza212** [comment]
@Anubhavgupta14 someone is already working on it
