### ISSUE TITLE
[Feat]: Add Codepen Frontend tool

### ISSUE THREAD

**Issue by abhinav-m22** [JasonDsouza212/free-hit#795]
### What feature?

I want to add Codepen website as a frontend tool in the website.

CodePen is an online community website for testing and showcasing user-created HTML, CSS and JavaScript code snippets. 

It functions as an online code editor and open-source learning environment, where developers can create code snippets, called "pens," and test them.

### Add screenshots

<img width="960" alt="image" src="https://github.com/JasonDsouza212/free-hit/assets/113239388/59da87ed-962b-4c64-99e1-7789e4b3c9dd">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JasonDsouza212** [comment]
Code pen is already present in the DB
