### ISSUE TITLE
Update: Host it on Vercel or Netlify

### ISSUE THREAD

**Issue by priyankarpal** [JasonDsouza212/free-hit#8]
@JasonDsouza212 can you host it on Vercel or Netlify? it would be great if you host it on any one of these. You can track the visitors also. Now it's ok but it would be more professional if you do it. ✌️

**Comment by JasonDsouza212** [comment]
Ya Ill do that

**Comment by priyankarpal** [comment]
@JasonDsouza212 are you working on this?

**Comment by JasonDsouza212** [comment]
Ya Ill do it tomorrow, Just have some problem with it

**Comment by priyankarpal** [comment]
> Ya Ill do it tomorrow, Just have some problem with it

okkk. Take your time ❤️

**Comment by dhawal-793** [comment]
You can also host it on render.com It is very simple and free.
For a static website like this one it is the best I think as Heroku is not free anymore.

You just need to provide access to the GitHub repo. and You can add any additional envs and custom name also.

**Comment by JasonDsouza212** [comment]
> > Ya Ill do it tomorrow, Just have some problem with it
> 
> okkk. Take your time heart

Just deployed it on versel. Have a look at it.

**Comment by priyankarpal** [comment]
Completed
