### ISSUE TITLE
[Feat]: Adding DALL.E webiste

### ISSUE THREAD

**Issue by Vaibhav9027** [JasonDsouza212/free-hit#802]
### What feature?

I have an idea to add DALL.E website.
It is an AI model which generate images as per the request.

### Add screenshots

![image](https://github.com/JasonDsouza212/free-hit/assets/115151167/bdb11e4b-eae9-45b7-b665-70930fdcdd53)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JasonDsouza212** [comment]
@Vaibhav9027, it's already in the database, so I'm closing this issue.
