### ISSUE TITLE
Feat : Looking for ideas to implement in styles of this cards

### ISSUE THREAD

**Issue by itsarraj** [JasonDsouza212/free-hit#85]
**Is your feature request related to a problem? Please describe.**
 Looking for ideas to implement in styles of this cards

**Describe the solution you'd like**
shadows , borders , and much more

**Describe alternatives you've considered**
no idea

**Additional context**
![Screenshot from 2023-03-30 23-03-23](https://user-images.githubusercontent.com/69187344/228918118-c8cbe3fa-6500-4b0f-b3c1-4bb6aba8814d.png)
![Screenshot from 2023-03-30 23-03-32](https://user-images.githubusercontent.com/69187344/228918173-90260a3f-31d9-4f61-be57-ddd989e898e1.png)

**Comment by priyankarpal** [comment]
It can be simple.

![image](https://user-images.githubusercontent.com/88102392/228940091-27849ca5-3bd2-473e-b35a-0884cc1afc29.png)

**Comment by itsarraj** [comment]
Yes , Similar , Let's have discussion and finalize few things

**Comment by JasonDsouza212** [comment]
Try keeping them simple as @priyankarpal said

**Comment by priyankarpal** [comment]
is it open?

**Comment by JasonDsouza212** [comment]
No , I'll close it now
