### ISSUE TITLE
[Feat]: Open-Source ML platform tool

### ISSUE THREAD

**Issue by Parul1606** [JasonDsouza212/free-hit#852]
### What feature?

I would like to add Mindsdb an Open-Source Machine Learning platform tool.
MindsDB is an open-source machine learning platform that simplifies the process of building predictive models. It empowers users with automated machine learning capabilities, enabling them to easily analyze and predict outcomes from their data. MindsDB aims to democratize AI by making it accessible to non-technical users.

### Add screenshots

![image](https://github.com/JasonDsouza212/free-hit/assets/80768852/a40c41f7-c4ea-4ce9-85ca-1c30988017b8)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JasonDsouza212** [comment]
I dont think this is free

**Comment by Parul1606** [comment]
Oh yes sorry, but it's an open source community too. Contributors can use this to deploy their projects, contribute, join hackathons, etc.
Here's a link to the website- [https://mindsdb.com/](url)
![Screenshot 2023-06-27 203912](https://github.com/JasonDsouza212/free-hit/assets/80768852/d6ef0943-f64b-46a8-91a5-8cc1fea3a7e2)
