### ISSUE TITLE
[Feat]: Footer components not aligned properly 

### ISSUE THREAD

**Issue by lakshmishreea122003** [JasonDsouza212/free-hit#861]
### What feature?

I have an idea 
The components in the footer are aligned in a way that a few of them are to the left the rest are in the center. I wish to change the alignment of the components to make them look more appealing.
Either all components are aligned to the center or to the left.

### Add screenshots

Add screenshots
![footer](https://github.com/JasonDsouza212/free-hit/assets/117621286/d5dbdccb-043a-4703-b6a9-790b34c9df1b)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lakshmishreea122003** [comment]
I wish to contribute as a GSSoC contributor.

**Comment by JasonDsouza212** [comment]
@lakshmishreea122003, could you please inform me about the media width, browser, and operating system in which you are encountering this bug?

**Comment by lakshmishreea122003** [comment]
I use gitpod.
I felt it would be great if all the components were uniformly aligned to the center. After changes are made the footer will appear in a similar manner on all screen sizes.
I am also ready to make the components be left aligned based on your opinion.

**Comment by lakshmishreea122003** [comment]
The components like the title, the sentence "Find the tools...................bank", contact us and the icons will center aligned to the center. 
Do assign it to me. I wish to make the footer a bit more appealing to the users.

**Comment by VenomFate-619** [comment]
do add a screen shot of what you want to do.
try to first make it on figma and do post it here.

**Comment by lakshmishreea122003** [comment]
I shall share the screen shots by today.
