### ISSUE TITLE
[Feat]: Add ChatPDF

### ISSUE THREAD

**Issue by Parul1606** [JasonDsouza212/free-hit#876]
### What feature?

I would like to add ChatPDF - Chat with Pdf.
ChatPDF is an innovative platform that allows users to interact and chat with PDF documents. By integrating natural language processing and AI technologies, ChatPDF enables users to ask questions, extract information, and perform actions within the PDF through conversational interactions. It simplifies document navigation and enhances the user experience by bringing interactivity to static PDF files.

### Add screenshots

![image](https://github.com/JasonDsouza212/free-hit/assets/80768852/50654b9f-0c92-4b35-ac92-5aa83f7fd968)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by VenomFate-619** [comment]
will you like to work on this ?

**Comment by Parul1606** [comment]
Hello @JasonDsouza212 @VenomFate-619 , I have added my work still my issue has been closed. Please look into the matter
