### ISSUE TITLE
[Feat]: Add Storybook

### ISSUE THREAD

**Issue by Parul1606** [JasonDsouza212/free-hit#905]
### What feature?

I would like to add Storybook.
It is used to Build UIs without the grunt work. Storybook provides a workshop to build UIs in isolation. It helps you develop hard-to-reach states and edge cases without needing to run the whole app. Storybook will look into your project's dependencies during its install process and provide you with the best configuration available.

### Add screenshots

![image](https://github.com/JasonDsouza212/free-hit/assets/80768852/bd834f29-2283-430e-83a6-5581ffff2079)

![image](https://github.com/JasonDsouza212/free-hit/assets/80768852/16fd9e7f-b547-4541-9388-a8ae9d4c0e39)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JasonDsouza212** [comment]
is this free

**Comment by Parul1606** [comment]
Yes
