### ISSUE TITLE
[Feat]: Add Frontend PRO for Learn, Build Challenges of Front End Tech Stacks

### ISSUE THREAD

**Issue by NarendraKoya999** [JasonDsouza212/free-hit#906]
### Issue Description
- **`Add Frontend PRO for Learn, Build Challenges for Front End Tech Stacks`**

### Add screenshots

Add screenshots
![freehit-12](https://github.com/JasonDsouza212/free-hit/assets/84512164/45f279fb-8309-4662-a24f-60a04a839d4c)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### NOTE: I want to work on this Issue

**Comment by karantec** [comment]
please assign me this issue i will solve under GSSOC'23

**Comment by agrawalVasu9** [comment]
please assign me this issue i will solve under GSSOC'23

**Comment by agrawalVasu9** [comment]
Please assign me this issue, I will solve under GSSOC'23...as soon as possible

**Comment by NarendraKoya999** [comment]
Hi @JasonDsouza212 . Please review on this Issue. If possible, assign me

**Comment by NarendraKoya999** [comment]
Hi @JasonDsouza212 . Please look into this Issue. It's one month ago raised Issue . Still not Respond. Please take a review on this Issue
