### ISSUE TITLE
[Feat]: Replace the website with the working one

### ISSUE THREAD

**Issue by gks2022004** [JasonDsouza212/free-hit#931]
### What feature?

On home page there's a 4th website called 9animetv that does not work as 9animetv is discontinued, so we can add zoro.to website , which is also for the same service, so assign me this task , I can change it, so that people can enjoy it.

### Add screenshots

Add screenshots
![Screenshot 2023-06-28 134313](https://github.com/JasonDsouza212/free-hit/assets/94637265/a6bdc622-e449-4fff-95a5-73776a45700d)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JasonDsouza212** [comment]
@gks2022004 ,Zoro.to is already in the DB

**Comment by gks2022004** [comment]
okk,  sorry I didn't notice that

**Comment by bharathkalyans** [comment]
> @gks2022004 ,Zoro.to is already in the DB

`Zoro.to` has been shifted to `https://aniwatch.to/`!
