### ISSUE TITLE
[Feat]: Contact Page 

### ISSUE THREAD

**Issue by SyedImtiyaz-1** [JasonDsouza212/free-hit#936]
### What feature?

Hello @JasonDsouza212 ,
Adding Contact form as the website doesn't have any Contact Section.
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JasonDsouza212** [comment]
How are you planning on implementing it

**Comment by SyedImtiyaz-1** [comment]
@JasonDsouza212 , I'm thinking that contact page with name email and message would be sufficient and will improve the code base with validations
and the UI will be as per the theme of the website.
