### ISSUE TITLE
[Feat]:  Gsoc organizations 

### ISSUE THREAD

**Issue by mandliyarajendra11** [JasonDsouza212/free-hit#959]
### What feature?

Gsoc oraganization is website providing list of open source org who participate in Google summer of code 

Link -https://www.gsocorganizations.dev/?filters=%7B%22years%22%3A%5B%5D%2C%22categories%22%3A%5B%5D%2C%22technologies%22%3A%5B%22javascript%22%2C%22reactjs%22%5D%2C%22topics%22%3A%5B%22web%22%5D%2C%22shortcuts%22%3A%5B%5D%7D

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JasonDsouza212** [comment]
I tink this cant be considered as free-tool
