### ISSUE TITLE
[style]:  filter and search box

### ISSUE THREAD

**Issue by mandliyarajendra11** [JasonDsouza212/free-hit#963]
### What's the style idea?

Sir, I have noticed some other issues here as well. Could you please assign this issue with a Level-3 label? I will be updating all the items mentioned below.

I didn't notice this earlier. I thought it was part of the design, but when I clicked on it by mistake then i realized it is filter topic feature but it look unnecessary here. We can place it in the red-lined area along with the **filter button & search button .**

### Add screenshots

![Screenshot (160)](https://github.com/JasonDsouza212/free-hit/assets/119125519/199f245e-abeb-4899-8ed7-31cb18787d4a)
![Screenshot (161)](https://github.com/JasonDsouza212/free-hit/assets/119125519/aa9ff7af-f07a-40d4-bf12-2d46789204f6)

![Screenshot (162)](https://github.com/JasonDsouza212/free-hit/assets/119125519/e3988d3f-b1ba-48b3-b3d3-281a3be255e2)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mandliyarajendra11** [comment]
> Thats not looking good and can you explain more about this

ye jo menu h esko es red box vale area me add karna chahta with filter name hu kyoki ye menu ka pata sahi se nahi chal pa raaha h 


filter button par click karne par ek module/pop box type open hoga and usme ye sare option honge 

and search box ko bhi esi red line area me shift kar dete header ki bajaye vaha better rahega

**Comment by JasonDsouza212** [comment]
@mandliyarajendra11, please give it a try, and let's see if we like the design and functionality. If we do, we can merge it.
