### ISSUE TITLE
[Feat]:  Add Indeed to remote jobs section

### ISSUE THREAD

**Issue by mnj93** [JasonDsouza212/free-hit#965]
### What feature?

I have an idea 

Can we add [Indeed](https://www.indeed.com/jobs?q=software&l=remote&vjk=1edb7aba240ecbc3) to remote jobs section? 

### Add screenshots

[![Screenshot-2023-06-30-at-6-11-32-PM.png](https://i.postimg.cc/TYv1GZsC/Screenshot-2023-06-30-at-6-11-32-PM.png)](https://postimg.cc/5jpbSkbC)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JasonDsouza212** [comment]
Indeed, it is not exclusively for remote jobs. There are also many tools in the remote sector that are not solely remote job platforms. In order to enhance this, would you like to work on more complex issue?
