### ISSUE TITLE
[Feat]: Adding Login/Sign-in Page

### ISSUE THREAD

**Issue by SyedImtiyaz-1** [JasonDsouza212/free-hit#981]
### I have an idea -
Hello @JasonDsouza212 ,
Adding a login/sign in is a great idea like after that if a user logined that time he/she can see all the bookmarks and we can also connect the Login btn with Oauth for connecting the user to the wesbite and after that we can display the name of the user.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JasonDsouza212** [comment]
@SyedImtiyaz-1 as there is no database, we can't achieve that functionality
