### ISSUE TITLE
[Feat]: Create hover effect for items in ListView

### ISSUE THREAD

**Issue by lakshmishreea122003** [JasonDsouza212/free-hit#992]
### What feature?

I have an idea 
I want to add a hover effect for the items in the ListView as in the GridView. Here when the user hovers over the item the item must appear raised, basically lifting up the components on hover.

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lakshmishreea122003** [comment]
I wish to contribute to it as a GSSoC contributor

**Comment by lakshmishreea122003** [comment]
Sorry for the delay. I shall come up with the PR by tomorrow

**Comment by adhamahmad** [comment]
I can work on this if it is still available.  @JasonDsouza212
