### ISSUE TITLE
[Feat]: Add HeyGen AI

### ISSUE THREAD

**Issue by SargamPuram** [JasonDsouza212/free-hit#994]
### What feature?

HeyGen is an AI video generation platform . 
It will require changes in products.json file
category : ai

### Add screenshots

Add screenshots
![Spline2](https://github.com/JasonDsouza212/free-hit/assets/130867468/0bcd60c4-4d7c-4d20-9274-f28c6a27ffc1)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SargamPuram** [comment]
Thanks for acknowledging my issue . Kindly assign me this issue under GSSOC'23.

**Comment by JasonDsouza212** [comment]
The template you used is incorrect. Please use the correct template and create a new issue.

**Comment by SargamPuram** [comment]
@JasonDsouza212 , I'm sorry for the blunder.
But can you please specify which template are you talking about, so that I'll rectify it in the new issue.
